decred/politeia

- .travis.yml
- README.md
- goclean.sh
- politeiad/api/v1/identity/identity.go
- politeiad/backend/gitbe/database.go
- politeiad/backend/gitbe/git.go
- politeiad/backend/gitbe/git_test.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/backend/gitbe/gitbe_test.go
- politeiad/cmd/politeia/politeia.go
- politeiad/config.go
- politeiawww/backend.go
> travis: enable

- politeiawww/backend.go
- politeiawww/cmd/politeiawww_refclient/politeiawww_refclient.go
> [www] Fix bug: title is publicly viewable for unvetted proposals

- politeiad/api/v1/v1.go
- politeiad/backend/backend.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/cmd/politeia/politeia.go
- politeiad/politeiad.go
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/backend_proposal_test.go
- politeiawww/backend_user_test.go
- politeiawww/cmd/politeiawww_refclient/politeiawww_refclient.go
- politeiawww/comments.go
- politeiawww/convert.go
- politeiawww/www.go
- util/json.go
Rework errors in politeiad so that they're JSON and include an error
code, and enhance www to pass errors from politeiad up to the client.
Fixes #65.
Fixes #79.
Fixes #114.
> Rework errors in politeiad and www

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
> www: Add userid to /user/me reply

- politeiawww/backend.go
- politeiawww/cmd/politeiawww_refclient/politeiawww_refclient.go
- politeiawww/middleware.go
- politeiawww/www.go
We don't want to fail at startup so load the inventory in a lazy fashion.  Try to make sure we don't race the inventory load.
> [www] Lazy load inventory

- politeiawww/api/v1/v1.go
- politeiawww/www.go
> [www] Add map of human readable error codes

- politeiawww/backend.go
- politeiawww/comments.go
> [www] Always init comment map when inserting props into inventory

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/backend_proposal_test.go
- util/proposal.go
- util/proposal_test.go
> [www]Adding proposal name maximum length Policy 

- politeiawww/backend.go
This makes the tests run slightly faster.
> [www] use minimum bcrypt cost when testing

- Gopkg.lock
- Gopkg.toml
- politeiad/api/v1/v1.go
- politeiad/backend/backend.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/backend/gitbe/gitbe_test.go
- politeiad/cmd/politeia/politeia.go
- politeiad/cmd/politeia_verify/politeia_verify.go
- politeiad/politeiad.go
- politeiad/sample-politeiad.conf
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/convert.go
Politeia is too proposal centric and needs to become more generic.  This PR should capture that desire.
Fixes #132 #138
> [politeiad] Make politeia more generic

- README.md
> [readme] Correct dep and go install examples

- README.md
I saw this in an issue but can't find it.  Just simply add the example that is needed.
> Document build process of politeia cli tool.

- politeiad/cmd/politeia/politeia.go
- politeiawww/config.go
- politeiawww/www.go
> [www] allow non-interactive identity fetch for containers

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/comments.go
- politeiawww/comments_test.go
Fixes #118 
Max length was set to 8000.
> [www] add max comment length policy (#118)

- examples/bugbounty/README.md
- examples/bugbounty/admin_censor.sh
- examples/bugbounty/admin_inventory.sh
- examples/bugbounty/admin_publish.sh
- examples/bugbounty/badbug1.txt
- examples/bugbounty/get_unvetted.sh
- examples/bugbounty/notabug1.txt
- examples/bugbounty/report_bug.sh
- examples/bugbounty/report_silly_bug.sh
- examples/bugbounty/settings.sh
These are the examples that were used for the politeia competition presentation.
> [examples] Add some examples of generic use.

- politeiad/backend/gitbe/gitbe.go
Make sure to skip unanchored digests when generating the precious list
for dcrtime fsck.  This fixes a bug where you publish a record followed
by an immediate ctrl-c.
> Don't fsck non-precious digests.

- Gopkg.lock
- politeiad/api/v1/api.md
- politeiad/api/v1/v1.go
- politeiad/backend/backend.go
- politeiad/backend/gitbe/git.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/backend/gitbe/gitbe_test.go
- politeiad/cmd/politeia/README.md
- politeiad/cmd/politeia/politeia.go
- politeiad/politeiad.go
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/comments.go
- politeiawww/comments_test.go
- politeiawww/convert.go
- util/convert.go
> [politeiad] Add multiple metadata streams.

- politeiad/cmd/politeia_verify/politeia_verify.go
> [politeiad] Add -jsonin and -jsonout options to the verification tool

- politeiawww/sample-politeiawww.conf
> [WIP] [www] add config sample

- politeiawww/api/v1/api.md
> [www] Add API docs for /user/key and /user/key/verify

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/backend_user_test.go
- politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
- politeiawww/cmd/politeiawww_refclient/client.go
- politeiawww/cmd/politeiawww_refclient/main.go
- politeiawww/convert.go
- politeiawww/database/database.go
- politeiawww/database/localdb/encoding.go
- politeiawww/database/localdb/localdb.go
- politeiawww/www.go
Also add user-proposal associations to proposal metadata, unit tests, and API docs.
Fixes #59.
Fixes #194.
> [www] Add route for fetching proposals for a user.

- politeiad/politeiad.go
Fixes #207 
I've also added a wrapper function for adding new routes. The same as we are doing on www.
> Set a wrapper for adding new routes and add support for StrictSlash

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/cmd/politeiawww_refclient/client.go
- politeiawww/www.go
> [www] Return paywall address on /user/me and /user/login

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/cmd/politeiawww_refclient/main.go
This PR adds a `numcomments` field for proposals.
Fixes #146.
> [www] Add numcomments field for proposals

- politeiawww/backend.go
- politeiawww/backend_proposal_test.go
- politeiawww/cmd/politeiawww_refclient/main.go
- politeiawww/www.go
> return proposal tittle

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/backend_proposal_test.go
- politeiawww/cmd/politeiawww_refclient/client.go
> add publickey field for verification

- decredplugin/decredplugin.go
- politeiad/backend/gitbe/decred.go
- politeiavoter/config.go
- politeiavoter/politeiavoter.go
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/cmd/politeiawww_refclient/client.go
- politeiawww/database/localdb/localdb.go
- politeiawww/www.go
There are some differences between regular and proxy mode on politeiawww and we need to cope with it. Fix default DNS names while here.
> Fix several deployment nits.

- politeiawww/api/v1/api.md
@jrick yelled about ... in JSON so remove it and clean up some {[]} while at it.
> Fix some indentation and brackets

- politeiawww/www.go
In order to not confuse users we need to persist the CSRF key.
> Persist CSRF key

- politeiawww/config.go
- politeiawww/www.go
This reverts commit 5433e70e6652a568c6013dcbabfbf7617d42b0c2.
Unfortunately this breaks some things and we will have to revisit later.
> Revert "remove proxy toggle. (#247)"

- LICENSE
> Update Years LICENSE

- politeiawww/backend.go
> Always return user Id info within unvetted proposal info

- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/inventory.go
> Do not allow users (admins) change the status from their own proposals

- .gitignore
- Gopkg.lock
- politeiawww/cmd/politeiawwwcli/README.md
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/commands/changepassword.go
- politeiawww/cmd/politeiawwwcli/commands/getcomments.go
- politeiawww/cmd/politeiawwwcli/commands/getproposal.go
- politeiawww/cmd/politeiawwwcli/commands/getunvetted.go
- politeiawww/cmd/politeiawwwcli/commands/getvetted.go
- politeiawww/cmd/politeiawwwcli/commands/login.go
- politeiawww/cmd/politeiawwwcli/commands/logout.go
- politeiawww/cmd/politeiawwwcli/commands/me.go
- politeiawww/cmd/politeiawwwcli/commands/newcomment.go
- politeiawww/cmd/politeiawwwcli/commands/newproposal.go
- politeiawww/cmd/politeiawwwcli/commands/newuser.go
- politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go
- politeiawww/cmd/politeiawwwcli/commands/resetpassword.go
- politeiawww/cmd/politeiawwwcli/commands/secret.go
- politeiawww/cmd/politeiawwwcli/commands/setproposalstatus.go
- politeiawww/cmd/politeiawwwcli/commands/startvote.go
- politeiawww/cmd/politeiawwwcli/commands/updateuserkey.go
- politeiawww/cmd/politeiawwwcli/commands/userproposals.go
- politeiawww/cmd/politeiawwwcli/commands/verifyuser.go
- politeiawww/cmd/politeiawwwcli/commands/verifyuserpayment.go
- politeiawww/cmd/politeiawwwcli/config/config.go
- politeiawww/cmd/politeiawwwcli/main.go
This is a command line tool that allows you to interact with the Politeia API (#252).
> politeiawwwcli

- decredplugin/decredplugin.go
- politeiad/backend/gitbe/decred.go
- politeiawww/api/v1/v1.go
Fixes bug where votes are not recorded.
> Always create ballot journal directory

- decredplugin/decredplugin.go
- politeiad/backend/gitbe/decred.go
- politeiawww/api/v1/v1.go
- politeiawww/cmd/politeiawww_refclient/main.go
- politeiawww/comments.go
- politeiawww/inventory.go
> Don't allow a user to go past +1 or -1 during comment up/down vote

- decredplugin/decredplugin.go
- politeiad/api/v1/v1.go
- politeiad/backend/backend.go
- politeiad/backend/gitbe/decred.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/backend/gitbe/gitbe_test.go
- politeiad/cmd/politeia_verify/politeia_verify.go
- politeiad/politeiad.go
- politeiawww/backend.go
> We need to version all disk structures

- politeiawww/backend.go
- politeiawww/cmd/politeiawww_refclient/main.go
> Do not update www inventory in case of like comment failure

- politeiawww/cmd/politeiawww_dataload/main.go
> [dataload] Fix bug with user ids for created users all being 0.

- politeiawww/cmd/politeiawww_dataload/README.md
- politeiawww/cmd/politeiawww_dataload/main.go
> [dataload] Improve error msg when create user fails

- decredplugin/decredplugin.go
- politeiad/backend/backend.go
- politeiad/backend/gitbe/decred.go
- politeiad/backend/gitbe/gitbe.go
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/cmd/politeiawww_refclient/client.go
- politeiawww/cmd/politeiawww_refclient/main.go
- politeiawww/www.go
Request: `https://localhost:3000/api/v1/user/proposals/2355ef39e9dbc3c7d1b2b4a1ac8971bbe29585330e10981e299eec2408253e93/commentsvotes`
Returns (for the current logged in user)
```
{"commentsvotes":[{"action":"1","commentid":"1","token":"2355ef39e9dbc3c7d1b2b4a1ac8971bbe29585330e10981e299eec2408253e93"},{"action":"1","commentid":"2","token":"2355ef39e9dbc3c7d1b2b4a1ac8971bbe29585330e10981e299eec2408253e93"}]}
```
> [www + decredplugin] Improve comment voting logic and return user votings

- politeiad/config.go
- politeiavoter/config.go
- politeiawww/cmd/politeiawww_dataload/config.go
- politeiawww/cmd/politeiawww_refclient.sh
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/client/util.go
- politeiawww/cmd/politeiawwwcli/commands/newproposal.go
- politeiawww/cmd/politeiawwwcli/config/config.go
- politeiawww/cmd/politeiawwwtest/main.go
- util/file.go
> [wwwcli] Newproposal command takes files or the --random flag should be especified

- politeiavoter/politeiavoter.go
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/convert.go
- politeiawww/www.go
It will significantly decrease the amount of data requested by the GUI when accessing the list of public proposals or a single proposal details
closes #312
> [www] Add alternative endpoints for the GUI

- README.md
Clarifies location of .conf files
> Readme Tweak

- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go
- politeiawww/cmd/politeiawwwcli/commands/votecomment.go
- politeiawww/cmd/politeiawwwtest/main.go
> add votecomment command to politeiawwwcli

- politeiad/backend/gitbe/decred.go
> [politeiad] Don't throw a stack trace when there are no comments

- Gopkg.lock
- politeiad/backend/gitbe/decred.go
Batch largest commitment addresses instead of doing one at a time.
> gitbe: use batch transactions dcrdata request

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/backend_user_test.go
- politeiawww/www.go
> [www] Fix several issues with new user signup.

- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/commands/commentsvotes.go
- politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go
- politeiawww/cmd/politeiawwwtest/main.go
> [wwwcli] Add commentsvotes command

- politeiawww/api/v1/v1.go
- politeiawww/backend.go
> [www] Don’t allow up/down votes on comments when prop voting is active

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
> [WWW] Update API docs

- politeiavoter/config.go
- politeiavoter/politeiavoter.go
Fix bug where we use testnet wallet by default when voting.
> Add option to select wallet and use sane wallet defaults

- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/config.go
- politeiawww/database/database.go
- politeiawww/templates.go
> [www] Lock user after many login attempts

- README.md
- politeiawww/api/v1/api.md
- politeiawww/sample-politeiawww.conf
This PR fixes some minor issues.
- update README politeiawww.conf
- add new login error `ErrorStatusUserLocked`
- update sample-politeiawww.conf
> Fix some minor issues

- politeiawww/admin.go
- politeiawww/admin_test.go
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/backend_user_test.go
- politeiawww/cmd/politeiawww_dataload/main.go
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/commands/edituser.go
- politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go
- politeiawww/cmd/politeiawwwcli/commands/userdetails.go
- politeiawww/config.go
- politeiawww/database/database.go
- politeiawww/paywall.go
- politeiawww/www.go
> [www] Add admin routes for user mgmt.

- politeiawww/cmd/politeiawww_dataload/main.go
- politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
Closes #399 
This PR makes the following changes to politeiawww_dbutil and politeiawww_dataload.
politeiawww_dbutil:
- remove commands: expireverification, clearpaywall, newuser
- add the addcredits command to allow for creating proposal credits
politeiawww_dataload
- update to use the cli edituser command to clear user paywalls
- have the admin account start off with 5 proposal credits
> Add the addcredits cmd to dbutil and update dataload

- politeiawww/cmd/politeiawww_dataload/main.go
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/client/util.go
- politeiawww/cmd/politeiawwwcli/commands/getproposal.go
- politeiawww/cmd/politeiawwwcli/commands/getunvetted.go
- politeiawww/cmd/politeiawwwcli/commands/getvetted.go
- politeiawww/cmd/politeiawwwcli/commands/newproposal.go
- politeiawww/cmd/politeiawwwcli/commands/userproposals.go
- politeiawww/cmd/politeiawwwtest/main.go
Closes #347 
This PR updates politeiawwwcli to verify the integrity of any proposals that it fetches.
> [wwwcli] Verify proposal integrity anytime proposals are fetched

- politeiawww/backend.go
> [www] Prevent timing attack on login route.

- README.md
- politeiad/cmd/politeia_verify/README.md
- politeiawww/cmd/politeiawww_dataload/README.md
- politeiawww/cmd/politeiawww_dbutil/README.md
- politeiawww/sample-politeiawww.conf
> Improve the developer documentation.

- politeiawww/www.go
* Delete session files on logout.
* Fix a bug where invalid sessions cause an unhandled error
in the server.
Fixes #288.
> [www] Address a couple session-related issues.

- politeiawww/admin.go
- politeiawww/user.go
- politeiawww/www.go
This PR makes the user's details route public and return the fields accordingly to the user access level.
closes #416
> [WWW] Make user's details route public

- politeiad/api/v1/v1.go
- politeiad/backend/backend.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/cmd/politeia/politeia.go
- politeiad/politeiad.go
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/convert.go
- politeiawww/inventory.go
- politeiawww/inventory_test.go
- politeiawww/user.go
This branch implement fixes/updates to the main PR branch #420
> [Temporary branch] Edit records

- politeiad/api/v1/v1.go
- politeiad/politeiad.go
- politeiawww/www.go
> [WWW/d] Handle errors: (www) log out twice crashes / (d) Better error message for invalid rpc creds

- politeiad/backend/gitbe/gitbe.go
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/backend_proposal_test.go
- politeiawww/cmd/politeiawww_dataload/main.go
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/commands/setproposalstatus.go
- politeiawww/cmd/politeiawwwtest/main.go
- politeiawww/convert.go
- politeiawww/inventory_test.go
> Enable admins to input a censor message 

- politeiawww/cmd/politeiawww_dataload/config.go
- politeiawww/cmd/politeiawww_dataload/main.go
Helps testing https://github.com/decred/politeiagui/issues/552
Also useful to bulk test the UI to see how it performs with a large amount of proposals/comments.
> [wwwdataload] Add options for number of vetted and unvetted proposals and comments

- politeiawww/cmd/politeiawwwcli/commands/changepassword.go
- politeiawww/cmd/politeiawwwcli/commands/newuser.go
- politeiawww/cmd/politeiawwwcli/commands/resetpassword.go
Closes #441 
This PR adds password length validation to politeiawwwcli.
> [wwwcli] Enforce password length requirement.

- politeiad/api/v1/v1.go
- politeiad/backend/backend.go
- politeiawww/api/v1/v1.go
This PR updates proposal status comments and metadata status comments that are no longer correct.
> Update proposal status and md status comments.

- .gitignore
- politeiawww/config.go
- politeiawww/www.go
as https://github.com/decred/politeiagui/pull/419 was merged now we can remove the proxy flag from politeiawww
> [www] Remove proxy flag

- politeiawww/api/v1/v1.go
- politeiawww/backend.go
tweak for https://github.com/decred/politeiagui/issues/579
> [WWW] Add end height info within vote status response

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/www.go
This PR is a necessary backend tweak for the GUI work on https://github.com/decred/politeiagui/issues/623.
> [WWW] Provide session max age on login reply

- politeiawww/cmd/politeiawww_dataload/main.go
- politeiawww/cmd/politeiawwwcli/commands/newcomment.go
Closes #481 
Fix multiple bugs in politeiawww_dataload to get it working again.
> [dataload] Fix multiple bugs.

- Gopkg.lock
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/comments.go
- politeiawww/inventory.go
- politeiawww/www.go
Also sneak in some bits from @fernandoabolafio on inventory management.
Supersedes #491 Closes #491
> [audit] Fix a bunch of locks and logical race conditions

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/inventory.go
closes https://github.com/decred/politeia/issues/462
> [WWW] Provide count of user proposals on LoginReply

- politeiad/backend/gitbe/anchors.go
- politeiad/backend/gitbe/decred.go
- politeiad/backend/gitbe/git.go
- politeiad/backend/gitbe/git_test.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/backend/gitbe/gitbe_test.go
- politeiad/backend/gitbe/journal.go
- politeiad/backend/gitbe/journal_test.go
- politeiad/backend/gitbe/plugin.go
- politeiad/backend/gitbe/readme.go
> [politeiad] Add generated README.md for the vetted repo.

- politeiawww/api/v1/api.md
> Fix set proposal status reply example

- politeiawww/api/v1/v1.go
- politeiawww/backend.go
This diff adds the user registration payment tx to LoginReply.
> [www] Add paywallTxID to LoginReply.

- politeiavoter/README.md
- politeiavoter/config.go
- politeiavoter/politeiavoter.go
- politeiavoter/sample-politeiavoter.conf
Politeiavoter needed some sprucing up. Fix some minor bugs and add some documentation.
> [politeiavoter] Cleanup politeiavoter

- politeiawww/backend.go
- politeiawww/config.go
- politeiawww/templates.go
- politeiawww/www.go
> [WWW] Email admin users for new submitted proposals

- politeiawww/admin.go
- politeiawww/backend.go
> [www] Add the censor message to the admin logfile.

- politeiawww/admin.go
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/cmd/politeiawww_dataload/main.go
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/commands/edituser.go
> [www] Add admin ability to lock users.

- politeiawww/cmd/politeiawwwcli/commands/help.go
- politeiawww/cmd/politeiawwwcli/commands/login.go
First try. 
I need feedback.
Thanks 
@lukebp
> Add help command to politeiawwwcli

- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
> [www] Add new vote fields into vote status reply

- politeiavoter/config.go
This is for testing only! Do not use.
> [politeiavoter] Add a proxy check bypass

- politeiavoter/politeiavoter.go
Closes #562 
This commit prevents politeiavoter from casting votes with tickets that have already voted on the proposal.
> politeiavoter: filter already voted tickets

- politeiavoter/config.go
- politeiavoter/log.go
- politeiavoter/params.go
- politeiavoter/politeiavoter.go
> politeiavoter: Shuffle the tickets

- politeiavoter/politeiavoter.go
This commit updates the way in which the delays between votes are calculated when the `--voteduration` flag is used. Votes are cast at random intervals while still ensuring that all votes are cast within the vote duration limit.
Vote delays are random durations between the range `[0, voteDuration/numVotes * 2]`.  The `voteDuration` is a hard cap.  politeiavoter ensures that the cumulative vote delays are less than `voteDuration`.
> politeiavoter: Update vote delay calculation

- politeiawww/backend.go
closes https://github.com/decred/politeiagui/issues/852
> [WWW] Voting finishes when voteEndHeight >= currentHeight

- politeiawww/user.go
Fixes #597 
Needed for https://github.com/decred/politeiagui/issues/871
> Return admin status

- politeiawww/admin.go
- politeiawww/admin_test.go
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/cmd/politeiawww_dataload/main.go
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/commands/commands.go
- politeiawww/cmd/politeiawwwcli/commands/edituser.go
- politeiawww/cmd/politeiawwwcli/commands/manageuser.go
- politeiawww/config.go
- politeiawww/database/database.go
- politeiawww/email.go
- politeiawww/events.go
- politeiawww/templates.go
- politeiawww/user.go
- politeiawww/www.go
This commit adds email notifications for users' own proposals, other
users' proposals, and for admins only. It adds a simple event system to
achieve these notifications while keeping them separate from the logic
that triggers them.
It also refactors the admin action logging to use the event system.
Closes #539.
> www: Implement email notifications.

- politeiad/api/v1/api.md
- politeiad/api/v1/v1.go
- politeiad/backend/backend.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/backend/gitbe/gitbe_test.go
- politeiad/politeiad.go
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/backend.go
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/cmd/politeiawwwcli/commands/authorizevote.go
- politeiawww/cmd/politeiawwwcli/commands/getproposal.go
- politeiawww/www.go
> www + d: Enable getting vetted proposals by version

- politeiawww/user_test.go
This commit adds test coverage for:
* ProcessUserDetails
* ProcessEditUser
> www: Add tests for user.go routes

- politeiad/backend/gitbe/journal.go
While here shorten time file is open.
> [politeiad] Add file sync to append path

- politeiad/backend/gitbe/decred.go
`tallyVotes` replays the ballot journal for a proposal in order to tally the votes.  `tallyVotes` does not hold a lock on the journal while replaying it, so `tallyVotes` must be called with `gitBackEnd` locked in order to prevent a race into the journal.
> d: Prevent journal race on vote tally

- politeiad/config.go
- politeiawww/cmd/politeiawww_dataload/config.go
- politeiawww/config.go
> multi: Fixes double printing of -h,--help message

- politeiawww/backend.go
> www: returns proper error when proposal's version equals 0

- .travis.yml
- Gopkg.lock
- Gopkg.toml
- goclean.sh
- politeiawww/www.go
> Set SameSite cookie option.

- go.mod
- politeiawww/api/v1/api.md
- politeiawww/api/v1/v1.go
- politeiawww/cmd/politeiawwwcli/commands/commands.go
- politeiawww/cmd/politeiawwwcli/commands/help.go
- politeiawww/cmd/politeiawwwcli/commands/subscribe.go
- politeiawww/middleware.go
- politeiawww/www.go
- util/websockets.go
Websockets operate on a subscription level. Client sends a subscribe
command to the server and then the server will start pushing
notifications.
closes #547
> Add websockets to provide server notifications.

- politeiawww/backend.go
- politeiawww/config.go
- politeiawww/email.go
- politeiawww/templates.go
Implements an email template for notifying users when his password is changed.
closes #673
> www: Sends email notification when password is changed

- util/paywall.go
Pleases recent travis govet complaining
> Remove redundant err check

- politeiad/backend/gitbe/gitbe.go
> politeiad: read g.shutdown locked

- politeiawww/api/www/v1/api.md
- politeiawww/api/www/v1/v1.go
- politeiawww/invoices.go
Only allow invoices to be edited when not approved, rejected or paid.
> Add Status check in editinvoice

- politeiawww/api/www/v1/v1.go
> [CMS] Fix typo in errorstatus

- politeiad/cache/cockroachdb/cockroachdb.go
- politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
Fixes connecting to postgresql directly.
> Do not set ssl=true since sslmode=required.

- README.md
This link is broken and refclient no longer exists
> Remove politeiawww_refclient link from readme

- politeiawww/invoices.go
> [cms] Fix generate payouts for expenses

- politeiawww/api/www/v1/api.md
- politeiawww/api/www/v1/v1.go
- politeiawww/invoices.go
Make sure all invoices include at least 1 line item.
> Add validateInvoice check for line items

- politeiawww/api/cms/v1/v1.go
- politeiawww/cmd/politeiawwwcli/commands/setinvoicestatus.go
- politeiawww/invoices.go
Adding this check will ensure that the admin is setting the status
for the most recent version of the invoice.
> Update SetInvoiceStattus signature to include invoice record version

- cms-instructions.md
Once this looks solid we can probably duplicate and have this directly on the CMS logged-in user front page.
> [cms] Initial readme for CMS user instructions

- politeiawww/api/cms/v1/v1.go
- politeiawww/api/www/v1/api.md
- politeiawww/api/www/v1/v1.go
- politeiawww/cmd/politeiawwwcli/commands/newinvoice.go
- politeiawww/invoices.go
This adds a check to ensure that the user has not already
submitted an invoice for the combined month and year.
Also includes some error code fixing in the documentation.
> [cms] Add check for only 1 invoice per month per user

- politeiawww/comments.go
> [cms] Remove event fire for invoice comments

- politeiawww/user.go
Fixes bug where username search was returning 500 when user is logged out.
> www: Fix bug processUsers username search

- politeiawww/api/cms/v1/v1.go
- politeiawww/cmswww.go
- politeiawww/invoices.go
Close #777 
Also adds min/max contact length to CMS policy response.
> [cms] Proper sanitization of user information

- politeiawww/user.go
> [cms] Set email as temporary username

- politeiawww/user/cockroachdb/cockroachdb.go
This commit prevents a data race of the cockroachdb encryption key. The
encryption key is a static value so this race is fairly benign, but it
was causing issues with the golang race detector when we zero out the
encryption key on shutdown.
> userdb: Prevent encryption key race condition

- politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
There was a ~2 month period where a bug allowed for users to be created
with duplicate usernames. This commit updates the migration command to
check for duplicate usernames and allows the username to be changed if
one is found.
> dbutil: Add duplicate username fix to migration

- politeiawww/config.go
> www: cleanAndExpand encryption key paths

- politeiad/cache/cockroachdb/decred.go
This commit adds a check to the cache's decred plugin ballot command to
ensure that duplicate votes, or any other vote that does not contain a
valid receipt signature, does not get added to the cache.
Duplicate votes were being added to the cache even when they were
rejected by gitbe. All decred plugin commands are automatically
forwarded onto the cache as long as gitbe doesn't return any errors.
Duplicate votes are unique in that gitbe doesn't return an error for
them. It returns a valid response and includes the duplicate vote error
message in the vote receipt. Since gitbe wasn't returning an error,
these duplicate votes were being incorrectly added to the cache.
> cache: Check for vote receipts

- politeiad/backend/gitbe/decred.go
Closes #882.
This commit fixes a bug in the decred plugin ballot command that would
allow duplicate votes to be recorded in the votes journal in specific
circumstances.
politeiad has a memory cache of all cast votes. When a user casts a
vote, politeiad checks the memory cache to see if the vote already
exists. If it does not exist, the vote is writen to the votes journal
then added to the memory cache. This memory cache read/write operation
was not atomic. If a user submitted the same vote request multiple
times, concurrently, it was possible for a duplicate vote to be added to
the votes journal before the memory cache was properly updated.
> gitbe: Fix duplicate votes bug

- politeiawww/api/cms/v1/api.md
- politeiawww/api/cms/v1/v1.go
- politeiawww/api/www/v1/api.md
- politeiawww/api/www/v1/v1.go
- politeiawww/cmd/politeiawwwcli/client/client.go
- politeiawww/comments.go
- politeiawww/invoices.go
- politeiawww/prices.go
- politeiawww/www.go
Close #890 
This will also require an update to pigui for the updated numbers as well.
> [cms] Move cms errors out of /api/www

- politeiad/backend/gitbe/decred.go
This commit adds validation to the decred plugin ballot command to make
sure that votes are cast using eligible tickets.
> gitbe: Ensure tickets are eligible to vote

- politeiawww/email.go
> [cms] Use previous month for invoice email

- politeiawww/cmswww.go
- politeiawww/comments.go
- politeiawww/email.go
- politeiawww/events.go
- politeiawww/invoices.go
- politeiawww/templates.go
- politeiawww/www.go
This PR adds a new Event Management system for CMS.  The first events are: notifying the user when an administrator comments on their invoice and notifying the user when their invoice's status has been updated to approved/rejected/disputed.
> [cms] Add notification for admin invoice comment

- politeiawww/prices.go
Close #879 
This PR adds a getPricesBinance function that essentially replaces the previous call to Poloniex's historical data API.
> [cms] Calculate monthly average with Binance API

- politeiawww/cmd/politeiawwwcli/commands/verifyuseremail.go
- politeiawww/cmd/politeiawwwcli/config/config.go
- politeiawww/testing.go
- politeiawww/user.go
- politeiawww/user_test.go
- politeiawww/userwww_test.go
This diff refactors the pi new user route and cleans up some code in `users.go`. The new user route was hard to reason about and needed a cleanup.
> www: Refactor new user route

- politeiawww/api/cms/v1/v1.go
- politeiawww/cmswww.go
> [cms] Add username supported chars to cms Policy

- politeiawww/api/cms/v1/api.md
- politeiawww/api/cms/v1/v1.go
- politeiawww/invoices.go
> [cms] Check that EditInvoice is same month/year

- politeiawww/api/www/v1/api.md
- politeiawww/api/www/v1/v1.go
- politeiawww/proposals.go
> [www] Include best block in vote status reply.

- politeiawww/email.go
> [cms] Remove email from invite email link

- politeiawww/politeiawww_test.go
This is the start of tests for the routes on politeiawww. The idea is to proceed testing the routes in order, one by one, until all of them are reasonably covered.
> Version route http tests for politeiawww

- politeiawww/cmsaddresswatcher.go
- politeiawww/invoices.go
This fixes a few issues that became clear when attempting to 
observe all payments for past invoices.
> [cms] Various bug fixes for payment watching

- politeiawww/api/cms/v1/v1.go
- politeiawww/cmswww.go
- politeiawww/invoices.go
This request allows administrators to search for all invoices 
based on a given userid.
> [cms] Add admin user invoices request

- politeiavoter/politeiavoter.go
- politeiawww/api/www/v1/api.md
- politeiawww/api/www/v1/v1.go
- politeiawww/cmd/politeiawwwcli/commands/login.go
- politeiawww/cmd/politeiawwwcli/commands/newuser.go
- politeiawww/cmd/politeiawwwcli/commands/register.go
- politeiawww/cmd/politeiawwwcli/commands/testrun.go
- politeiawww/user.go
- politeiawww/user_test.go
- politeiawww/userwww_test.go
This diff updates the login to use email instead of username for the reasons specified in: https://github.com/decred/politeia/issues/860#issuecomment-520871500.
> www: Update login to use email.

- go.mod
- go.sum
> Upgrade gorilla/websocket

- politeiawww/api/cms/v1/api.md
- politeiawww/api/cms/v1/v1.go
- politeiawww/cmd/cmswww/cmswww.go
- politeiawww/cmd/cmswww/invoicepayouts.go
- politeiawww/cmd/shared/client.go
- politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
- politeiawww/cmsdatabase/database.go
- politeiawww/cmswww.go
- politeiawww/convert.go
- politeiawww/invoices.go
Previously labor column was being given as minutes instead of USD.
> [cms] Fix Labor and Expenses in Line Item payouts

- go.mod
- goclean.sh
- politeiawww/politeiawww_test.go
- politeiawww/userwww_test.go
- util/paywall.go
> util: plug memleak.

- politeiawww/user/user.go
> user: Fix User json typo.

- politeiawww/api/www/v1/api.md
- politeiawww/api/www/v1/v1.go
- politeiawww/comments.go
> www: Don't allow censored comments to be voted on.

- cms-instructions.md
> Update DCC proposal link on cms-instructions

- politeiawww/api/www/v1/api.md
Removes wording for admin privilege constraint to user detail route, and updates what data is returned or omitted from response.
> Minor update in doco

- politeiawww/cmd/politeiavoter/politeiavoter.go
- politeiawww/cmd/politeiavoter/signal_unix.go
> politeiavoter: support SIGUSR1 on non-windows

- go.mod
- go.sum
- util/paywall.go
@jrick says to not rely on udb
> util: drop dcrwallet udb usage.

- politeiawww/invoices.go
Currently, we are only allowing Supervisors and Direct Contractor types to submit
invoices.
> [cms] Disallow subs from submitting invoices

- politeiawww/api/cms/v1/api.md
- politeiawww/api/cms/v1/v1.go
The doc looks different from the specs on v1.go
https://github.com/decred/politeia/blob/cb3005e825e60a6ec9829e14527a38e62175cabe/politeiawww/api/cms/v1/v1.go#L671-L676
> [cms] Fix Support/Oppose DCC api docs

- politeiawww/cmd/cmswww/newdcc.go
This updates the newdcc command for revocations so the user
entering the information doesn't have to enter the domain or
the contractortype of the revoking user.
The domain will be pulled automatically from the user's information, 
and the contractor type will be set to Revoked.
> [cms] Update newdcc command for revocations

- politeiawww/proposals.go
This diff optimized the ActiveVote route with newer decred plugin calls
that weren't around when the ActiveVote route was initially implemented.
It was previously fetching the entire politeiad inventory and the the
vote details for every proposal in the inventory. It now uses the
TokenInventory command to determine which proposals are actively being
voted on and only fetches the data for those specific proposals.
> politeiawww: Optimize ActiveVote route.

- politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
- politeiawww/convert.go
This fixes some various problems with payout summary generation.
> [cms] Fix various issues with invoice payout request

- politeiawww/invoices.go
This PR adds the version to a newly created invoice before inserting it into the database.
closes https://github.com/decred/politeia/issues/1074
> [cms] Add version field to new invoice database record

- politeiawww/invoices.go
Only invoice owning users or admins should be able to review invoice details.
> [cms] Enforce invoice details viewing rules

- politeiawww/api/cms/v1/v1.go
- politeiawww/cmd/cmswww/manageuser.go
- politeiawww/cmd/cmswww/newdcc.go
- politeiawww/cmswww.go
This PR also removes Community from available domain types, it is now rolled into marketing.
> [cms] Add available CMS domains to policy request

- politeiawww/api/cms/v1/v1.go
- politeiawww/cmswww.go
This PR is meant to remove hard coded values from the gui regarding supported line item types.
> [cms] Add supported line item types to policy reply

- politeiad/cache/testcache/testcache.go
- politeiawww/politeiawww_test.go
This commit adds tests for `/v1/proposals/vetted` route.
> tests: all vetted proposals route

- README.md
- cms-instructions.md
- go.mod
- politeiawww/api/cms/v1/v1.go
- politeiawww/convert.go
> [cms] Add DCC's submission & approval/rejection timestamps

- politeiawww/invoices.go
> [cms] Rejected invoice is permanently rejected

- politeiawww/plugin.go
> politeiawww: Rety politeiad plugin inventory call.

- politeiawww/api/cms/v1/api.md
- politeiawww/api/cms/v1/v1.go
- politeiawww/invoices.go
Needed for https://github.com/decred/politeiagui/issues/1202 & https://github.com/decred/politeiagui/pull/1803
> [cms] Make contractor location field optional

- politeiawww/cmswww.go
- politeiawww/dcc.go
- politeiawww/email.go
- politeiawww/events.go
- politeiawww/templates.go
This PR adds 2 new events for DCC for all current admins:
1) any new DCC
2) any new Support/Oppose to a DCC.
> [cms] Add DCC event notifications

- politeiad/backend/gitbe/decred.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/backend/gitbe/gitbe_test.go
- politeiad/config.go
- politeiad/politeiad.go
- politeiad/sample-politeiad.conf
- politeiawww/cmd/cmswww_payment/cmswww_payment.go
- politeiawww/cmsaddresswatcher.go
- politeiawww/config.go
- politeiawww/paywall.go
- politeiawww/sample-politeiawww.conf
- politeiawww/user.go
- politeiawww/wsdcrdata.go
- politeiawww/www.go
- util/paywall.go
Closes #461 
This PR adds the ability to update the dcrdata host used in politeiad and politeiawww through the config files.
> [multi] Add custom config for dcrdata host

- politeiawww/convert.go
- politeiawww/invoices.go
> [cms] Set username on invoice status change

- politeiawww/cmd/politeiavoter/politeiavoter.go
A bug in dcrdata has caused a best block height of 0 to be returned
intermittently. This diff adds a retry loop to the best block call to
ensure that a valid best block is returned.
> politeiavoter: Add best block retry loop.

- README.md
Doc update regarding the merged #1151 PR.
> Minor doc update

- politeiawww/api/www/v2/v2.go
- politeiawww/proposals.go
The json tag was missing an "s", causing the gui to error.
> politeiawww: Fix json typo.

- go.mod
- politeiawww/api/www/v1/api.md
- politeiawww/api/www/v1/v1.go
- politeiawww/politeiawww.go
This PR adds the `paywallenabled` field to the response of the policy request.
> Add paywallenabled to policy

- politeiawww/cmd/cmswww/cmswww.go
- politeiawww/cmd/piwww/piwww.go
- politeiawww/cmd/shared/shared.go
- politeiawww/dcc.go
- politeiawww/invoices.go
- politeiawww/proposals.go
- politeiawww/util/merkle.go
> www: Fix for detecting changes on edit proposal

- politeiad/backend/gitbe/gitbe.go
This diff prevents the git fsck command from being run during every
hourly anchoring. It is instead run once per day during the 06:58 UTC
anchoring. This time was chosen because it occurs in the middle of the
night for the USA and Brazil, which is likely the majority of politeia
traffic.
> gitbe: Limit git fsck during anchoring.

- politeiawww/cmsnotifications.go
This fixes contractors that are subs or other types from still receiving notifications to submit an invoice for this month.
> [cms] Only notifiy for invs direct and supervisor

- politeiawww/comments.go
- politeiawww/proposals.go
- politeiawww/www.go
This diff removes the comment vote cache initialization that happened with www startup. They are now lazy loaded into the cache when needed.
Closes #1215
> www: Lazy load comment votes

- politeiawww/user_test.go
This diff adds tests for `processUpdateUserKey` and
`processVerifyUpdateUserKey` functions on politeiawww/user.go
> www: Tests for user keys

- politeiawww/cmd/piwww/newproposal.go
This diff cleans up the `piwww newproposal` command and fixes some
behavior that was deviating from the documentation.
> piwww: Update newproposal command.

- politeiad/backend/gitbe/gitbe.go
This adds a proper handler for the CMS plugin inventory call.
> [cms] Add CMSPlugin inventory handler

- politeiawww/cmd/piwww/startvote.go
- politeiawww/cmd/piwww/startvoterunoff.go
This diff fixes the description for v2 vote options
> piwww: fix descriptions for v2 vote options

- politeiawww/api/cms/v1/v1.go
- politeiawww/invoices.go
This diff adds a new contractor type for those contractors that have been approved by proposal, but not a DCC.
This also adds a new rule that contractors not approved by DCC cannot see domain invoices.
> [cms] Add new contractor type

- politeiawww/invoices.go
As discussed on matrix, we should limit the amount of invoices that people are able to see if sharing domain.
> [cms] Add 6 month limit on domain invoice viewing

- politeiawww/api/cms/v1/v1.go
- politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
- politeiawww/cmsdatabase/cockroachdb/encoding.go
- politeiawww/cmsdatabase/database.go
- politeiawww/convert.go
- politeiawww/invoices.go
This adds a Total field to InvoiceRecord to ease any downstream computations that may be needed.
> [cms] Add Total to InvoiceRecord

- politeiawww/api/cms/v1/api.md
This PR adds documentation for the `proposals/billing` endpoint and remove some trailing spaces from the file.
> docs: add docs for proposals/billing

- politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
> fix: remove invoices alias on spendingsummary query

- go.sum
- politeiad/api/v1/v1.go
- politeiad/backend/backend.go
- politeiad/backend/gitbe/gitbe.go
- politeiad/politeiad.go
- politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
- politeiawww/convert.go
- politeiawww/www.go
Due to limitations on memory usage I've added a basic page/count paginator on the record inventory call. 
There is also a fix included for DCC mdstream decoding from records.
> politeiad: add pagination to record inventory

- politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
- politeiawww/cmsdatabase/cockroachdb/encoding.go
- politeiawww/convert.go
> [cms] Populate SubUserID in lineitem db request

- .gitignore
- politeiawww/cmd/politeiavoter/politeiavoter.go
- politeiawww/cmd/politeiavoter/retry.go
- politeiawww/cmd/politeiavoter/signal.go
- politeiawww/cmd/politeiavoter/signal_unix.go
- politeiawww/cmd/politeiavoter/stats_unix.go
- politeiawww/cmd/politeiavoter/stats_windows.go
always handle interrupt; also handle sigterm on !windows
> politeiavoter: fix signal handling.

- politeiawww/cmd/politeiavoter/README.md
- politeiawww/cmd/politeiavoter/config.go
- politeiawww/cmd/politeiavoter/politeiavoter.go
- politeiawww/cmd/politeiavoter/sampleconfig/sampleconfig.go
Add `verify` vote(s) option to pivoter. This examines the json logs and verifies vote integrity and consistency.
> [WIP] Add verify vote option

- politeiad/backendv2/tstorebe/plugins/comments/cmds.go
- politeiad/backendv2/tstorebe/tstore/verify.go
- politeiawww/client/comments.go
- politeiawww/client/records.go
- politeiawww/client/ticketvote.go
- politeiawww/cmd/pictl/cmdcommentcensor.go
- politeiawww/cmd/pictl/cmdcommentnew.go
- politeiawww/cmd/pictl/cmdcommenttimestamps.go
- politeiawww/cmd/pictl/cmdvotetimestamps.go
- politeiawww/cmd/politeiaverify/README.md
- politeiawww/cmd/politeiaverify/comments.go
- politeiawww/cmd/politeiaverify/politeiaverify.go
- politeiawww/cmd/politeiaverify/record.go
- politeiawww/cmd/politeiaverify/ticketvote.go
- politeiawww/comments/process.go
This diff makes a few improves to the `politeiaverify` tool:
- Improves the record bundle and record timestamps validation
- Adds comment bundle and comment timestamps validation
- Adds ticketvote bundle and ticketvote timetamps validation
> politeiaverify: Verify comment and vote bundles.

- politeiawww/cmd/politeiavoter/trickle_test.go
The tests were previously saving the journal to the local dir every time
they were run.
> politeiavoter: Add temp dir to tests.

- politeiawww/proposals.go
The active votes route was not paginating its requests to politeiad
which was causing the route to 500 when there were more active votes
than the politeiad records page size. This diff updates the active votes
route to paginate its politeiad requests.
> politeiawww: Fix legacy active votes bug.

- politeiawww/cmd/politeiavoter/politeiavoter.go
The config provided wallet password was being ignored.
> politeiavoter: Fix password bug.

- politeiad/client/comments.go
- politeiawww/proposals.go
Closes #1407.
```
$ piwww batchproposals 41225ecf6bae2d22                                                                 
{
"proposals": [
{
"name": "tasssssss",
"state": 2,
"status": 4,
"timestamp": 1620082967,
"userid": "0e3dde1e-ec22-409c-ad08-da8281aacb69",
"username": "admin",
"publickey": "af145a34c6aaaecd481157a3cb4e99205dad02c3f1ad71959f76026009d02ac0",
"signature": "edf5e5d4e6f0654fea0c14e1c647520aee6de5d240e208f0dc59fee0835121c7f2b0f2f3d985f47f52ec5e3d5d3f5e5a44ab7174c071c9ebb0caa16fdf853301",
"numcomments": 1,
"version": "1",
"publishedat": 1620082967,
"files": [],
"metadata": [
{
"digest": "df4c0ea0c4b28511e3b4d4f382f9a3d3266505f0271a3ebbcac49809613b1249",
"hint": "proposalmetadata",
"payload": "eyJuYW1lIjoidGFzc3Nzc3NzIn0="
}
],
"censorshiprecord": {
"token": …
```
> www: Missing proposal comment field.

- politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
- politeiawww/cmswww.go
Close #1329 
For proposal billing, previously only PAID invoices were included in the line item tabulation for various summaries and details of proposal billing.  This updates to include new, updated, approved and paid invoices in these requests.
> [cms] Update LineItem db function to fetch more invoice status

- politeiawww/pi/mail.go
> Emails: Add record's token to email subjects.

- politeiawww/comments/error.go
- politeiawww/middleware.go
- politeiawww/records/error.go
- politeiawww/ticketvote/error.go
- politeiawww/www.go
This diff adds in error handling for when the client drops the
connection.
> politeiawww: Handle client conn drops.

- politeiawww/api/cms/v1/v1.go
- politeiawww/cmswww.go
This should be able to handle the current issue with hosting of archived and new proposals on different sites.
> Add archive site to pass though requests

- politeiawww/user.go
- politeiawww/user_test.go
This diff adds unit tests for `processManageUser` and `processUsers` methods
on `politeiawww/user.go`
> www: Unit tests for user management and user fetching

- politeiawww/pi/mail.go
> Emails: Use proposal name in email subjects.

- .github/workflows/go.yml
- goclean.sh
- politeiawww/user/mysql/mysql.go
> build: test against golangci-lint v1.41.1

- politeiad/README.md
This diff adds instructions to the politeiad README on clearing out the
politeiad databases in order to create a fresh development enviroment.
> politeiad: Add reset docs.

- politeiawww/userwww.go
- politeiawww/www.go
This diff adds the login route to the auth router so that it is CSRF
protected.
> politeiawww: Add login to auth router.

- politeiawww/userwww.go
- politeiawww/www.go
This diff adds the login route to the auth router so that it is CSRF
protected.
> backport: politeiawww: Add login to auth router.

- politeiawww/README.md
Just a little styling in the documentation 😁
> docs: Add code block to politeiawww readme commands.

- .github/workflows/go.yml
- politeiad/backendv2/tstorebe/plugins/ticketvote/activevotes.go
- politeiawww/cmd/pictl/subscribe.go
- politeiawww/cmd/politeiavoter/help.go
- politeiawww/cmd/politeiavoter/signal_unix.go
- politeiawww/cmd/politeiavoter/stats_unix.go
- politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
This diff fixes the error caused by an incorrect golangci-lint version.
While fixing the linter, new lint errors were thrown and also fixed by
this commit.
> chore: github actions and lint adjustments.

- politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
- politeiawww/cmd/politeiawww_dbutil/time.go
- politeiawww/legacy/user/user.go
This improves the user identity logging in the dbutil `verifyidentities`
command. It makes some small tweaks to the user identity methods and
documentation in order to facilitate this improved logging.
> multi: Improve identity logging.

- politeiawww/cmd/politeiavoter/config.go
- politeiawww/cmd/politeiavoter/politeiavoter.go
This modifies the initial configuration error handling logic to mirror more recent logic from `dcrd` to avoid a bunch of duplicate code and fix some cases that were not logging the errors as expected.
It accomplishes this by consolidating the error reporting in a single place in the caller and introducing a custom error type which signals that the usage message should be suppressed in order to retain the primary behavior the originally was the reason for the prints being in the config function to begin with.
The application name is passed into the function now since it is needed in both places.
Finally, this also corrects a couple of other issues such as the log rotator not being properly closed and a panic when trying to get help without specifying a command.
> pivoter: Cosolidate config error reporting.

- politeiawww/sessions/mysql/mysql_test.go
This commit adds test coverage to the sessions MySQL database.
> sessions: Add tests

- politeiad/backendv2/tstorebe/tstore/anchor.go
- politeiad/backendv2/tstorebe/tstore/freeze.go
- politeiad/backendv2/tstorebe/tstore/tstore.go
- politeiad/backendv2/tstorebe/tstorebe.go
This commit cleans up some logging and documentation.
> politeiad: Logging tweaks.

- politeiawww/cmd/politeiavoter/politeiavoter.go
- politeiawww/cmd/politeiavoter/trickle.go
- politeiawww/cmd/politeiavoter/trickle_test.go
This consolidates the logic that creates the signed votes to cast by creating them without the signature first and then obtaining the signatures from the wallet and setting those signature into the existing unsigned votes.
This approach is simpler and less error prone than the current one that passes separate arrays of eligible tickets, signatures, and associated vote details around.
> pivoter: Consolidate cast vote creation.

- .golangci.yml
- goclean.sh
- politeiawww/legacy/piuser.go
> golanglint-ci: Add golanglint-ci.yml.
