decred/politeia

politeiawww/backend.go, politeiawww/backend_proposal_test.go, politeiawww/cmd/politeiawww_refclient/politeiawww_refclient.go, politeiawww/www.go
This PR changes `/proposals/{token}` to only return full proposal data to admin users. For all other users, it only returns the metadata (censorship data, status, etc). This allows users to see (and show to others) the status of their submitted proposals and know if/when it gets censored.
Fixes #95.
=> [www] Fix bug where users can see unvetted proposals

politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/cmd/politeiawww_refclient/politeiawww_refclient.go
As discussed: covers the api doc, api route and client.
PR GUI: decred/politeiagui#93
=> routes: modified 'setstatus' to 'status #76

politeiad/backend/gitbe/git.go, politeiad/backend/gitbe/gitbe.go
This PR adds default config of `core.autocrlf=false` to the vetted and unvetted repos in Politeiad, which prevents Git from converting CRLF character to LF while committing and checking out files.
Having `core.autocrlf` set to anything else can cause issues in Windows if, for example, a proposal is committed with the following text:
This is a description\n
\n
with newline characters.
The same file can get checked out as:
This is a description\r\n
\r\n
with newline characters.
which will result in merkle verification failure when trying to open the proposal details.
Fixes #99.
=> [politeiad] Fix vetted/unvetted repo creation for Windows

politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/backend_proposal_test.go, politeiawww/cmd/politeiawww_refclient/politeiawww_refclient.go
Summary of changes:
* Add paging capability to `/vetted` and `/unvetted` routes
* Add `v1.ProposalListPageSize`
* Add a unit test for paging
* Update reference client to create and fetch 2 pages of proposals
* Update API docs
* Add some missing info for API docs
Fixes #43.
=> [www] Add paging capability to proposal list routes

politeiad/backend/gitbe/git.go, politeiad/backend/gitbe/gitbe.go, politeiad/backend/gitbe/gitbe_test.go
fixes #166 
- git checkout was not returning an error after deleted the unvetted branch (when passing from unvetted to vetted)
=> [politeiad] Fixing vetted proposals being brought on getUnvetted

politeiawww/backend.go, politeiawww/backend_user_test.go, politeiawww/database/localdb/localdb.go
Fixes #188.
This breaks the tests by adding ToUpper and then uses ToLower in the right spots to fix the issue.
=> force lowercase when creating and getting a user

politeiad/backend/gitbe/gitbe.go
There is one remaining corner case where an Anchor confirmation comes
BEFORE some commits that have not been anchored.  This needs to be fixed
but for now work around this issue.
=> [politeiad] Ignore non-empty reconcile maps

politeiawww/www.go
This PR ensures that an invalid input user error is returned for all routes when the input JSON cannot be unmarshalled.
Fixes #148.
=> [www] Fix routes to return invalid input user errors

Gopkg.lock, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/cmd/politeiawww_refclient/client.go, politeiawww/www.go, util/json.go
The GET handlers are trying to unmarshal the request body
as JSON into a struct, but a payload within a GET request
is not actually defined by the latest HTTP/1.1 spec. This
commit changes the behavior to instead pull values from
the query and store them in the command struct.
=> [www] Fix bugs with GET handlers

README.md
related to issue #199
Add on top of recent improvement by @fernandoabolafio. I notice the "dep ensure" and "go install" references are removed. Is it done on purpose? This may create difficulties for GO new comer. I can add it back here if the reviewer agrees.
=> add SMTP section in README.md

politeiad/backend/gitbe/anchors.go
Politeiad is not crashing on master anymore. But `fsck` still verifying for "Anchor confirmation", that's why we get this log on politeaid start: `Error verifying anchor during fsck: not a valid digest: confirmation`
This PR fixes that.
closes #237
=> [Politeaid] Fix politead crash after running politeiawww_refclient

politeiawww/backend.go, politeiawww/middleware.go, politeiawww/www.go
After observing some file handle leaks I noticed that handlers were leaking file handles. Move r.Body.Close() to middleware so that it can be hooked and therefore we can ascertain it is always run.
=> Move body.Close to middleware

politeiawww/cmd/politeiawww_refclient/client.go, politeiawww/cmd/politeiawww_refclient/main.go
After commit de601294199c4b3d034dba68a1aa7843fc0b5a81 we are not returning status 403 when user not logged in anymore.
This PR fix the refclient to accept this change.
=> fix refclient after not returning forbidden when not logged in

README.md, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawww_refclient/client.go, politeiawww/cmd/politeiawww_refclient/main.go, politeiawww/config.go, politeiawww/paywall.go, politeiawww/www.go, util/paywall.go
This PR closes #217 
I added a flag `-use-paywall` to the politeiawww_refclient. In case we do not want to wait for the paywall payment confirmation, we just need to set it to false, but because of that, is not possible to test new proposals and comments. I let default as true.
I also added a flag `--minConfirmations` to politeiawww, so we can change the minimum amount of blocks needed when in testnet. I setted mainnet as 2 blocks and it is not configurable. Should I left like that?
~~Tests are failing because of paywall enformecement, should I add 0 confirmations block in case of tests?~~
Right now we have two URLs for confirming payments
```
primaryURL = "https://testnet.dcrdata.org/api/address/" + address + "/raw"
backupURL = "https://testnet.decred.org/api/addr/" + address + …
```
=> [www] Add paywall enforcement

politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/backend_proposal_test.go, politeiawww/backend_user_test.go, politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go, politeiawww/cmd/politeiawww_refclient/main.go, politeiawww/database/database.go, politeiawww/database/localdb/localdb.go, politeiawww/inventory.go, politeiawww/www.go, util/proposal.go
This PR adds support for usernames, which are unique (case-insensitive). It adds a parameter to the `/user/new` route for supplying a username (required), and a `/user/username/change` route which allows an already-logged-in user to change his existing username by supplying his current password.
Unrelated to the usernames feature, this PR also adds a `-clearpaywall <email>` flag to `politeiawww_dbutil`.
=> [www] Add username implementation

politeiawww/middleware.go
This PR is a complement of a missing detail on #283
=> [www] Return 401 when user session is not found on middleware “isLoggedIn”

politeiawww/cmd/politeiawwwcli/README.md, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/changepassword.go, politeiawww/cmd/politeiawwwcli/commands/changeusername.go, politeiawww/cmd/politeiawwwcli/commands/newuser.go, politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go
This PR adds the username parameter to the `newuser` command as well as a new command `changeusername`.
=> [wwwcli] Add username functionality

politeiawww/cmd/politeiawwwcli/README.md, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go, politeiawww/cmd/politeiawwwcli/commands/version.go, politeiawww/cmd/politeiawwwcli/config/config.go, politeiawww/cmd/politeiawwwcli/main.go
Fixes #293.
The `version` command sends a GET request to `/version` and receives a response containing the server's version, route info, signing identity, and a CSRF token.  The CSRF cookie and header token are automatically stored for future use.
=> [wwwcli] Add version command and persist CSRF token

.gitignore, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/verifyuserpayment.go, politeiawww/cmd/politeiawwwtest/main.go
Fixes #280
Replaces `politeiawww_refclient` with `politeaiwwwtest` to run the politeiawww api tests. 
```
Usage:
politeiawwwtest [OPTIONS]
Application Options:
-h, --host=          Host (https://127.0.0.1:4443)
-o, --overridetoken= Override token for faucet
-j, --json           Print JSON
-s, --skip-paywall   Don't wait for paywall confirmations during test run
-v, --vote           Run vote routes
Admin Options:
-e, --email=         admin email
-p, --password=      admin password
Help Options:
-h, --help           Show this help message
```
Run the basic api routes:
`$ politeiawwwtest`
Run the basic api routes and the admin routes:
`$ politeiawwwtest -e admin@example.com -p somepassword`
Run the vote routes:
`$ politeiawwwtest -v -e admin@example.com -p somepassword`
=> replace politeiawww_refclient with politeiawwwtest

politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go, politeiawww/cmd/politeiawwwcli/commands/usernamesbyid.go, politeiawww/www.go
Because www does not send usernames with comments for a proposal details request, this PR adds a route which allows the client to fetch usernames given their user ids.
=> [www] Add usernames-by-id route.

politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/convert.go
closes #270
I've added the vote Details info within vote Results returned data. With that, is possible to tell a proposal status (on-voting, finshed, not-started-voting) by simply calling the vote Results for a given proposal token.
=> [www] Merge voting details to proposal vote results

politeiawww/backend.go, politeiawww/cmd/politeiawww_dataload/README.md, politeiawww/cmd/politeiawww_dataload/config.go, politeiawww/cmd/politeiawww_dataload/main.go, politeiawww/cmd/politeiawww_dataload/sample-politeiawww_dataload.conf, politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/database/database.go
This PR adds a `politeiawww_dataload` command to automatically load data to help quickly test Politeia. Running `politeiawww_dataload` will automatically start/stop `politeiad` and `politeiawww`, and utilize `politeiawww_dbutil` and `politeiawwwcli` to create an admin and regular users, proposals in each state (public, censored, etc), and a couple comments.
=> Add a command for loading basic data.

politeiawww/cmd/politeiawww_refclient.sh, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/faucet.go, politeiawww/cmd/politeiawwwcli/commands/newuser.go, politeiawww/cmd/politeiawwwcli/commands/policy.go, politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go, politeiawww/cmd/politeiawwwcli/commands/resetpassword.go, politeiawww/cmd/politeiawwwcli/commands/verifyuser.go, politeiawww/cmd/politeiawwwtest/main.go
Closes #308 
This PR converts politeiawww_refclient into a bash script that uses politeiawwwcli to interact with the politeiawww api and jq to validate the output.
A 'policy' command and a 'faucet' command were needed in the script, so this PR also includes the addition of those commands to politeiawwwcli.
```
Usage:
politeaiwww_refclient.sh [options] [ -e admin_email ] [ -p admin_password ]
Options:
-e    specify an admin email
-h    show this help message
-j    print json output
-o    override token for faucet
-p    specify an admin paassword
-s    specify server (i.e. host)
-v    run vote routes
* to run admin routes, specify admin login credentials using -e and -p
```
=> politeiawww_refclient script

politeiawww/cmd/politeiawwwcli/README.md, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/client/util.go, politeiawww/cmd/politeiawwwcli/commands/activevotes.go, politeiawww/cmd/politeiawwwcli/commands/castvotes.go, politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go, politeiawww/cmd/politeiawwwcli/commands/proposalvotes.go, politeiawww/cmd/politeiawwwcli/config/config.go
Closes #315 
Closes #291 
This PR adds the activevotes, castvotes, and proposalvotes comands to politeiawwwcli.  It defaults to using a testnet wallet on localhost to sign votes for right now.  I'll add in the ability to change this using a config file and cli flags in a future PR.
This PR also fixes a bug with the --host flag.  You can now interact with multiple politeiawww hosts without any issues.
=> [wwwcli] Add activevotes, castvotes, and proposalvotes commands

politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go, politeiawww/cmd/politeiawww_refclient/client.go, politeiawww/cmd/politeiawww_refclient/main.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/verifyuserpayment.go, politeiawww/cmd/politeiawwwtest/main.go, politeiawww/database/database.go, politeiawww/paywall.go, politeiawww/www.go, util/paywall.go, util/paywall_test.go
This PR changes the paywall logic to continuously watch the paywall addresses for unpaid users. The full behavior is:
* When a user verifies his registration, his paywall info is automatically added to the verification pool.
* The verification pool iterates the unpaid users, checking dcrdata and/or insight for a transaction that meets the paywall requirements.
* When a user is verified as paid by the pool, it removes his paywall info from the pool and updates the database.
* When the server first starts, it iterates all users in the database and adds unpaid users to the pool.
* The pool will stop watching any users whose paywall info was generated more than 24 hours ago. The user's paywall info will only be re-added to the pool via a call to `/me` or `/login` or `/user/verifypayment` (and …
=> [www] Change paywall logic to continuously poll.

politeiad/backend/gitbe/git.go, politeiad/backend/gitbe/gitbe.go
Git requires user.name and user.email to be set.
git config requires a -c before each key/value pair.
=> politeiad: fix initial run

politeiawww/cmd/politeiawwwcli/README.md, politeiawww/cmd/politeiawwwcli/commands/login.go, politeiawww/cmd/politeiawwwcli/commands/newuser.go, politeiawww/cmd/politeiawwwcli/commands/version.go
Closes #397.
You typically have to run the `version` command in order to fetch CSRF tokens from politeiawww.  This has been a common source of confusion.  This PR makes politeiawwwcli a bit easier to use by automatically fetching CSRF tokens in the `login` and `newuser` commands.
It also updates the politeiawwwcli README
=> [wwwcli] Add CSRF call to the login and newuser commands

politeiad/cmd/politeia/politeia.go
Creating a record with "politeia new" would always fail with a verification error.
This fixes it.
=> Fix record verification in politeia command

politeiawww/api/v1/v1.go, politeiawww/cmd/politeiawwwcli/README.md, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go, politeiawww/cmd/politeiawwwcli/commands/proposalpaywall.go, politeiawww/cmd/politeiawwwtest/main.go, politeiawww/database/database.go
Closes #405 
politeiawwwtest hadn't been updated in a little while.  In addition to the two items listed above, this PR cleans up politeiawwwtest and gets it working again.
=> add proposalpaywall cmd to wwwcli and update wwwtest

politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/client/util.go
Closes #421 
This PR updates `politeiawwwcli` to convert passwords to SHA3-256 digests before sending them to the server.
=> [wwwcli] Hash passwords before sending to server

politeiawww/backend.go, politeiawww/inventory.go, politeiawww/inventory_test.go
closes #396
This PR make changes to the www inventory, in order to always load the metadata of the records when changes are applied to it.  It also adds a few test cases to ensure the inventory is working properly.
=> [WWW] Add Inventory test cases and fix loading proposal metadata

Gopkg.lock, politeiad/api/v1/api.md, politeiad/api/v1/v1.go, politeiad/backend/backend.go, politeiad/backend/gitbe/decred.go, politeiad/backend/gitbe/git.go, politeiad/backend/gitbe/gitbe.go, politeiad/backend/gitbe/gitbe_test.go, politeiad/cmd/politeia/politeia.go, politeiad/politeiad.go, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/editproposal.go, politeiawww/cmd/politeiawwwcli/commands/politeiawwwcli.go, politeiawww/convert.go, politeiawww/inventory.go, politeiawww/middleware.go, politeiawww/user.go, politeiawww/www.go, util/dcrtime_test.go
In reality what this means is that we are creating a version directory for the latest proposal. When a proposal is updated it creates a new version directory with all content in it. This seems to be the least painful way to implement versioning without having to keep track of all kinds of additional files etc. Also from a code perspective this is the least LOC change possible since most of the code remains intact, only file paths change from a git perspective.
=> Add capability to "edit" proposals

politeiawww/cmd/politeiawwwcli/commands/editproposal.go, politeiawww/cmd/politeiawwwcli/commands/newproposal.go
politeiawwwcli currently uses hardcoded proposal text when the `--random` flag is used with the `newproposal` and `editproposal` commands.  This PR fixes this by adding 10 lines of randomly generated text to the proposal.   An example proposal is shown below.
```
This is the proposal title
CUJV7uVxJGxuNAY0nfyXoEgv8VF014dqIeVDXOIhDow=
MYfrM2VKOuXeuh+7QMGDQ/1BNH37YnMPkqbIriYQDbI=
FxevhuN3kZzgXSm+o6c5G9rq4YMzlMUphFZyVbuIukk=
ZnZH5dN+QTQxyYrVKBbh62O1aDz5xDcqHCZ6K67y7Oo=
MiYYVGuDRjfwn4lzsBm31eCKSN70mGgc6n97DFYUvC8=
WNqp8JQEBhPJu1PGVKGFPniJwychmE4bVRcCpWiXO08=
cBYVAY9i1xMlLbn9dBbvmdD2Va4salG3CiW3DeDr/2I=
4yRuDqvknXhk+6esB0XZeSg/Y6PTteAJgTzfKciyYqM=
B/0dgDam3D4rhOzM3RY99kNi8rOtJNenlrab2wbUeSU=
ZaKdZTJTVn9yeLjbVgvO48SWV/ewEr+eUuMh2N9xY0c=
```
=> [wwwcli] Generate random proposal text when --random is used

politeiawww/api/v1/v1.go, politeiawww/backend.go
This PR improves the enforcement rules for creating comments and liking comments. The enforcement update is:
- Only public proposals can be commented or receive "like" for its comments
- Proposals which voting has already ended cannot receive comments or "like" for its comments
=> [WWW] Update “comment” and “like comment” enforcement rules

politeiawww/www.go
Set default path for CSRF cookies to `/` in order to avoid multiple tokens stored in the cookie
closes https://github.com/decred/politeiagui/issues/540
=> [www] Set default path for CSRF cookies

politeiawww/api/v1/v1.go, politeiawww/backend.go
Closes #324.
This PR ensures that usernames are properly formatted.  When a new user is created or a username is updated, the white space is trimmed and the username is converted to lowercase.  The validateUsername regex check was also updated to enforce the no white space and no upper case letters rules.
=> [www] Format usernames and enforce no white space or uppercase letters.

politeiawww/cmd/politeiawwwcli/commands/setproposalstatus.go
This PR changes the status change message for the `politeiawwwcli setproposalstatus` command from a command line flag to an optional argument.
```
$ politeiawwwcli setproposalstatus 3d9f611fb8e8ec9a5577079f98be7f4206a35f34371c10b8f68dbba745a238a4 3 "censor message"
```
=> [wwwcli] Change setproposalstatus message to optional argument.

politeiad/backend/gitbe/decred.go, politeiawww/backend.go
This adds in logic so that a comment cannot be censored multiple times.  
The original implementation of censor comment would delete the comment from the cache so these checks were not necessary.  When we updated the implementation to keep the comment in the cache, I failed to add these additional checks in.
With this pr, if an admin tries to censor a comment that has already been censored, they will no get a 400 response with the user error "cannot censor comment".
=> Don't allow a comment to be censored multiple times.

politeiawww/cmd/politeiawwwcli/README.md, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/client/util.go, politeiawww/cmd/politeiawwwcli/client/wallet.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/inventory.go, politeiawww/cmd/politeiawwwcli/commands/tally.go, politeiawww/cmd/politeiawwwcli/commands/util.go, politeiawww/cmd/politeiawwwcli/commands/vote.go, politeiawww/cmd/politeiawwwcli/config/config.go
This adds the politeiavoter inventory, vote, and tally commands to politeiawwwcli.  For right now, they only work on testnet and you have to be running dcrwallet locally using the default port.  Additional cli options will be added in the future that allow you to use these commands anywhere.
```
$ politeiawwwcli inventory
Token: ee42e2e231c02b3d202de9f5df7b2d361a5ab078f675a8823e3db73afb799899
Proposal        : This is the proposal title
Eligible tickets: 3
Start block     : 30938
End block       : 32954
Mask            : 3
Vote Option:
ID                   : no
Description          : Don't approve proposal
Bits                 : 1
To choose this option: politeiawwwcli vote ee42e2e231c02b3d202de9f5df7b2d361a5ab078f675a8823e3db73afb799899 no
Vote Option:
ID                   : yes …
```
=> [wwwcli] Add inventory, vote, and tally commands.

politeiawww/backend.go, politeiawww/backend_proposal_test.go
When the www inventory cache is loaded on startup, www requests the proposal inventory from politeiad without the files included.
When a new proposal is created, it creates a new inventory record with the files included.  This creates inconsistencies in the inventory cache.  Some inventory records include proposal files and some don't. 
This PR updates the new proposal endpoint to not store the proposal's files in the inventory cache.
=> [www] Don't add files to inventory cache on new proposal.

politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/login.go, politeiawww/cmd/politeiawwwcli/commands/newuser.go, politeiawww/cmd/politeiawwwcli/commands/updateuserkey.go, politeiawww/cmd/politeiawwwcli/commands/util.go
Up until this point,`politeiawwwcli` has been using the email address to generate a new identity in order to make the tool easier to use.  This allowed you to login and logout with different users and have the identity that was saved to disk be automatically updated since `politeiawwwcli` could generate the identity using the user's email address.  This was fine for development, but not that we're getting closer to launching Politeia, this needed to be updated.
This PR does a couple of things:
- Identities are now created using random data instead of the user's email address.
- Updates the `newuser` command to automatically save the identity to disk.  You can use the `--nosave` flag if you don't want the user's identity to be saved.
- Adds the `UpdateUserKey` command.  The new identity is …
=> [wwwcli] Generate random user identities.

politeiawww/cmd/politeiawwwcli/README.md, politeiawww/cmd/politeiawwwcli/commands/edituser.go, politeiawww/cmd/politeiawwwcli/commands/setproposalstatus.go, politeiawww/cmd/politeiawwwcli/config/config.go
Fixes part of #449
This PR converts the status argument in `setproposalstatus` and the action argument in `edituser` from status codes to human readable text. 
**old implementation**
```
$ politeiawwwcli setproposalstatus a75e59a5b651448ea51139f59a97d3dd 3 "censor message"
$ politeiawwwcli edituser 1 4 "some reason"
```
**new implementation**
```
$ politeiawwwcli setproposalstatus a75e59a5b651448ea51139f59a97d3dd censored "censor message"
$ politeiawwwcli edituser 1 clearpaywall "some reason"
```
=> [wwwcli] Make status code arguments human readable.

politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/convert.go
Closes #478 
This PR does two things:
- Changes the www user error `ErrorStatusInvalidProposalName` to `ErrorStatusInvalidFilename`
- Updates www so that `ErrorStatusInvalidFilename` is returned on an invalid filename instead of a 500 error code
I changed the error name was to make it consistent with the politeiad filename error and so that it can be used for both proposal and attachment filename validation errors.  `ErrorStatusInvalidProposalName` was never actually being used, so it was an easy change.
=> [www] Return user error on invalid filename.

politeiawww/backend.go, politeiawww/convert.go, politeiawww/inventory.go, politeiawww/www.go
This diff adds a missing return to a failure path and locks around the pubkey to userid converter.
Closes #477
=> [www] Shuffle code around to make locking more obvious.

Gopkg.lock, politeiawww/admin.go, politeiawww/admin_test.go, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go, politeiawww/database/database.go, politeiawww/database/localdb/localdb.go, politeiawww/paywall.go, politeiawww/user.go, politeiawww/www.go
Sets a random generated 128-bit uuid for every new user. Significant changes:
- strconv lib is no longer used to deal with userid; uuid lib has methods for parsing uuid->string and string->uuid
- userid was used as index to generate paywall addresses; now, the db keeps a lastpaywallindex that increments sequentially, and is only used as index to new addresses.
Tested with gui integration and everything worked fine! Please let me know if there is some change needed.
=> [www] Implements uuid as unique user identifier

politeiavoter/politeiavoter.go
Because of the bias, the buckets aren't always below the allotted time. Complain to the user if we can't find a solution and recommend increasing the --voteduration.
=> [voter] Make sure there is an escape if we don't find an acceptable duration

politeiad/backend/gitbe/decred.go
dcrdata.org is redirected to the wrong spot when using JSON command.
=> [plugin] Fix dcrdata mainnet url

politeiad/backend/gitbe/decred.go
We were not accounting for maturity when setting the vote duration. This fixes that.
=> [politeiad] Add maturity to endheight

politeiawww/paywall.go
This diff reduces the sleep time in between paywall polling requests from 5 seconds to 1 second.
=> [www] Update paywall polling sleep time.

politeiawww/admin.go, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/users.go, politeiawww/www.go
This commit adds a new admin-only route for fetching a list of users.
It supports filtering by email and/or username, and only returns the
first 20 results. It also returns the total number of all users in the
database.
Closes #505.
=> [www] Add admin route for users list.

politeiawww/admin.go, politeiawww/api/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/rescanuserpayments.go, politeiawww/paywall.go, politeiawww/www.go, util/paywall.go
Closes #500 
This diff adds the endpoint `/user/payments/rescan` which allows an admin to rescan a user's paywall address to check for any payments that may have been missed by paywall polling.  If a payment is found that doesn't correspond to existing proposal credits, then new credits are created and added to the user's account.
=> [www] Add user payments rescan endpoint.

politeiawww/admin.go, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawwwcli/commands/edituser.go, politeiawww/database/database.go, politeiawww/middleware.go, politeiawww/user.go, politeiawww/www.go
This PR adds the ability for admins to deactivate and re-activate users. Deactivating a user prevents them from logging in, and also kills any existing sessions.
Closes #537.
=> [www] Add admin ability to deactivate users.

politeiawww/admin.go, util/paywall.go
Fixes the insight testnet url and a bug with the user payments rescan that occurs when proposal credit payments are in the same block as the user registration payment.
=> [www] Fix insight url and payments rescan bug.

decredplugin/decredplugin.go, politeiad/backend/gitbe/decred.go, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawwwcli/commands/startvote.go, politeiawww/config.go, politeiawww/convert.go, politeiawww/sample-politeiawww.conf
Close #538 
This diff adds the parameters `QuorumPercentage` and `PassPercentage` the to start vote command. 
`QuorumPercentage` is used to indicate the percentage of eligible tickets that must vote in order fo a quorum to have been met.  `PassPercentage` is used to indicate the percentage of total votes that are required for the vote to pass.  Vote duration is turned into a configurable www parameter.
=> [d+www] Add vote parameters to start vote.

politeiawww/admin.go, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/backend_user_test.go, politeiawww/database/database.go
This commit makes the following changes:
* Add a new user registration expiry field specifically for resend
email requests. This allows a user to request another registration email
before the email-spam-prevention period has ended.
* Reduce the email-spam-prevention period to 1 day.
* Add a new login error that notifies the user he cannot login
specifically because his email is unverified.
This is intended to help address the issues raised in decred/politeiagui#745.
=> [www] Minor improvements to new user registration.

politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/user.go, politeiawww/www.go
Closes #498 
This PR removes proposal data from the user struct that is returned by the `UserDetails` route. Proposal data should be accessed through the `UserProposals` route.
=> www: Remove proposals from user details

politeiawww/api/v1/api.md, politeiawww/backend.go, politeiawww/inventory.go, politeiawww/www.go
Closes #578 
This PR fixes how the `NumOfProposals` value is calculated in the `UserProposals` endpoint. 
Before, the `NumOfProposals` value was the total number of proposals that had been submitted by the user regardless of proposals status. 
Now, the `NumOfProposals` value reflects the number of proposals that are available to be returned from the `UserProposals` endpoint. If the request is being sent by an admin or a user is requesting their own proposals then `NumOfProposals` includes unvetted, censored, and public proposals. Otherwise, `NumOfProposals` only includes public proposals.
=>  www: Fix NumOfProposals value in UserProposals

politeiad/api/v1/api.md, politeiad/api/v1/v1.go, politeiad/backend/backend.go, politeiad/backend/gitbe/gitbe.go, politeiad/politeiad.go, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawwwcli/README.md, politeiawww/cmd/politeiawwwcli/commands/setproposalstatus.go, politeiawww/convert.go, politeiawww/inventory.go, politeiawww/inventory_test.go
Closes #479 
This commit adds the 'archived' record status to politeiad and the 'abandoned' proposal status to politeiawww. An abanonded proposal in politeiawww corresponds to a archvied proposal in politiad. Admins can declare a proposal abandoned at any time as long as the proposal is public and voting has not yet started. The admin must include a change message when changing a proposal status to abandoned and the admin's action is logged. Abandoned proposals are publicly viewable but cannot be edited, have the voting period authorized for them, have any new comments made or have any new comment votes cast.  Abandoned proposals are vetted proposals and are returned from the politeiad and politeiawww endpoints for fetching vetted proposals.
=> d+www: Add the proposal status abandoned

politeiavoter/politeiavoter.go, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/proposalvotes.go
Closes #576 
* Update the VoteResults endpoint to verify that the proposal exists
before sending a request to politeiad
* Don't print the user error when politeiavoter or wwwcli receive a 404
from www
* Update the human readable error message for ErrorStatusInvalid to make
it explicit that it is an invalid error status, not an invalid proposal status
* Remove eligible tickets snapshot from wwwcli VoteResults output to
make it readable (only for normal output, not JSON or Verbose)
=> multi: Improve various error handling

politeiawww/backend.go
Now `ProcessLikeComment` verifies at the start of the execution if the comment exists, before proceeding with plugin and daemon interactions.
closes #580
=> www: Verifies that comment exists before like action

politeiawww/backend.go
Closes #511 
This fixes a bug that was allowing a vote authorization to be revoked after the proposal vote had started.
=> www: Fix authorize vote bug

politeiad/api/v1/api.md, politeiad/api/v1/mime/bmime.go, politeiawww/api/v1/api.md
Closes #607
We have decided to remove SVG image support until adequate Golang tooling exists for sanitizing SVG.
=> d: Remove svg from accepted MIME types

politeiawww/admin.go, politeiawww/api/v1/v1.go, politeiawww/user.go
Now returns proper error in case the passed UUID is invalid or non-existent in our DB. Fixed commands were `manageuser` and `rescanuserpayment`, which receives a UUID as input.
closes #561
=> www: Fix UUID validation and proper error returns

decredplugin/decredplugin.go, politeiad/backend/gitbe/decred.go, politeiad/backend/gitbe/gitbe.go, politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/commentsvotes.go, politeiawww/comments.go, politeiawww/inventory.go, politeiawww/www.go
This PR removes the comment likes tally from d and add into www. It also standardizes the terminology as comment likes instead of mixing comment votes and comment likes across structs and functions.
The comment likes are all fetched from d when the www inventory is initialized and it is updated as new "comment likes" come in.
closes #603
=> www + d: Move comments likes tally from d to www

politeiawww/backend.go
Resolves #629. Also depends on https://github.com/decred/politeiagui/pull/936
This commit disables admin privileges to abandon a proposal if voting has been authorized by the user.
=> www: Disable abandoned state if voting authorized

politeiawww/email.go, politeiawww/events.go
This commit resolves two bugs with email notifications for comments.
-Change link in email notification for new comments to the permalink of the comment, instead of the proposal link.
-Disable email notifications for comments and replies posted by the proposal's author.
=> www: Fix bugs with email notifications for comments

politeiavoter/politeiavoter.go
This checks the error returned when making a request to specifically detect a `*url.Error`, which can often happen on Tor for various reasons, and convert it to a retry error so that code which deals with retries will properly retry the request.
=> politeiavoter: Retry on failed req due to URL err.

politeiawww/api/v1/api.md, politeiawww/api/v1/v1.go, politeiawww/backend.go, politeiawww/inventory.go
This Pull Request adds 3 new fields into the proposal struct:
```Go
PublishedAt         int64       `json:"publishedat"`                   // The timestamp of when the proposal has been published
CensoredAt          int64       `json:"censoredat"`                    // The timestamp of when the proposal has been censored
AbandonedAt         int64       `json:"abandonedat"`                   // The timestamp of when the proposal has been abandoned
```
closes #618
=> www - Return the timestamp by status of a proposal

politeiawww/backend.go
GET api/v1/proposals/votestatus
it should be init ,and return 
```
{
votesstatus: [ ]
}
```
insteadof
```
{
votesstaus: null
} 
```
when len of inventory is 0.
=> www: Fix VotesStatus not init

politeiawww/cmd/politeiawwwcli/commands/newuser.go
Return the paywall flag to new user command. It fetches address and amout from a request to `/me` and pays the fee.
closes #522
=> wwwcli: Adds --paywall flag to newuser command

README.md
dep is no longer required so should not be listed as a requirement in step 1 of setup.
Added a message that notes that Go version 1.11 is higher, since this is required for using Go modules.
=> readme: remove 'dep' listing as a dependency

politeiawww/cmd/politeiawwwcli/commands/getpaywallpayment.go, politeiawww/cmd/politeiawwwcli/commands/help.go, politeiawww/cmd/politeiawwwcli/commands/me.go, politeiawww/cmd/politeiawwwcli/commands/policy.go, politeiawww/cmd/politeiawwwcli/commands/proposalpaywall.go, politeiawww/cmd/politeiawwwcli/commands/rescanuserpayments.go, politeiawww/cmd/politeiawwwcli/commands/resetpassword.go, politeiawww/cmd/politeiawwwcli/commands/startvote.go, politeiawww/cmd/politeiawwwcli/commands/updateuserkey.go, politeiawww/cmd/politeiawwwcli/commands/verifyuserpayment.go
This commit adds new help messages for the commands:
- getpaywallpayment
- me
- policy
- proposalpaywall
- rescanuserpayments
- resetpassword
- startvote
- updateuserkey
- verifyuserpayment
=> wwwcli: Add new help messages

politeiawww/api/v1/api.md
This commit fixes the markdown in tables that weren't rendering 
properly in the politeiawww API Specification.
=> www: Fix formatting tables

politeiad/backend/gitbe/decred.go
This commit fixes a bug that was causing an error to be incorrectly logged when a comment is submitted to a proposal that already has existing comments.
The error is only supposed to be logged if the politeiad in-memory cache contains an existing comment with the same comment ID as the new comment.  The error is actually being logged anytime there are any existing comments in the cache for the given record.
=> politeiad: Fix new comment error bug

politeiad/cmd/politeia/politeia.go, politeiad/config.go, politeiawww/cmd/politeiawwwcli/commands/editproposal.go, politeiawww/cmd/politeiawwwcli/commands/newproposal.go, politeiawww/config.go, util/file.go
Closes #692.
This commit fixes the implementation of the `cleanAndExpandPath` function that is used in politeiad and politeiawww.  The old implementation was replacing the `~` character with the OS specific data directory.  The new implementation was taken from dcrd and replaces the `~` character with the OS specific home directory.
=> multi: Fix CleanAndExpandPath implementation

politeiad/cmd/politeia/politeia.go, util/file.go
This removes MIME type validation from `util.LoadFile`.  It was causing politeiad inventory calls to error out when an old version of a record contained a now unsupported MIME type.  
MIME types are validated when records are submitted, but are no longer validated when records are retrieved.
=> util: Remove MIME validation from LoadFile

politeiawww/www.go
This commit fixes a bug that was causing the proposal details route to return a 500 when accessed by a user that was not logged in.
=> www: Fix session lookup bug

politeiawww/cmd/politeiawwwcli/commands/edituser.go, politeiawww/cmd/politeiawwwcli/commands/manageuser.go
This commit adds human readable input settings to the edituser
command. Help command text is also updated to reflect new
human readable options. ( Closes #642 )
=> wwwcli: Adds human readable settings edituser

politeiawww/cmd/politeiawwwcli/README.md
Mentioned by @camus-code on matrix.
=> [wwwcli] Remove incorrect testnet option in README

politeiavoter/politeiavoter.go
This checks the status code returned when making a request to specifically detect a gateway timeout, which can often happen on Tor for various reasons, and convert it to a retry error so that code which deals with retries will properly retry the request.
Fixes #713.
=> politeiavoter: Retry on failed req due to timeout.

util/paywall.go
This PR adds a few fixes & updates to the paywall code:
1. Log errored response (status code != 200) from dcrdata or insight.
2. Fix insight requests paths by adding the prefix `/insight`.
=> Paywall fixes

README.md
This commit adds `mode=piwww` to the list of default parameters for `politeiawww.conf` in the README. 
Without setting this parameter, the user will get the below error when trying to run politeiawww.
```
"_Could not load configuration file: invalid mode:_".
```
As an alternate solution, we could also tell the user to set this parameter on the command line when loading their identity, as was suggested by @fernandoabolafio in this [chat on #politeia](https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$1552633121257503xwvMX:matrix.org?via=decred.org&via=matrix.org&via=zettaport.com) (it appears to have worked for the user).
```
politeiawww --mode=piwww  --fetchidentity
```
=> www: Adds mode=piwww to default politeiawww.conf configutation

politeiad/config.go
This commit fixes a bug in the politeiad config where the cache params were being loaded even if the cache had not been enabled.
=> politeiad: Fix cache param bug

politeiawww/proposals.go, util/paywall.go
The `_fireEvent` function was being called without the lock being held in a few different places.  This commit updates those calls to use the `fireEvent` function instead, which does not require the caller to have the lock held.
It also fixes an error in `util/paywall.go` that travis was complaining about.
=> www: Fix fireEvent bugs

politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/convert.go, politeiad/cache/cockroachdb/decred.go, politeiad/cache/cockroachdb/models.go
This commit changes the type of the version fields in the cache models from string to uint64.  This is necessary because some of the queries rely on ordering the results by version.  The bug becomes apparent when the proposal version gets into the double digits.
=> cache: Change version type to uint64

politeiad/backend/gitbe/decred.go
This commit prevents votes from being accepted during the end height block.
old:  `bestBlock > endHeight`
new: `bestBlock >= endHeight`
It also changes the order of the ballot validation.  The vote bits are now validated before the end height is checked.
=> politeiad: Fix ballot end height bug

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/admininvoices.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/userinvoices.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/database.go, politeiawww/cmswww.go, politeiawww/invoices.go
This commit adds the UserInvoices and AdminInvoices routes that allow
for users and administrators to request invoices based on certain
criteria.
Currently UserInvoices simply responds with all of the currently logged
in user's invoices. While the AdminInvoices request requires an admin
to be logged in.  AdminInvoices allows searching by month/year and/or
status.  If none of these fields are used, then all of the current
invoices will be returned.
=> Add UserInvoices and AdminInvoices routes

politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/decred.go
This commit updates how the cache gets build.  The records cache and the
decred plugin cache were previously being built using a transaction for
each. The decred plugin cache was exceeding cocroachdb's transaction
size limit when it was built using the data from proposals.decred.org.
Specifically, the large amount of cast vote data was causing the build
process to failing.
This commit updates the build process to build the cache without using
transactions.
=> cache: Build cache without using a transaction.

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/editinvoice.go, politeiawww/cmd/politeiawwwcli/commands/help.go, politeiawww/cmd/politeiawwwcli/commands/setinvoicestatus.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/cmsdatabase/database.go, politeiawww/cmswww.go, politeiawww/convert.go, politeiawww/invoices.go
~Requires #735~
EditInvoice allows users to update their invoices based on comments by
administrators.  This will change the status of the invoice back to
InvoiceStatusUpdated so the administrators will be notified that the
invoice must be reviewed again.
SetInvoiceStatus allows administrators to update the status of a given
invoice.  This can be set to updated, disputed, rejected or approved.
For either of these commands, a corresponding request is sent to the
politeiad backend to update the records and keep the updates journaled.
=> Add EditInvoice and SetInvoiceStatus routes

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/politeiawwwcli/commands/newinvoice.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/cmsdatabase/database.go
Instead of letting users enter in a variety of information,
we've created LineItemType to better organize the line items down
the road.  Currently, this includes 2 main types (labor/expense),
and 1 misc catch all.
=> Introduce LineItemType for better organization

politeiawww/convert.go, politeiawww/invoices.go
Closes #766.
This commit removes the fields `month`, `year`, and `name` from the invoice metatdata.  Month and year are already included in the invoice json and the invoice name was not actually being used anywhere.
The `00.metadata.txt` file now looks like this:
```
{
"version": 1,
"timestamp": 1554214582,
"publickey": "663780987a9e31818573798ef1143c4085da0598f7ef32348b16dfc67ad98e8a",
"signature": "06ba43dd2f708b399075e2ac3cad57db1a67247503c892553f61eb2500815a15b10219a03d7427c9f4df5ee387c1a1b2e0ff81deae400cd43034c671abfbc20a"
}
```
=> cms: Remove month, year, name from invoice md.

politeiawww/api/cms/v1/v1.go, politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/commands/newinvoice.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/cmsdatabase/database.go, politeiawww/convert.go, politeiawww/invoices.go
This gives us more flexibility when organizing expenditures for
public consumption down the road.
For example:
Domain: Development
Subdomain: Decrediton
This would allow us to group all spending for each domain and
subdomain, instead of purely "subtype".
=> Add new domain/subdomain line item fields

politeiawww/convert.go, politeiawww/invoices.go, politeiawww/proposals.go
This commit breaks out the invoice status changes into their own
metadata stream. They were previously being included in the record
status change metadata stream. This wasn't going to work though because
invoice statuses do not map 1-to-1 to record statuses. They need their
own metadata stream.
The convertPropFromCache function was being used throughout the invoice
routes which is no beuno. Changing the metadata streams broke this code
so I also went ahead and cleaned up the parts of code that were fetching
invoices from the cache.
=> cms: add md stream for invoice status change

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/commands/register.go, politeiawww/invoices.go, politeiawww/user.go
This is the first in a series of PRs to address issue #765 
We will no longer be storing this information within the userdb and
instead will be entered per invoice.
=> Remove name, location and ext pubkey from userdb

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go
The error code `ErrorStatusInvalidInvoiceInputVersion`was removed from the "human readable" map but it was not removed from the list of status code. This was creating an unmatching between the errors codes and their respective message.
This PR fixes that and update the error codes.
=> Remove unused error status and update codes accordingly

politeiawww/cmd/politeiawwwcli/commands/register.go, politeiawww/user.go
This commit fixes a bug in the `politeiawwwcli register` command. The
command was logging in the user after registration but was not saving
the logged in user to disk, which is required so wwwcli knows which
identity to load.
It also removes some unnecessary code in the processRegisterUser
function.
=> wwwcli: Fix cms register bug

politeiawww/convert.go, politeiawww/invoices.go
The intial status of an invoice was not being added to the markdown
stream mdStreamStatusChanges when a new invoice was submitted.
=> cms: Update mdStreamStatusChanges on new invoice

politeiawww/proposals.go
Abandoned proposals are throwing a 400 error when votestatus is called.
This is because the abandoned status didn't exist when the votestatus
route was written. This commit fixes this by checking for abandoned
proposals in addition to public proposals and allowing both to be
accessed ( Closes #785 ).
=> www: Fix votestatus 400 error abandoned proposals

politeiad/cache/cache.go, politeiad/cache/cachestub/cachestub.go, politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/convert.go, politeiad/politeiad.go
This commit adds a cache update to the politeiad route updateVettedMetadata. This route was not being used by politeiawww until recently so it was missed in the original cache implementation.
=> politeiad: update cache in updateVettedMetadata

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/generatepayouts.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmswww.go, politeiawww/invoices.go
This request is mostly a place holder for payment handling by admins.
It returns the payout information for all currently approved invoices.
With this information admins can do a final audit of the payout and
then construct the on-chain transaction to complete the invoice.
In the future, much of this payout system will be automated and will
require no intervention by an administrator.
=> Add GeneratePayouts admin request

politeiawww/api/cms/v1/v1.go, politeiawww/convert.go
This now allows us to directly decode the file into the InvoiceInput
therein.  This will allows any requests that return InvoiceRecords 
to have direct access to the parsed InvoiceInput and LineItemInput.
Also remove some extraneous fields that are already included in the 
InvoiceInput (Month, Year, ContractorName, Location etc)
=> [cms] Add raw invoice to InvoiceRecord and remove extra

politeiad/config.go
this fixes a panic if the root certificate is not valid.
=> politeiad: check pem Decode results

README.md
In the README, we say a line in `politeiawww.conf` references a mac OS path; it's actually referencing Linux. This commit fixes the wording ( Closes #760 ).
=> politeiawww: Corrects OS reference in README

README.md, cachesetup.sh, cmssetup.sh, cockroachcerts.sh, politeiad/cache/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/config.go, politeiawww/www.go
This commit merges the politeiawww config settings for the cache
database and the cms database into a single set of parameters. It also
updates the database users.  There are now only two database users:
politeiad and politeiawww.  Permissions are set accordingly per
database.
=> www: simplify database setup

politeiad/cache/cache.go, politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/decred.go, politeiad/politeiad.go, politeiawww/www.go
This commit fixes a bug that was introduce in #800 that was preventing the cache from being properly setup when the version table did not exist.  It improves the version record lookup process by adding debug statements and differentiating between when an version record was not found and when the record was found but there was a version mismatch.
=> cache: update version record lookup

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/api/www/v1/api.md, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/help.go, politeiawww/cmd/politeiawwwcli/commands/invoicecomments.go, politeiawww/cmswww.go, politeiawww/comments.go, politeiawww/invoices.go
This adds a new NewCommentInvoice endpoint for cms.  Having a
fully separate version was done to avoid the paywall check and the 
proposal specific checks there.
Currently, only admins or the owner/creator of a given invoice should
be able to comment on that invoice.  And it must not be in Approved 
or Paid status.
=> [cms] Add new comment endpoint for invoices

politeiad/cache/cockroachdb/models.go, politeiawww/politeiawww.go, politeiawww/proposals.go, politeiawww/www.go
This commit focuses on improving the performance of the vote status API
endpoints.  It does so by:
1. Indexing the cast votes by token in the cache database.
2. Caching the vote results in politeiawww memory for proposals whose
voting period has ended.
Indexing the cast votes by token in the cache database improved cast
vote lookup times by ~25%.
Most of the performance benefits come from caching the vote results in
memory for proposals whose voting period has ended.
Response times for the `/proposals/votestatus` route are included below.
The response times are the result of testing the route locally against
the pi production mainnet data.  Response times on my local machine are
significantly slower then the production site, so I've also included the
response time from the production site …
=> www: improve performance of vote status endpoints

decredplugin/decredplugin.go, politeiad/cache/cache.go, politeiad/cache/cockroachdb/convert.go, politeiad/cache/cockroachdb/decred.go, politeiad/cache/cockroachdb/models.go, politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/tokeninventory.go, politeiawww/convert.go, politeiawww/decred.go, politeiawww/politeiawww.go, politeiawww/proposals.go
Closes #795.
This diff adds a TokenInventory route to politeiawww.  The TokenInventory route retrieves the censorship record tokens of all proposals in the inventory.  The returned tokens are categorized in a manner that resembles their vote statuses, but that has been altered to be a more natural fit with how a UI would display them.  The categories are pre, active, finished, and abandoned. 
The 'finished' category was not broken up into 'approved' and 'rejected' because politeia is designed to be able to handle proposal votes with multiple voting options.  Categorizing the finished proposal votes into 'approved' and 'rejected' only makes sense for simple yes/no proposal votes.
The cache StartVote model was also updated.  The type of the EndHeight field was changed from a string to a …
=> www: Add TokenInventory route

politeiad/backend/gitbe/decred.go, util/paywall.go
Resolves #698 
This commit adds validation to ensure HTTP status codes are `http.StatusOK` before decoding a JSON response
=> [d/util]: add validation for http.StatusOk

politeiawww/cmd/politeiawww_dbutil/README.md, politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
This commit adds the --stubusers option to the politeiawww_dbutil tool.
The stub users option creates user stubs in the user database for the
public keys found in the passed in directory.  It is intended to be used
in conjunction with the politeiaimport tool to allow developers to
import the decred mainnet proposal data and test against it.
=> dbutil: Add stub users command

politeiad/cache/testcache/decred.go, politeiad/cache/testcache/testcache.go, politeiad/testpoliteiad/convert.go, politeiad/testpoliteiad/decred.go, politeiad/testpoliteiad/testpoliteiad.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/convert.go, politeiawww/events.go, politeiawww/paywall.go, politeiawww/proposals.go, politeiawww/proposals_test.go, politeiawww/testing.go, politeiawww/user.go, politeiawww/user_test.go, politeiawww/userwww_test.go
This commit adds a few things related to politeiawww testing.
- Adds a testpoliteiad package.  testpoliteiad is a httptest server that
implements the politeiad api.
- Adds a testcache package.  testcache is an implementation of the Cache
interface that stores records in memory and that can be used for
testing.
testpoliteiad and testcache allow us to fake the responses from
politeiad and the cache so that we can fully test the politeiawww
routes.
This commit also adds test coverage to processNewProposal,
setProposalStatus, and verifyStatusChange.
This commit increases politeiawww test coverage from 15.7% to 21.6%.
=> www: Add proposal tests

.gitignore, politeiad/backend/gitbe/gitbe.go, politeiad/cmd/politeiaimport/README.md, politeiad/cmd/politeiaimport/politeiaimport.go, politeiad/config.go, politeiad/sharedconfig/sharedconfig.go
This commit adds the `politeiaimport` tool which allows you to import
data from a public politeia repo into politeiad.  It sets up the
unvetted and vetted repositories and recreates the journals.  The git
history from the import directory is kept intact.
=> Add politeiaimport tool

politeiawww/cmswww.go, politeiawww/userwww.go, politeiawww/www.go
Close #808 
This adds a new route registering function while using CMS mode.
This will hopefully remove the need for any mode checks downstream.
If CMS (or any other mode) need a slightly different implementation of
a shared route, they may change the route in `setCMSUserWWWRoutes()`
to a newly added handler defined in `userwww.go`
=> [cms] Add new route register func for cms mode 

politeiawww/invoices.go
Close #794 
`processEditInvoice` now includes an additional call to politeiad to `UpdateVettedMetadata` 
to include the new status, `InvoiceStatusUpdated`.
=> [cms] Update record metadata on invoice edit

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/invoices.go
This adds basic validation that the current date is not before the end of the 
invoice's billing cycle.
=> [cms] Add month/year validation to invoice input

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/invoiceexchangerate.go, politeiawww/cmswww.go, politeiawww/prices.go
This is a first pass of implementing an exchange rate endpoint.
It calculates a monthly average exchange based on a provided month/year.
Currently, this is calculation is done each time.  Once this implementation
and calculation has been approved/merged, I will go about adding a caching system
in the cms database that will only request the prices and calculate when if there
is not an entry found in the database.
=> [cms] Add invoice exchange rate endpoint

politeiawww/api/cms/v1/v1.go, politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/commands/newinvoice.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/cmsdatabase/database.go, politeiawww/convert.go, politeiawww/invoices.go, politeiawww/prices.go
This adds an ExchangeRate field to the InvoiceInput struct.
With this change it requires newly submitted invoices to have
the corresponding month's exchange rate included in the invoice
payload.  In doing so, it requires the cli request for newinvoice to
first request the exchange rate from the server to use.  A similar
process will be required when using the GUI.  
This also adds additional fields to the generated payouts for admins.
Exchange rate and the total DCR to be paid out by the invoice.
=> [cms] Add ExchangeRate to invoice json

decredplugin/decredplugin.go, politeiad/backend/gitbe/decred.go, politeiad/backend/gitbe/gitbe.go, politeiad/cache/cockroachdb/decred.go, politeiad/cache/cockroachdb/models.go, politeiawww/api/www/v1/v1.go, politeiawww/convert.go, politeiawww/decred.go, politeiawww/proposals.go
Closes #819.
This commit removes the 'finished' field from the token inventory reply
and replaces it with the fields 'approved' and 'rejected'. These fields
correspond to proposals with approved and rejected votes.
A cache table for vote summaries was added to enable proposal lookups by
whether their vote was approved or rejected. The vote summaries table is
lazy loaded. Loading vote summaries required the addition of a new
decred plugin command since only politeaid has write access to the
cache.
=> multi: Add token inventory approved and rejected

politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/cmsdatabase/database.go, politeiawww/invoices.go, politeiawww/prices.go
Requires #821 
This adds a new table into the cmsdatabase that caches
calculated monthly averages for a given month/year.
The first time a month/year is requested, the results are
stored and retrieved for any subsequent requests.
=> [cms] Cache exchange rate

politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/commands/users.go, politeiawww/user.go, politeiawww/user/localdb/localdb.go, politeiawww/user/user.go, politeiawww/userwww.go
In order for an external tool to be able to verify things like a
comment score, there needs to be a way to lookup public user details
by pubkey. This commit accomplishes this via the following changes:
- Makes the /users endpoint public
- Adds UserGetByPublicKey method to the user database interface
- Allows non-admins to filter users by username or pubkey (endpoint
returns only user ID and username for matches)
- Allows admins to search by username, email, or pubkey (endpoint
returns user ID, email, and username for matches)
=> www: Allow user details lookup by pubkey

decredplugin/decredplugin.go, politeiad/backend/gitbe/decred.go, politeiad/backend/gitbe/gitbe.go, politeiad/cache/cockroachdb/convert.go, politeiad/cache/cockroachdb/decred.go, politeiad/cache/cockroachdb/models.go, politeiawww/convert.go, politeiawww/decred.go, politeiawww/politeiawww.go, politeiawww/proposals.go
Closes #796.
This commit does two things:
1. Creates a light weight VoteSummary decred plugin command that returns
a summary of the vote params and results. Without this command, the only
way to get a summary of the vote results was to fetch all of the cast votes
and tally them manually.
2. Renames the VoteSummary table to VoteResults, which is a more
accurate name.
=> decredplugin: Add VoteSummary command

politeiawww/user/user.go
This commit removes cms specific fields from the User struct that are no longer being used.
=> cms: Remove unused user fields

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/user.go, politeiawww/user_test.go, politeiawww/userwww_test.go
This commit adds an `ErrorStatusInvalidPassword`, which is triggered by `processChangeUsername` when attempting to change the username with an invalid password.
Fixes #831
=> [www]: Invalid password Error Status

politeiawww/api/cms/v1/v1.go, politeiawww/invoices.go
There were 2 Max length policy's available for line item field length.  I've opted to remove one and update the old to the proper value of 200.  Verified that the policy is properly given to the GUI for validation.
=> [cms] Remove confusing policy field

decredplugin/decredplugin.go, politeiad/cache/cockroachdb/decred.go, politeiawww/api/www/v1/v1.go
This commit fixes a bug in some of the the sql queries from the token
inventory command.  The queries were ordering results by start block
height, which is a string.  They should have been ording results by end
height, which is a uint64.
=> cache: Order vote inv by end height

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/payinvoices.go, politeiawww/cmswww.go, politeiawww/invoices.go
This is a temporary command that allows for administrators
to set all approved invoices to paid.  
This command will be either be wholly removed or changed
significantly when the address watcher for paid invoices
has been added.  
We may keep this command in some fashion to allow for
administrators to update to the paid status in case of issues
or problems with the watcher.
=> [cms] Add PayInvoices command

politeiawww/cmsnotifications.go, politeiawww/cmswww.go, politeiawww/email.go, politeiawww/politeiawww.go, politeiawww/templates.go, politeiawww/www.go
Closes #823 
This notification system uses https://github.com/robfig/cron to schedule a check every month at a given time to check to see if all non-admin users have submitted an invoice for the previous month.  If they have not then they will be sent a short email notifying them to submit one to expedite the processing.
=> [cms] Add email notification for invoices

politeiawww/user.go, politeiawww/user_test.go
A bug was introduced in commit 00994d0 that allowed users with duplicate
usernames to be created for both pi and cms. This commit fixes that bug.
=> www: Enforce unique usernames in pi and cms

politeiad/cache/cockroachdb/decred.go, politeiad/cache/cockroachdb/models.go
This commit fixes a bug that was causing the vote option details to not be returned in the vote results query.
=> cache: Fix VoteOptionResult bug

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/invoices.go
Close #887 
This also uses a more descriptive error when labor or expense fields are invalid.
=> [cms] Properly validate line item type

politeiawww/api/cms/v1/v1.go
There were some users that were going above the 200 char limit.
=> [cms] Bump line item column length to 500

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/proposals.go
Closes #761 
This commit adds validation into politeiawww which prevents submission of an edited proposal unless it actually contains changes. If there are no changes, this validation returns `ErrorStatusNoProposalChanges`
=> [www]: Validate changes for proposal edits

politeiawww/invoices.go
An upcoming PR will update events for CMS to notify users and admins of changes to status or comments etc.
=> [cms] Remove events fires for invoices

politeiawww/paywall.go, politeiawww/user.go
This PR solves a inconsistency when removing users from the paywall polling pool. A detailed comment about the bug is written on top of `removeUsersFromPool` function.
=> www: Fix inconsistencies in paywall polling logic

politeiawww/comments.go, politeiawww/proposals.go, politeiawww/proposals_test.go
This commit adds validation to the GetAllVetted and GetAllUnvetted
routes to ensure that the tokens being passed up in the Before and After
params are valid censorship tokens. Unit tests are also added.
=> www: Validate Before and After tokens

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go
The `/proposals/vetted` and `/proposals/unvetted` have the optional
query params "before" and "after".  These query params filter the
proposals after they've been sorted into reverse chronological order.
This is not what you would typically expect, so I added additional
documentation to make this clear.
=> www: Add doco for proposal filtering params

politeiad/backend/gitbe/decred.go, politeiad/cache/cockroachdb/decred.go
This commit updates how votes are inserted into the cache. It removes
the vote lookup that was checking for duplicate votes. This lookup query
was too expensive and is not needed. It was causing cache build times to
be unreasonable (~3 hours) and would also cause extremely long response
times if someone were to cast a large block of votes all at once, which
does occasionally happen.
Removing this query does not effect whether duplicate votes will be
added to cache once they have been rejected by gitbe. Any vote that does
not have a valid vote receipt is not added to cache. Duplicate votes
that are rejected by gitbe do not contain a valid vote receipt.
Removing this query does mean that the 15 duplicate votes that made it
into the "Decentralize Treasury Spending" proposal vote journal will …
=> cache: Remove duplicate vote lookup

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/database.go, politeiawww/invoices.go
This ensures that no payment is used multiple times.  This will be an integral part of the upcoming payment address watching system.
=> [cms] Add dupicate payment address check

politeiawww/invoices.go
This corrects a bug with the duplicate payment address check while attempting to edit.
The validating of invoices would fail when attempting to edit, since it would find an invoice with a matching payment address (itself).
=> [cms] Fix duplicate address check for editing

politeiawww/api/cms/v1/v1.go
Possibility that some companies or location would contain a numeral.
=> [cms] Add 0-9 to acceptable Name/Location regex

politeiawww/user.go, util/paywall.go
Closes #747 
This commit removes all the direct references to the Insight API in `util/paywall.go`. However, this commit *does* leave in place much of the structure for utilizing a backup paywall URL, should we decide to move to a new one in the future.
=> [util]: Remove Insight references in paywall

politeiawww/testing.go, politeiawww/user.go, politeiawww/user/user.go
Fixes the bug documented in decred/politeiagui#1249.
This commit improves the code for managing user identities, fixes a
bug that was preventing users from updating their identity properly,
and refactors the routes that create/update a user identity to use the
new identity management methods.
Bug details:
If a user requested a new identity, but never verified the identity,
then requested another new identity once the original verification token
had expired, the user would end up with multiple inactive identities in
their identities array. When they eventually did verify an identity, the
wrong identity was being activated.
=> www: Improve user identity managment

politeiawww/comments.go, politeiawww/events.go, politeiawww/invoices.go, politeiawww/politeiawww.go, politeiawww/proposals.go, politeiawww/testing.go, politeiawww/user.go, politeiawww/user/cockroachdb/cockroachdb.go, politeiawww/user/localdb/localdb.go, politeiawww/user/user.go, politeiawww/www.go
Closes #861.
This diff removes the public key memory cache from politeiawww. A
UserGetByPubKey function is added to the user database interface. All
user lookups by public key now query the user database instead of
relying on a memory cache.
=> www: Remove pubkey memory cache

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/lineitempayouts.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/database.go, politeiawww/cmswww.go, politeiawww/convert.go, politeiawww/invoices.go
This command allows administrators to query the cms database for
all paid out line items within a given period of time.  This will be
used to create public summaries of expenditures by domain for any
given month.
=>  [cms] Add line item payout summary commands 

politeiawww/invoices.go
This should fix the following issue:
Admin reported that an address had an extra space within the exported payout CSV.  This caused problems when attempting to process the payouts and had to fixed manually.
=> [cms] Trim spaces for Address for payouts

politeiawww/api/cms/v1/v1.go, politeiawww/convert.go, politeiawww/invoices.go
Close #826 
This should streamline payout calculation for clients.  It will be returned
along side the pure invoice record returned from the backend.
=> [cms] Add Payout to InvoiceDetailsReply

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/invoices.go
Close #849
After consideration, the administrators felt like there could be valid situations where a contractor may need to submit multiple invoices for a given month.
=> [cms] Remove check for multiple invoices per month

politeiawww/cmsaddresswatcher.go, politeiawww/politeiawww.go, politeiawww/wsdcrdata.go, politeiawww/www.go
This diff pulls the dcrdata websocket functionality out of the cms address watcher implementation and creates a general abstraction for managing dcrdata websocket connections.
It also updates the cms address watcher naming convention to make a distinction between cms address watching and the pi paywall functionality, which will both use dcrdata websocket subscriptions for address events.
=> www: Update wsDcrdata context

politeiawww/cmsaddresswatcher.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, util/paywall.go
This fixes some outstanding issues with payment checking and
address watching.  
Now upon address subscription notification, the included txid
and the address will be used to query dcrdata for the
full transaction information via util.FetchTx.  
For restart, it will now use checkHistoricalPayments which
still uses util.FetchTxsForAddressNotBefore to pull all transactions
for a given address before a given time.
=> [cms] Fix address watching for invoices

politeiawww/invoices.go
Closes #935 
We now do slightly different checks after invoice validation occurs
in both NewInvoice and EditInvoice.  If there are any similar addresses
found during NewInvoice, that will throw the error.  And EditInvoice should
expect 1 invoice returned from the db request (the given invoice).
=> [cms] Add duplicate address checks in New/EditInvoice

politeiavoter/politeiavoter.go, politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/commands/login.go, politeiawww/cmd/politeiawwwcli/commands/newuser.go, politeiawww/cmd/politeiawwwcli/commands/register.go, politeiawww/cmd/politeiawwwcli/commands/testrun.go, politeiawww/user.go, politeiawww/user_test.go, politeiawww/userwww_test.go
This is required for #860.
This diff switches the login to require that a user login using their
username instead of their email address. The timing attack protection
was removed since usernames are public.
politeiagui changes will need to be completed before this can be merged.
=> www: Switch login to use username.

politeiawww/api/www/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/resetpassword.go, politeiawww/email.go, politeiawww/user.go, politeiawww/user_test.go, politeiawww/userwww.go, politeiawww/userwww_test.go
This is required for #860.
This diff removes the user lookups by email address from the reset
password route and splits the ResetPassword route into two separate
routes.
ResetPassword
VerifyResetPassword
This is consistent with the pattern that is used for VerifyNewUser and
VerifyUpdateUserKey.
Since the ResetPassword command now contains the username and email
address, it was necessary to add a minimum wait time to the route in
order to prevent an attacker from being able to execute a timing attack
to determine if the provided email address is the user's valid email
address.
politeiagui changes will need to be completed before this can be merged.
=> www: Remove email lookups from reset password.

politeiawww/cmswww.go, politeiawww/convert.go, politeiawww/invoices.go
This removes the request to find all of the same information again from the politeiad cache and instead just converts the database invoice to the expected invoice record to return.
=> [cms] Improve admin invoices request performance

politeiawww/cmsnotifications.go, politeiawww/email.go, politeiawww/events.go, politeiawww/templates.go
Closes #963 
Closes #950 
Includes a few fixes for various issues with CMS email notifications.
- No longer send emails to unregistered users.
- Fix displayed month for invoice notifications.
- Add invoice token to invoice status update email.
=> [cms] Various email notification fixes

decredplugin/decredplugin.go, politeiad/cache/cache.go, politeiad/cache/cockroachdb/decred.go, politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/comments.go, politeiawww/decred.go, politeiawww/events.go
Closes #931.
This diff adds validation to politeiawww to prevent a user from
submitting a duplicate comment. A duplicate comment is defined as a
comment with the same signature as an existing comment.  The comment
signature is the token+parentID+comment.
The scenerio that this is meant to prevent is when a user submits the
same comment request multiple times due to some network/browser hiccups.
This has happened to multiple users on production pi.
It also cleans up some documentation that was out of date in `www/v1/api.md`.
Note: this only adds validation to politeiawww. It does not add any
validation to politeiad. This means thats its still possible to for
duplicate comments to make it into the politeiad repo if the duplicate
comment request is submitted before the original comment is …
=> multi: Prevent duplicate comments.

decredplugin/decredplugin.go, politeiad/cache/cockroachdb/decred.go, politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/convert.go, politeiawww/decred.go, politeiawww/politeiawww.go, politeiawww/proposals.go
This diff updates the token inventory route to also return the unvetted
tokens to admins in addition to the normal vetted tokens.
The gui redesign separates unvetted proposals into "unreviewed" and
"censored" when displaying them to an admin. This diff allows the gui
to fetch the specific proposals required to populate those views instead
of having to use the `AllUnvetted` route which just returns a page of
the most recent unvetted proposals.
=> multi: Return unvetted token inventory to admins.

politeiawww/cmsuser.go
Wasn't properly allowing admins access to user details request.
=> [cms] CMS UserDetails bug for allowed user action

scripts/cachesetup.sh
This PR resolves https://github.com/decred/politeia/issues/915. Added two sql commands to the newly created DB to disable CockroachDB diagnostic reporting. Verified that it worked by entering the cockroach sql cli client and checking the results (see below). 
```# Welcome to the cockroach SQL interface.
#
#
#
root@:26257/defaultdb> SHOW CLUSTER SETTING diagnostics.reporting.enabled;
diagnostics.reporting.enabled  
+-------------------------------+
false              
(1 row)
Time: 279.069µs
root@:26257/defaultdb> SHOW CLUSTER SETTING diagnostics.reporting.send_crash_reports;
diagnostics.reporting.send_crash_reports  
+------------------------------------------+
false                    
(1 row)
Time: 404.594µs
```
=> disable cockroach diagnostic reporting in cachesetup script

politeiawww/api/www/v1/v1.go
While working on politeiagui I bumped into several cases where I had to create workarounds due to the lack of those fields. This PR will keep all the unvetted fields as part of the token inventory despite they are empty or not.
=> www: Do not ommit empty unvetted fields for token inventory

politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/database.go, politeiawww/invoices.go
This fixes an issue with getting multiple duplicate payout line items.
The db request was not being restricted to only InvoiceStatusPaid invoice changes
as the comments suggested.
=> [cms] Fix LineItemByDate db payout request

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/politeiawwwcli/client/client.go, politeiawww/cmd/politeiawwwcli/commands/commands.go, politeiawww/cmd/politeiawwwcli/commands/dcccomments.go, politeiawww/cmd/politeiawwwcli/commands/newdcccomment.go, politeiawww/cmd/politeiawwwcli/commands/supportopposedcc.go, politeiawww/cmswww.go, politeiawww/convert.go, politeiawww/dcc.go, politeiawww/invoices.go
Requires https://github.com/decred/politeia/pull/980
This PR adds the ability for users to offer their support, opposition
and comment on active DCC proposals (issuances or revocations).
When an authorized user submits a Support or Opposition request,
metadata from the request is appended to the existing DCC on
the politeiad backend.  This makes them permanent and verifiable.
=> [cms] Add Support, Oppose and Comment DCC functionality

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/politeiawwwcli/commands/newdcc.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/cmsdatabase/database.go, politeiawww/convert.go, politeiawww/dcc.go
This PR adds the ContractorType to the DCCInput data structure. 
This will allow us to set the contractor type of the nominee upon issuance
approval.  For now, we will be only allowing Direct and Sub contractor types.
Upon successful sub contractor issuance approval, the userid of the sponsor
will be set as their SupervisorUserID.
=> [cms] Add ContractorType to DCCInput

politeiawww/cmd/politeiawwwcli/commands/newdcc.go, politeiawww/dcc.go, politeiawww/invoices.go, politeiawww/user/cockroachdb/cms.go
This fixes a number of bugs exposed when completing further DCC testing:
- Fix invalidDCCContractorType checks.  Now properly erroring on Invalid or Nominee users.
- Fix invalidNewInvoiceContractorType checks.  Now properly erroring on Invalid or Nominee users.
- Set ContractorType in cms userdb update.
- Add spaces in newdcc CLI
=> [cms] Various fixes for DCC creation and CLI

go.mod, go.sum, politeiavoter/politeiavoter.go
This modifies the way vote eligibility is determined to ignore commitments for imported xpubs, refactors the relevant vote eligibility determination code into a separate function, and updates the inventory path to report eligible remaining votes in addition to the eligible tickets.
Credits to @jrick for the code that ignores commitments for imported xpubs.
=> politeiavoter: Improve eligible vote handling.

go.mod, politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/cmswww/edituser.go, politeiawww/cmd/cmswww/help.go, politeiawww/cmd/cmswww/manageuser.go, politeiawww/cmd/piwww/help.go, politeiawww/cmd/piwww/manageuser.go, politeiawww/cmd/piwww/piwww.go, politeiawww/cmd/shared/client.go, politeiawww/cmsuser.go, politeiawww/cmswww.go, politeiawww/userwww.go
This PR updates the usage of EditUser to basic contractor information.
Now all of the important fields which need to be restricted have
been added to a new request ManageUser.  
ManageUser requires admin credentials to update Domain,
ContractorType and SupervisorID. 
Once DCC has been put into production, these fields will be populated
by an approved DCC issuance, rather than administrator intervention.
=> [cms] Update EditUser and add ManageUser for CMS

politeiawww/proposals.go
Closes #1004 
This diff prevents the getVoteSummaries function from trying to parse
the vote end height when one does not exist.
=> www: Fix getVoteSummaries parse uint bug.

decredplugin/decredplugin.go, go.mod, politeiad/backend/gitbe/decred.go, politeiawww/api/www/v1/v1.go, politeiawww/convert.go
This diff adds an ErrorStatus field onto the decredplugin and
politeiawww CastVoteReply structs. CastVote errors were previously only
being returned as human readable strings in the CastVoteReply. The newly
added ErrorStatus field contains the numeric error code. This gives
clients the option to key off the error code.
=> multi: Add error codes to CastVoteReply.

decredplugin/decredplugin.go, politeiad/cache/cockroachdb/decred.go, politeiawww/api/www/v1/v1.go, politeiawww/proposals.go
Closes #1012.
This diff adds the duration to the VoteSummary struct. This was
previously overlooked because the gui doesn't use the duration, but it
makes sense to include it and Decrediton needs it.
=> multi: Add duration to VoteSummary.

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/politeiawww.go, politeiawww/proposals.go
This diff cleans up the doco for the BatchProposals and BatchVoteSummary
routes.  It also removes the api.md documentation for the ProposalStats
route, which no longer exists.
=> www: Doco for BatchProposals and BatchVoteSummary.

go.mod, go.sum, politeiawww/cmd/politeiavoter/README.md, politeiawww/cmd/politeiavoter/config.go, politeiawww/cmd/politeiavoter/politeiavoter.go, politeiawww/cmd/politeiavoter/politeiavoter_test.go, politeiawww/cmd/politeiavoter/retry.go
The big idea is to make politeiavoter a fire and forget type deal even
when dealing with terrible connections over tor.
When a vote fails move it to a retry queue where the vote will be
retried randomly within 120s. Failed votes are pushed to the end to the
retry list. If a vote fails in the retry loop it is also pushed to the
back of the queue. Votes that error out on the server are not retried;
this only deals with network errors.
=> [pivoter] Make politeiavoter less prone to network errors

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/cmswww/manageuser.go, politeiawww/cmd/cmswww/usersubcontractors.go, politeiawww/cmd/shared/client.go, politeiawww/cmsuser.go, politeiawww/cmswww.go, politeiawww/invoices.go, politeiawww/user/cms.go, politeiawww/user/cockroachdb/cms.go, politeiawww/user/cockroachdb/models.go
This PR adds the ability for a user to include line items that are
associated with their subcontractors.  This will become necessary 
information to populate once we start to tabulate hours work 
for the all-contractor vote capabilities.  
Also included in this PR:
- UserSubContractors request to allow users to get a list of
users that are currently associated with them.  This will make
entry much easier on the GUI as users will be offered their
subcontractors' usernames to select from a dropdown.
- Updates manageuser to include supervisoruserid
- Updates newinvoice to now looks for subcontractor userid CSV field
=> [cms] Add Sub-Contractor hours type to LineItem

politeiawww/cmd/politeiavoter/politeiavoter.go
The BatchVoteSummary endpoint is not live yet. This diff switches out
the BatchVoteSummary call for a VoteStatus call.
=> politeiavoter: Update BatchVoteSummary calls.

politeiawww/cmd/politeiavoter/politeiavoter.go
The best block call was not using the context client, which means the call was not being routed through the proxy.  This diff fixes that.  It also adds in logging for the best block call.
```
2019-10-22 09:54:28.189 [DBG] POLV: Request: GET https://explorer.dcrdata.org:443/api/block/best
2019-10-22 09:54:30.089 [TRC] POLV: Response: 200 {"height":390491,"size":33119,"hash":"00000000000000000bcfa2fa22d9e9f50e57b42cc5e2a09cf0010afd20a83c78","diff":27788681028.69406,"sdiff":129.79952598,"time":1571759072,"txlength":0,"ticket_pool":{"height":390491,"size":40838,"value":5333850.00654643,"valavg":130.6099712656455,"winners":["eb4ff11b6d97b47b7f1736205539927556d9f7c8fe72511f3f85bb2bb8d5c495","746d44a3d47fa2f7492a7dcb25e3cab053150c6d35530c7aa4e1a300bc3e4d5c","4c371ab49516ba33ee1f25383a6356d0012c61 …
```
=> politeiavoter: Use context client for best block.

politeiawww/api/cms/v1/api.md
This diff adds  1047, 1048, 1049 and 1050 error descriptions into the docs for CMS.
=> [docs] Add new error details on docs

politeiawww/api/cms/v1/v1.go, politeiawww/cmsaddresswatcher.go, politeiawww/convert.go, politeiawww/invoices.go
Adding payment information to the backend was overlooked in the initial implementation.
Upon receipt of any new payment by the address watcher a new backendInvoicePayment mdstream
is appended to the existing invoice record in politeiad.
With this, we will be able to fully recover cmsdb information pertaining to invoices from the backend anchored information on politeiad.
=> [cms] Add payment backend stream

decredplugin/decredplugin.go, politeiad/cache/cache.go, politeiad/cache/cachestub/cachestub.go, politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/decred.go, politeiad/cache/testcache/testcache.go, politeiawww/api/www/v1/api.md, politeiawww/decred.go, politeiawww/proposals.go, politeiawww/user/cockroachdb/cockroachdb.go, politeiawww/user/localdb/localdb.go
This diff standardizes how batched called are handled in the cache and
the userdb. Before this diff, some batched calls where returning a slice
of results and some were returning a map of results. Having all batched
calls perform the same way makes the code easier to reason about.
All batched calls in the cache and the userdb now return a map of the
results. If an output is not found for one of the input values, such as
if a passed in proposal token doesn't actually correspond to a proposal,
the input value will not be included in the returned map. This makes it
easy for the calling function to check if results where found for all
input values and leaves it up to the calling function to decide how to
deal with values that were not found.
=> multi: Cleanup batched calls in cache and userdb.

politeiawww/api/cms/v1/api.md, politeiawww/cmsuser.go
This implements the same public user information filtering that 
politeia uses.  If a non-admin and not the owner of the userid
requests the UserDetails for a given userID then a shorten list
of information is provided: 
ID, Admin, Username, Identities, ContractorType, GitHubName, MatrixName, Domain
=> [cms] Filter user details based on requester

politeiawww/api/cms/v1/api.md, politeiawww/cmd/cmswww/cmswww.go
1. Get DCC route: https://github.com/decred/politeia/blob/9a6d7c62c1d0f51f4fafa22bf14d9dd3b598a02b/politeiawww/api/cms/v1/v1.go#L30
2. `users` command:
https://github.com/decred/politeia/blob/9a6d7c62c1d0f51f4fafa22bf14d9dd3b598a02b/politeiawww/userwww.go#L842-L843
=> [cms] Minor fixes on api docs and cmd instructions

politeiawww/cmd/cmswww/userdetails.go
This is minor, but the CMS CLI was not correctly reading the `userid` value.
=> [cms] Add userid to userdetails cmd on cmswww cli

politeiawww/api/cms/v1/v1.go, politeiawww/dcc.go
Adding this now allows for better information to be displayed in 
DCC listings and details without have to perform subsequent requests
to retrieve that information.
=> [cms] Add nominated username to DCC Record

politeiawww/dcc.go, politeiawww/invoices.go
Previously there was overlap between 5 for invoice payments and DCC General.
Since we haven't yet implemented DCC's it would be easiest to just move them to an unused set rather than change invoice payments (which is in production now).
=> [cms] Move DCC mdStream IDs to unused 

mdstream/mdstream.go, politeiawww/convert.go, politeiawww/dcc.go, politeiawww/invoices.go, politeiawww/proposals.go
This diff renames the ProposalStatusChange mdstream to
RecordStatusChange. The name ProposalStatusChange did not make sense
since this mdstream is used by both pi and cms to store additional
status change metadata for general record status changes.
=> multi: Rename mdstream to RecordStatusChange.

politeiawww/cmd/cmswww/manageuser.go, politeiawww/cmd/cmswww/newinvoice.go
This diff makes the following changes to the cmswww manageuser command:
- Removes the CLI prompts that would occur when optional arguments were
left out. This allows the command to be used in scripts.
- Accepts both numeric codes or their human readable equivalents for the
domain and contractor type arguments.
- Updates the help command to list the available domain types and
contractor types.
Example usage:
```
$ cmswww manageuser b89c8363-ae41-4e4f-b574-3ef8963671dc --domain=developer
{
"userid": "b89c8363-ae41-4e4f-b574-3ef8963671dc",
"domain": 1,
}
{}
$ cmswww manageuser b89c8363-ae41-4e4f-b574-3ef8963671dc --domain=1
{
"userid": "b89c8363-ae41-4e4f-b574-3ef8963671dc",
"domain": 1,
}
{}
```
I also snuck in a update to newinvoice help message that adds
documentation for the expected csv …
=> [cms] Update manageuser command.

mdstream/mdstream.go, politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/convert.go, politeiawww/dcc.go, politeiawww/invoices.go, politeiawww/proposals.go
This diff adds a RecordStatusChangeV2 to the mdstream package and
updates politeiawww to use the RecordStatusChangeV2 mdstream.
RecordStatusChangeV2 adds a Signature field, which was erroneously left
out of V1. The status change signature was being included in the
politeiawww API call correctly and was being validated by politeiawww
correctly, but was not being saved to gitbe since it was missing from
the V1 mdstream. This diff fixes that.
No politeiawww API changes were required since the API was already
including the signature correctly.
=> multi: Add RecordStatusChangeV2 mdstream.

politeiawww/cmsaddresswatcher.go, util/paywall.go
This PR fixes util.FetchTx so it properly only returns the requested txid Defails instead 
of all txs related to the provided address.  
Also includes some clean up and improved error handling
=> [cms] Fix util.FetchTx and addresswatcher cleanup

politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/cmsdatabase/database.go, politeiawww/config.go, politeiawww/convert.go, politeiawww/www.go
This PR now allows for rebuilding of the cmsdb based on db version 
changes.  
Adding the `--buildcmsdb` option to politeiawww will no drop relevant tables
in cmsDB (invoices, line items, payments, invoice changes and dccs).  Then 
it will take all of the records and metadata currently stored in the backend's cache
and rebuild the tables from that information.
=> [cms] Rebuild cmsDB from records cache

politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/convert.go, politeiawww/invoices.go
Because subcontractors may have different rates than the supervisor or other subcontractors within the same group we needed to add the ability to have differing subrates per lineitem.
This was pretty minor change.  Just added a new field to the line item database table and updated the various conversions and payout calculations.
=> [cms] Add SubRate to Invoice line items

politeiawww/www.go
This fixes an issue with invoices after rebuilding of not having user id information (which is used for db queries) with the invoices.  
This caused users not to be able to see their invoices, or admins seeing user invoice lists.
=> [cms] Obtain userid for invoice rebuild

decredplugin/decredplugin.go, politeiad/backend/gitbe/decred.go, politeiad/cache/cockroachdb/decred.go
This diff removes the StartVote from the decredplugin VoteResultsReply.
The StartVote returned by the VoteResults command was never actually being
used by any of the calling functions and the StartVote data is already
returned in the VoteDetails command so having it in the VoteResultsReply
is unnecessarily redundant.
=> multi: Update decredplugin VoteResults command.

politeiawww/convert.go
This diff fixes a bug that was causing errors to be logged for valid
proposal mdstreams that are not required to created a ProposalRecord.
=> politeiawww: Fix convertPropFromCache bug.

tlog/tclient/tclient.go, tlog/tserver/anchor.go, tlog/tserver/tserver.go, tlog/util/util.go
This diff moves tlog specific util functions into a tlog util package.
The is necessary because our CLI tools that used any functions from the
global util package, such as the politeia tool, could no longer use the
-v flag. Trying to use the -v flag would cause a runtime panic due to
the glog package already declaring it. The depenecy tree to get to the
glog package was as follows:
github.com/decred/politeia/util
github.com/decred/politeia/tlog/api/v1
github.com/google/trillian
github.com/golang/glog
Moving the tlog util functions into a tlog util package fixes this.
=> tlog: Create a tlog util package.

politeiawww/invoices.go
Previously was allowing months less than 1 to be submitted (0/2020 for example)
=> [cms] Add basic validation for input month

politeiawww/api/cms/v1/v1.go, politeiawww/dcc.go
To easily show the supporting usernames on the DCC Details page in the GUI we need to also return the list of usernames (instead of just the userids).
=> [cms] Add support/opposing usernames in DCC Record

politeiawww/dcc.go
This allows for existing contractors to be submitted for DCC's for the following situation:
A previously accepted marketing/events contractor has worked on learning Dev and
needs to be approved via DCC to bill for the new Development work.
=> [cms] Allow direct and subs for issuance

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/cmsusers.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/shared/client.go, politeiawww/cmsuser.go, politeiawww/user/cms.go, politeiawww/user/cockroachdb/cms.go, politeiawww/userwww.go
This PR adds a new authenticated route to all users to request a list of users in various domains and/or contractor types.   If no domain or contractor type is given then the full list of contractors is provided.  I don't believe any of the returned information should be considered private.
This is required for things like dropdowns and other UX improvements for DCC submissions.
=> [cms] Add CMS Users Request

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/cmswww/help.go, politeiawww/cmd/cmswww/manageuser.go, politeiawww/cmd/piwww/help.go, politeiawww/cmd/piwww/piwww.go, politeiawww/cmd/shared/censorcomment.go, politeiawww/cmd/shared/client.go, politeiawww/cmd/shared/manageuser.go, politeiawww/cmd/shared/shared.go, politeiawww/cmsuser.go, politeiawww/cmswww.go, politeiawww/userwww.go
This PR re-adds the legacy manage user endpoint and moves the newly added
CMS specific manage user endpoint to `/admin/manage/cms`
=> [cms] Re-add legacy mange user endpoit

politeiad/cache/cache.go, politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/decred.go, politeiad/cache/cockroachdb/models.go
This diff adds the ProposalGeneralMetadata table to the cache in order
to make the ProposalGeneral mdstream queryable. This mdstream was
previously being stored in the cache as a MetadataStream with an encoded
payload.  It still is stored as a MetadataStream, but a
ProposalGeneralMetadata record will now exist for the most recent
proposal version. This will be required once RFP proposals go live so
that the link between proposals can be queried.
The diff also required adding hooks for cache plugins so the the
ProposalGeneralMetadata table could be updated properly when a proposal
is submitted or edited.
=> cache: Add ProposalGeneralMetadata table.

politeiawww/user/user.go
There was a bug in the early version of politeia that could cause some
users to have multiple inactive identities and apparently also multiple
active identities. The fix for multiple inactive identities was merged a
while back. This diff provides a fix for users who have multiple active
identities.
=> user: Fix identity bug.

politeiawww/cmd/politeiawww_dbutil/README.md, politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
This diff adds a command to politeiawww_dbutil that verifies that a
user's identities do not violate any politeia rules. Any invalid
identities that are found are deactivated.
The bug that caused these invalid states has already been fixed and the
code has been updated to automatically deactivate invalid identities.
This command allows us to do it manually until the code changes have
been deployed to production.
=> dbutil: Add verifyidentities command.

politeiawww/cmd/shared/client.go
The `cmsmanageuser` command was not working properly. This diff fixes it.
=> [cms] Fix cmsmanageuser command on cmswww cli

go.mod, politeiawww/cmswww.go, politeiawww/middleware.go, politeiawww/politeiawww.go, politeiawww/sessions.go, politeiawww/sessionstore.go, politeiawww/testing.go, politeiawww/user/cockroachdb/cockroachdb.go, politeiawww/user/cockroachdb/models.go, politeiawww/user/localdb/localdb.go, politeiawww/user/localdb/localdb_test.go, politeiawww/user/user.go, politeiawww/userwww.go, politeiawww/userwww_test.go, politeiawww/www.go
This diff moves user sessions from a session store backed by the
filesystem to a session store backed by the userdb. It implements a
custom sessions store that satisfies the gorrilla/sessions Store
interface. 
Moving the session store to the userdb accomplishes a few things:
1. Allows us to manually invalidate sessions. An example being when a
user changes their password we can invalidate their sessions on all
other devices. This was not previously possible with the filesystem
store implementation. 
2. Removes one of the blocking issues that is preventing us from running
multiple politeiawww instances.
This diff does not fix issues #647 or #650. It is a prerequisite for
fixing those issues, but those issues will be fixed in the next PR.
=> politiawww: Move sessions to userdb.

politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/invitenewuser.go, politeiawww/cmsuser.go
This is the beginnings of the ability to add "one-off" contractors that are allowed to submit invoices without having to proceed through the full DCC process as a normal regularly billing contractor would.  
The current use-case that comes to mind for these users are bug bounty folks.  While they need the ability to bill for work complete, they are not considered to be full members of our contractor community and with that will come a reduce amount of rights and access.
=> [cms] Add Temporary contractor type

politeiawww/api/cms/v1/v1.go, politeiawww/dcc.go
Previously malformed DCCs were being returned and appended to the getDCCs response.
Instead malformed detections will be logged and skipped from the response.
=> [cms] Return error when malformed DCC detected

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/api/www/v2/api.md, politeiawww/proposals.go
This diff fixes a bug in the vote results route that was causing a 500
to be returned when the vote results were requested for a proposal whose
voting period had not yet been started.
=> politeiawww: Fix vote results bug.

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/cmswww/manageuser.go, politeiawww/cmd/cmswww/proposalowner.go, politeiawww/cmd/shared/client.go, politeiawww/cmsuser.go, politeiawww/cmswww.go, politeiawww/user/cms.go, politeiawww/user/cockroachdb/cms.go, politeiawww/user/cockroachdb/models.go
This allows administrators to add proposal "ownership" to a user information.  
This will be used in an upcoming request that will let proposal owners receive a report of 
users and line items that have been billed against their proposal.
=> [cms] Add proposalsOwned to CMSUsers information

politeiawww/api/cms/v1/v1.go, politeiawww/cmsaddresswatcher.go, politeiawww/invoices.go
This PR is the first step into limiting the access for users that have been given the "temp" contractor qualifier.  
When a temp contractor has an invoice moved to 'paid' status this will update their contractor type to the newly added "TempDeactivated."
Then if this temp contractor would like to submit another, they must first get approval from an administrator who will update their contractor type back to Temp in the admin user panel.
=> [cms] Update Temp to Deactivated on paid invoice

politeiawww/www.go
Previously, we were receiving 403s frequently with cmswww and piwww.  
This matches what have set for sessionMaxAge in sessions.go
=> www: Set csrf.MaxAge to 1 Day

politeiawww/user/cockroachdb/cockroachdb.go, politeiawww/user/localdb/localdb.go, politeiawww/user/user.go, politeiawww/userwww.go
Closes #647
This diff makes the following changes.
ChangePassword - on success, delete all existing sessions for the logged
in user except for the current session.
VerifyResetPassword - on success, delete all existing sessions for the
user whose password was reset.
=> politeiawww: Delete sessions on password change.

politeiad/backend/backend.go, politeiad/backend/gitbe/decred.go, politeiad/backend/gitbe/gitbe.go, politeiawww/cmd/piwww/testrun.go
This diff updates the gitbe decred plugin to use gitBackEnd methods for
reading and writing to disk instead of doing it directly.
=> gitbe: Remove plugin disk reads and writes.

politeiawww/api/cms/v1/v1.go
As mentioned by Elian on [Matrix contractor's chat](https://matrix.to/#/!zUNclAsjlDCTJWzPVS:decred.org/$15861818648444uYNui:decred.org?via=decred.org), the DCC statement is now allowing new lines, returning a _The DCC sponsor statement is malformed_ exception.
Since the DCC is something pretty critical, I think that, by adding this, the DCC usability will increase and we will be able support Markdown for DCC statements.
=> [www] Allow skipping lines on DCC Statement

politeiawww/api/cms/v1/v1.go, politeiawww/cmswww.go
This commit adds the DCC Statement supported chars to the `/policy` response.
https://github.com/decred/politeia/blob/635e23f1641262ed7bb0555d2f8d13454ecd7234/politeiawww/api/cms/v1/v1.go#L243-L245
=> [cms] Add DCC Statement supported chars to policy response

politeiawww/user/cockroachdb/cms.go
Previously any edit or manageuser request that didn't populate fields would set the others to empty.
=> [cms] Only update cms user fields when populated

politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/cmswww/proposalbilling.go, politeiawww/cmd/shared/client.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/database.go, politeiawww/cmswww.go, politeiawww/convert.go, politeiawww/invoices.go
Requires: #1135 
This request allows administrators and proposal "owners" to review all 
line items that have been billed to the given proposal.  
All other private user information for the invoices is hidden (name, address, etc),\
so just the raw information about a line item is given.
=> [cms] Add ProposalBilling request

politeiawww/user.go
Close #1042 
Set `u` user was being shadowed so was considered `nil` in any check below.
=> [www] Fix users request with pubkey

politeiawww/user.go
Closes #650 
Seems like a rare instance, but it makes sense to also reset the token/expiry if they are possibly set when a user changes their passphrase.
=> [www] Reset Password Token/Expiry on password change

mdstream/mdstream.go, politeiad/cache/cockroachdb/decred.go, politeiad/cache/cockroachdb/models.go, politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/cmswww/editinvoice.go, politeiawww/cmd/cmswww/newdcc.go, politeiawww/cmd/cmswww/newinvoice.go, politeiawww/cmd/piwww/editproposal.go, politeiawww/cmd/piwww/inventory.go, politeiawww/cmd/piwww/newproposal.go, politeiawww/cmd/piwww/piwww.go, politeiawww/cmd/piwww/testrun.go, politeiawww/cmd/shared/shared.go, politeiawww/convert.go, politeiawww/events.go, politeiawww/proposals.go, politeiawww/proposals_test.go
This diff seperates out proposal metadata from the proposal files when
submitting a proposal. The `NewProposal` and `EditProposal` routes now
contain a `Metadata` field that allows the client to submit user
specified metadata about the proposal. The metadata is included in the
signed merkle root of the proposal.
The only user defined proposal metadata up to this point has been the
proposal name. It is inserted into the `index.md` file as the first line
of the file and parsed out by the server. This is a very hacky way to
accomplish passing in user defined metadata.
The politeia RFP work adds additional user defined metadata fields
(`LinkTo`, `LinkBy`) to a proposal and cms is also getting to the point
where additional user defined metadata fields are required in an
invoice. We didn't want …
=> multi: Add metadata to proposal submissions.

politeiad/cache/cockroachdb/decred.go
A sanity check in the cache decred plugin was causing issues with cms so
it needed to be taken out until we've split up the plugins by
functionality.
=> cache: Remove decredplugin sanity check.

politeiawww/templates.go
Link wasn't rendering without double bracket.
=> [cms] Typo in DCC support template

politeiawww/cmd/politeiawww_dbutil/README.md, politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
This diff adds a setemail command to `politeiawww_dbutil`. A user's
email address can be updated manually using this command.
`$ politeiawww_dbutil -cockroachdb setemail username newemail@example.com`
**politeiawww must be restarted after the email address has been updated
so that the email address memory cache gets rebuilt. politeiad is fine
and does not need to be restarted.**
=> dbutil: Add setemail command.

decredplugin/decredplugin.go, politeiad/backend/gitbe/decred.go, politeiad/backend/gitbe/gitbe.go
This diff adds the vote duration min/max as a plugin setting to the
gitbe decred plugin. This allows the min/max to be lowered when on
testnet to make testing easier.
politeiawww already allows this.
=> gitbe: Set vote duration as a plugin setting.

cmsplugin/cmsplugin.go, politeiad/backend/gitbe/cms.go, politeiad/backend/gitbe/gitbe.go, politeiad/backend/gitbe/gitbe_test.go, politeiad/cache/cockroachdb/cms.go, politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/convert.go, politeiad/cache/cockroachdb/models.go, politeiad/config.go, politeiad/politeiad.go, politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/activevotes.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/cmswww/setdccstatus.go, politeiawww/cmd/cmswww/startvote.go, politeiawww/cmd/cmswww/votedcc.go, politeiawww/cmd/cmswww/votedetails.go, politeiawww/cmd/shared/client.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/cmsdatabase/database.go, politeiawww/cmsuser.go, politeiawww/cmswww.go, politeiawww/convert.go, politeiawww/dcc.go, politeiawww/www.go
This adds the final portion laid out in the stakeholder approved proposal:
https://proposals.decred.org/proposals/fa38a3593d9a3f6cb2478a24c25114f5097c572f6dadf24c78bb521ed10992a4
When a DCC proposal for either issuance or revocation is deemed "contentious,"
administrators may now start a "Debate." This will then allow all currently active and valid
contractors to submit a vote to determine the final outcome of any given DCC proposal.
When the status for a DCC is updated to "debated" a current snapshot of the user base
is taken and the "weights" of each user's vote is determined. Currently, the weight is
simply the amount of billed hours over the previous 6 months of invoices that have been paid out.
We can use this raw amount however we like to best tabulate the results in a future PR.
As …
=> [cms] Add All Contractor Vote for contentious DCCs

politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/README.md, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/cmswww/help.go, politeiawww/cmd/cmswww/invitenewuser.go, politeiawww/cmd/cmswww/newdcc.go, politeiawww/cmd/cmswww/newinvoice.go, politeiawww/cmd/cmswww/register.go, politeiawww/cmd/cmswww/setdccstatus.go, politeiawww/cmd/cmswww/setinvoicestatus.go, politeiawww/cmd/cmswww/testrun.go
This requires #1104.
This diff adds a testrun command to cmswww.
The command runs through the DCC process and the DCC vote process. Its
meant to help with testing PRs and serve an informal reference
implementation to document how some of the cms processes work. It can be
expanded in the future to include other CMS routes.
```
$ cmswww testrun admin@example.com password
Running pre-testrun validation
Running testDCC
create existing contractors
create a user to be the nominee
create a DCC for the nominee: 8b5c987f5822613da6d3eef4f8ed8fe2350aab6b17f9a609bdd6c099a0a5a511
comment on the DCC
support the DCC
approve the DCC
create a user to be the nominee
create a DCC for the nominee: 5e58d92a3d2804a3bb4d38438cab16ff7e03933949f1b438919bf47e09257f94
oppose the DCC
reject the DCC
testDCC success! …
```
=> cmswww: Add testrun command.

politeiad/cache/cockroachdb/models.go
The record token size is going to be changing in the future with the new
tlog backend. This diff removes the size requirements that the cache
tables previously had for tokens.
=> cache: Remove token size requirement.

politeiawww/dcc.go
This fixes a couple of bugs that were recently seen.  
- Correctly send the sponsor user id instead of the approving admin's user id.
- Make sure to check that the sponsor user is a supervisor when validating a sub-contractor issuance.
=> [cms] DCC issunace and validatioon fix

politeiawww/email.go
As part of the efforts to increase user privacy and security, we changed the local browser storage keys from being the users email to his username/uuid. (pgui PR https://github.com/decred/politeiagui/pull/1903)
This diff adds the username to the verify user email link, so that we can properly retrieve his signing key on the frontend, without disclosing any personal information.
=> [www] Add username to email verification link

decredplugin/decredplugin.go, politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/decred.go
This diff fixes two different bugs in the decred plugin linkedfrom
command.
1. Passed in tokens were being returned in the reply map even if they
did not correspond to an actual proposal.
2. The query was searching for all proposals that had their linkedto
field set to the provided token. The cache stores all version of a
proposal so the query was returning all versions when it should have
just been returning the most recent version.
=> cache: Fix LinkedFrom bugs.

politeiawww/comments.go, politeiawww/proposals.go, politeiawww/proposals_test.go, politeiawww/user.go
This diff adds a check on the routes that receive a proposal token. This check verifies if the token is valid and not in the prefix short form.
Closes #1206
=> Return proper error when using token prefix

politeiawww/cmd/shared/login.go
Previously, expired CSRF tokens weren't being updated on subsequent Login attempts, so after a day the user would need to clear out their .*www/data/ directory to be able to login.
=> [www/cms] Add Version request on Login

politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/database.go, politeiawww/invoices.go
There was a bug discovered that line items that were being remove via Edit were still remaining in the cmsdatabase due to UpdateInvoice not fully updating the sub tables within.  To handle all situations we now just remove all line item rows for a particular invoice before the update occurs.  This will ensure that when the UpdateInvoice occurs only the ones included in the edit will remain.
=> [cms] Remove invoice line items on EditInvoice

politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/invoicedetails.go, politeiawww/cmd/cmswww/testrun.go, politeiawww/cmd/shared/client.go, politeiawww/invoices.go
Now administrators will be able to view all the versions of an invoice after edits completed by a contractor.  
This works in the exact same manner as ProposalDetails request.  It's an optional field, when populated, request that version of the token provided.  If empty it will the return the most recent change.
=> [cms] Add Version to InvoiceDetails request

politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/piwww/editproposal.go, politeiawww/cmd/piwww/help.go, politeiawww/cmd/piwww/newproposal.go, politeiawww/cmd/piwww/piwww.go, politeiawww/cmd/piwww/proposaldetails.go, politeiawww/cmd/piwww/testrun.go, politeiawww/cmd/piwww/userproposals.go, politeiawww/cmd/piwww/vettedproposals.go, politeiawww/cmd/shared/batchproposals.go, politeiawww/cmd/shared/shared.go, politeiawww/cmd/shared/tokeninventory.go, politeiawww/cmswww.go, util/json.go
This allows us to request `https://cms.decred.org/api/v1/proposals/tokeninventory` and `https://cms.decred.org/api/v1/proposals/batch` to avoid a cross site request that causes security issues.  This simple passes that request through via the API to the relevant proposals site (mainnet/testnet).
=> [cms] Add passthroughs for proposals requests

politeiad/backend/gitbe/cms.go, politeiad/backend/gitbe/decred.go, politeiad/backend/gitbe/gitbe.go
This diff fixes the UnvettedExists gitbe method. It was previously
checking the unvetted repo for the record on the master branch. This is
incorrect. Unvetted records are stored in the unvetted repo as branches.
Once they become vetted records then they are merged into master. The
UnvettedExists method now checks the unvetted repo branches for the
record.
It also updates a few plugin calls, which were calling the
UnvettedExists method when they should have been calling the VettedExits
method. This was not causing any issues because the UnvettedExists method
was actually returning whether the vetted record existed.
=> gitbe: Fix UnvettedExists bug.

politeiad/cache/cockroachdb/decred.go, politeiawww/politeiawww.go, politeiawww/proposals.go, politeiawww/www.go
This diff implements three performance improvements for the vote results cache table.
- Keep track of the best block used to update the vote results table, and only update it again if a new best block is received.
- `LoadVoteResults` command on www startup.
- `LoadVoteResults` command whenever a new best block comes along in dcrdata ws connection.
closes #1221
=> cache: Performance improvements for vote results

politeiad/cache/cockroachdb/cockroachdb.go, politeiad/cache/cockroachdb/decred.go, politeiad/cache/cockroachdb/models.go, politeiawww/proposals.go
This fixes a bug introduced by PR #1226, where VoteResults table never got loaded due to a wrong value comparison in `voteResultsMissing`.
This also fixes the way we store the best block reference. In #1226 we stored it in-memory, which leads to problems since www and d each run their own instance of cdb. Therefore, this diff now stores the best block reference as a record value in the cache, on a generic key-value table.
=> cache: Store best block in cache instead of in-memory

politeiad/cache/testcache/decred.go, politeiad/testpoliteiad/decred.go, politeiad/testpoliteiad/testpoliteiad.go, politeiawww/events.go, politeiawww/proposals.go, politeiawww/proposals_test.go, politeiawww/testing.go
This diff aims to increase test coverage to functions related to the RFP process recently merged in the repo. Besides adding proposal tests, this diff moves test helper functions (`new...`) to `testing.go` for better modularity.
Tests added:
```
TestValidateProposalMetadata
TestValidateAuthorizeVote
TestValidateStartVote
TestProcessAuthorizeVote
TestProcessStartVoteV2
TestProcessStartVoteRunoffV2
```
Smaller tests added:
```
TestIsRFP
TestIsRFPSubmission
TestIsProposalAuthor
TestVoteIsApproved
TestValidateVoteOptions
TestValidateVoteBit
TestValidateAuthorizeVoteStandard
TestValidateAuthorizeVoteRunoff
TestValidateStartVoteStandard
TestValidateStartVoteRunoff
```
If any of the smaller tests added are deemed to make the code brittle and hard to change, let me know and I can remove or modify …
=> tests: Add unit tests to RFP-related functions

politeiad/backend/gitbe/decred.go
This diff fixes a bug that was recently introduced when the gitbe
UnvettedExists call was fixed. The decredplugin post-edit hook was
trying to flush the comments on unvetted proposals, but validation was
failing because comments can only be made on vetted proposals.
=> gitbe: Fix decredplugin post edit hook bug.

politeiawww/proposals.go, politeiawww/proposals_test.go
This diff fixes a bug that was causing proposal edits to be rejected if
the linkto deadline had expired. New RFP submissions should be rejected
once the linkby deadline has expired, but edits to existing submissions
are allowed.
=> politeiawww: Fix linkto expiration bug.

politeiawww/proposals_test.go
This diff adds a check to see if we expect a error on the test, and receive a err == nil instead. Before this diff, the tests passed without prompting the error, leading to undesired behaviour.
=> tests: Add mising case to RFP tests

politeiawww/proposals_test.go
This diff removes a obsolete test case that is causing travis to fail on the repo.
edit: it now adds this test case, seeing if the submission deadline of a RFP proposal is expired, to its correct place, in `TestProcessNewProposal`.
=> tests: Move expired deadline test case to correct place

politeiawww/cmd/piwww/editproposal.go, politeiawww/cmd/piwww/piwww.go, politeiawww/proposals.go
This diff introduces new flags: `usemd` & `linkby` to the editproposal command & adjusts the help message accordingly.
When `usemd` provided existing metadata then used as starting point and can be overwritten by providing specific value flags.
In addition, it prevents users from misusing the flags and throwing new errors when:
- `--random` is used with `--name`.
- `--rfp` is used with `--linkby`.
Closes #1196
=> piwww: Update editproposal command.

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/cmd/piwww/policy.go, politeiawww/politeiawww.go
This diff adds `MinVoteDuration` & `MaxVoteDuration` fields to `/policy`
route reply struct.
=> politeiawww: Add Min/MaxVoteDuration to policy

decredplugin/decredplugin.go, politeiad/backend/backend.go, politeiad/backend/gitbe/cms.go, politeiad/backend/gitbe/decred.go, politeiad/backend/gitbe/gitbe.go, politeiad/cache/cache.go, politeiad/cache/cockroachdb/decred.go, politeiad/politeiad.go
When the cache needs to be rebuilt it would use the backend `Inventory`
call to retrieve the full record inventory, including all versions of
every record, and store them in memory. This was a temporary solution
that has now started to become a problem due to the amount of data that
exists on the mainnet proposals site.
This diff adds two calls, `UnvettedTokens` and `VettedTokens` to the
backend interface that return the tokens of all unvetted and vetted
records, respectively. When the cache gets rebuilt it uses these calls
to fetch the record tokens then retrieves a single record at a time to
insert into the cache. The decred plugin cache rebuild process was
also updated to do the same thing. It retrieves the decred plugin data
and builds the decred plugin cache for each record …
=> politeiad: Update cache build process.

politeiawww/user/cockroachdb/cms.go
Previously user details were returning proposalsOwned: [""] for when nothing was populated there.
=> [cms] Return empty slice for proposals owned

politeiawww/cmd/piwww/testrun.go
This diff adds the RFP process to `piwww testrun` command.
It covers the following commands:
- Create RFP
- Make RFP public
- Authorize it for vote
- Start vote on RFP
- Cast RFP votes
- Wait until RFP votes is done
- Create 4 RFP submissions:
- 1 Unreviewed
- 2 Public
- 1 Abandoned
- Start runoff vote
- Cast first public submission votes
- Wait until runoff vote is done
- Ensure first submission was approved.
And the following failures/edge cases as @lukebp suggested:
- Attempting to submit an RFP submission before the RFP vote has been approved.
- Submit an RFP, have the vote fail, attempt to submit an RFP submission to failed rfp.
- Attempting to vote on the abandoned proposal submission during runoff vote.
Closes #1190
=> piwww: Add RFP process to testrun command.

politeiawww/cmd/piwww/testrun.go
This commit ditchs an extra update user key call.
In addition, it improves the logging while voting
be adding the bestblock/proposal.endheight to the
log.
=> politeiawww: cleanup testrun call

README.md
This diff updates `cockroach start` command in README which was 
replaced in cockroach v20.* with `cockroach start-single-node`.
=> README: update `cockroach start` command

politeiawww/proposals_test.go
This diff cleans up the proposals tests and removes a unecessary verification of the received error context, which was being hard coded on the test.
=> tests: remove hardcoded error context from proposals test

politeiawww/cmswww.go, politeiawww/invoices.go
When issuing a batch proposals pass through request for ProposalBillingSummary on mainnet, too many proposals were being requested.  We must only request below the ProposalListPageSize amount.  
So this PR chops up the list of approved invoices returned from the TokenInventory list into chunks that abide by max list page size.
=> [cms] Fix batch proposals error

politeiawww/api/cms/v1/api.md, politeiawww/api/cms/v1/v1.go, politeiawww/cmd/cmswww/admininvoices.go, politeiawww/cmd/cmswww/cmswww.go, politeiawww/cmd/shared/client.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/database.go, politeiawww/cmswww.go, politeiawww/convert.go, politeiawww/invoices.go
This PR changes the existing `AdminInvoices` request to the more open `Invoices`.  
`Invoices` now is allowed to be accessed by any user instead of just administrators.  Users may access invoices from their set domain.  Private information concerning payouts, addresses, location etc is scrubbed if the requesting user isn't the invoice owner or an administrator.
This PR also adds 3 new params to the Invoices request. StartTime, EndTime and UserID.
- UserID if set will return only invoices that were created by that UserID.
- StartTime and EndTIme will return invoices in the range given. But note that these params can only be used when Month/Year are empty otherwise an Error will be returned.
=> [cms] Update AdminInvoices to Invoices

politeiawww/cmsaddresswatcher.go, politeiawww/politeiawww.go, politeiawww/www.go, wsdcrdata/wsdcrdata.go
This diff makes a few improvements to the wsdcrdata package:
- If client intialization fails due to being unable to make a dcrdata
connection, the client is still returned. This allows the caller to
decide whether reconnection attempts should be made or if the
application should exit.
- A `StatusT` type was added to the wsdcrdata client that tells whether
the websocket connection is open, attempting to reconnect, or has been
shutdown. This allows the caller to determine the correct course of
action for the different statuses.
- Any new subscribe/unsubscribe events that are attempted while the
client is in the process of reconnecting to dcrdata are recorded and
then replayed in the order in which they were received once the new
connection has been established.
=> wsdcrdata: Improve reconnection handling.

politeiawww/cmsaddresswatcher.go, politeiawww/www.go
This PR adds standardized reconnect logic as used in the WS handler for politeiawww.  
Closes #1272
=> [dcrdata] Add retry loop for wsDcrdata connection

politeiawww/invoices.go
this PR closes #1277 which reported an incomplete info response from invoice details call.
=> [cms] fix: show complete invoice details for admin or owner

politeiawww/invoices.go
This diff adds validators for invoice SubRate and SubUserIDs on labor invoice lineitems. Basically, a Labor type lineitem shouldn't be allowed to receive both subrate and subuserid info.
=> cms: validate subrate and subuserid for labor invoice lineitems

cmsplugin/cmsplugin.go, politeiad/backend/gitbe/cms.go, politeiad/backend/gitbe/gitbe.go, politeiad/cache/cockroachdb/cms.go, politeiawww/cmd/cmswww/testrun.go, politeiawww/dcc.go
This diff removes the remaining DCC references to the cache and now directly requests the
vote information from the gitbe.  This clears the way for easier implementation of tlog
since it will no longer be using the cache as we have it now.
=> [cms] Replace DCC cache usage with direct gitbe implementation

politeiawww/cmsuser.go, politeiawww/cmsuser_test.go, politeiawww/testing.go, politeiawww/user/localdb/cms.go, politeiawww/user/localdb/localdb.go
This diff adds the leveldb implementation for userdb plugins for
cms.  Now this can be used for testing infrastructure without
needing to bring up a full cockroachdb in CI.
Along with plugin support for New/UpdateCMSUser and CMSUserByID,
there is also added tests for InviteNewUser and RegisterUser for
cms.
=> [cms] Add cms plugin support to user leveldb implementation

go.mod, politeiawww/user/cockroachdb/cockroachdb_test.go
This diff adds tests to the cockroachdb implementation of the user database. It uses the library `go-sqlmock` to mock a cdb connection and data. With it we are able to test if the expected SQL query got properly executed for a given db method, as well as transaction steps such as `tx.Commit()` and `tx.Rollback()`, and type checking parameters in the query.
All SQL related methods in userdb were tested:
```
UserNew
UserUpdate
UserGetByUsername
UserGetById
UserGetByPubKey
UsersGetByPubKey
AllUsers
SessionSave
SessionGetByID
SessionDeleteByID
SessionsDeleteByUserID
```
=> tests: Add userdb test infrastructure

politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
This diff changes the approach on `politeiawww_dbutil` to use the user.Database interface instead of the *leveldb.DB Database object.
Also, changes the proposalMetadata to use the correct one imported from mdstream package
Closes #1241
=> dbutil: use user database interface

politeiawww/convert.go, politeiawww/invoices.go
An incorrect userID was being used to pull user information, therefore leading to invoices not being skipped as expected.
Also filter out PaymentAddress from returned invoice input
=> cms: Fix domain check for invoices route

politeiawww/cmd/politeiawww_dbutil/README.md, politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
This adds a basic reset of TOTP credentials to the politeiawww_dbutil tool.  This should only be necessary for extreme cases,
but will be more convenient than have to alter the db by hand and more secure than having an admin command available in www.
=> totp: Add reset totp to admin db tool

politeiawww/cmd/piwww/newuser.go, politeiawww/cmd/piwww/sendfaucettx.go, politeiawww/cmd/piwww/testrun.go, politeiawww/cmsaddresswatcher.go, politeiawww/cmswww.go, politeiawww/comments.go, politeiawww/dcc.go, politeiawww/decred.go, politeiawww/invoices.go, politeiawww/paywall.go, politeiawww/plugin.go, politeiawww/politeiawww.go, politeiawww/prices.go, politeiawww/proposals.go, politeiawww/proposals_test.go, politeiawww/user.go, politeiawww/userwww.go, politeiawww/www.go, util/paywall.go
This uses the http request's context while processing.  If a visitor closes the http connection, we should stop processing.
=> multi: add context to multiple APIs

politeiad/cache/cockroachdb/decred.go
The best block function should not return an error when the cached best
block value does not exist yet. This is expected on fresh installs.
=> cache: Fix best block bug.

politeiawww/cmd/piwww/newuser.go, politeiawww/cmd/piwww/sendfaucettx.go, politeiawww/cmd/piwww/testrun.go
The additional argument in NewUserCmd and SendFauctTxCmd Execute was not allowing the commands to be properly called on cli.
=> piwww: Fix context usage for PayWithTestNetFaucet

politeiawww/cmsdatabase/cockroachdb/encoding.go, politeiawww/cmsdatabase/cockroachdb/models.go, politeiawww/invoices.go
Previously on cms build from records, line items were not properly being keyed so the differing versions weren't being seen.
Also includes a fix for retaining invoice versions after editing.  Previously db entries were being updated, but with the removal of the cache we actually want to start storing all version of the invoices in the db and only add new entries instead of updating rows.
=> [cms] Add LineItemKey so versions are properly seen

politeiawww/cmd/politeiavoter/README.md, politeiawww/cmd/politeiavoter/config.go, politeiawww/cmd/politeiavoter/politeiavoter.go, politeiawww/cmd/shared/client.go, politeiawww/cmd/shared/config.go
Requires: https://github.com/decred/dcrwallet/pull/1867
This allows both piwww and politeiavoter to communicate with dcrwallet via grpc.  
One must use https://github.com/decred/dcrd/tree/master/cmd/gencerts to create a fresh keypair (default: client.pem and client-key.pem) at the appdata directory of either piwww or politeiavoter (default: ~/.piwww or ~/.politeiavoter respectively).  Then they must also concat the contents of client.pem to their clients.pem file under choosen dcrwallet appdata directory.
=> cmd: Add client certs for gRPC dcrwallet changes

politeiawww/cmd/politeiavoter/config.go, politeiawww/cmd/shared/config.go
This changes the --cert and --key flags to be named --clientcert and
--clientkey, to more consistently match other Decred tooling (e.g.
dcrctl).
=> politeiavoter: Use consistent long flag names

politeiawww/cmd/politeiavoter/config.go
This diff replaces the existing cleanAndExpandPath function with the
function from util, which is more comprehensive, and adds in cleaning
the dcrwallet client cert paths.
=> politeiavoter: Clean dcrwallet cert paths.

politeiawww/api/cms/v1/v1.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/convert.go
This fixes a few lingering issues with the proposal billing request:
1) Now only the most recent version of the invoices' line items will be returned.
2) Add Contractor Rate to the ProposalBilling Line item object so calculations can be made.
=> [cms] Fixes for proposal billing request

politeiawww/api/www/v1/api.md, politeiawww/api/www/v1/v1.go, politeiawww/cmd/shared/login.go, politeiawww/politeiawww.go, politeiawww/totp.go, politeiawww/totp_test.go, politeiawww/user.go, politeiawww/user/user.go, politeiawww/user_test.go
~Requires https://github.com/decred/politeia/pull/1210~
This PR adds the ability to have users Login with TOTP if they have verified a TOTP Secret.
Currently, if a user has verified a TOTP then they will be told they need a code to be entered along with their username/password.  This code must match before the hashed password is compare against what is saved in the database.
According to the implemented security measures here, we will only allow 2 failed TOTP codes to be submitted for a givien epoch.  Any subsequent request will fail with a `ErrorStatusTOTPWaitForNewCode`
=> [totp] Add TOTP Code check in Login

politeiawww/cmsaddresswatcher.go, politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/cmsdatabase/database.go, politeiawww/convert.go, politeiawww/invoices.go
There were some issues that were revealed about invoice payment record keeping.
First, payments were not being properly given metadata record updates when checked
during historical payments.  So now on start up we do a quick check on invoice payments
that have been set to paid, if they don't have a proper entry then they are given a metadata
update.  
This also fixes some invoice key/token issues when updating invoice payments.
=> [cms] Fix Invoice payment check and records

politeiawww/codestats.go, politeiawww/codetracker/codetracker.go, politeiawww/codetracker/github/update.go, politeiawww/config.go, politeiawww/www.go
To allow for retrieving pull requests from other organizations we are going to change the config to only pull repos but expecting them to have the organization on the front like "decred-politeia"  or "alexlyp-politeia"
Also includes an additional config option boolean to avoid the pull request sync on start up.  That means it will only be run as scheduled on the first of the month.
=> [cms] Update config for CMS code stats

politeiad/backendv2/tstorebe/plugins/comments/cmds.go, politeiad/backendv2/tstorebe/tstore/tlogclient.go, politeiad/plugins/comments/comments.go, politeiawww/api/comments/v1/v1.go, politeiawww/client/comments.go, politeiawww/cmd/pictl/cmdcommenttimestamps.go, politeiawww/comments/process.go
This diff updates the comment timestamp commands in politeiawww and
politeiad to differentiate between comment add timestamps and comment
del timestamps. This is required so that the client is able to decode
the timestamp data payload into the correct structure.
=> multi: Break comment timestamps up.

politeiad/README.md, politeiad/backendv2/tstorebe/plugins/comments/cmds.go, politeiad/cmd/politeia/README.md, politeiad/plugins/comments/comments.go, politeiawww/api/comments/v1/v1.go
This diff updates how deleted comments are returned from the politeiad
comments plugin and politeiawww API. The public key, signature, receipt,
and timestamp from the deletion event is now returned so that the
deletion event signature and receipt can be verified by the client.
=> multi: Return comment del signature.

politeiad/backendv2/tstorebe/tstore/record.go
Closes #1383 
When a record is made public the encrypted blobs in the kv store are
re-saved as clear text, but the tlog leaf remains the same since the
record content did not actually change. The backend was only deleting
one of these blobs when a vetted record was being censored. This diff
updates the backend to delete both the encrypted blob and clear text
blob.
=> tstore: Delete vetted record content bug.

politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go, politeiawww/cmd/pictl/cmdvotetestsetup.go
Closes #1382 
This diff removes a testnet code path that allowed a runoff vote to
start prior to the linkby deadline expiring. It was suppose to make
testing easier, but it is causing bugs so its being removed. Having a
testnet code path was a bad idea.
=> ticketvote: Remove testnet linkby path.

politeiawww/user.go
The fields `PaywallAddress`, `PaywallAmount`, and `PaywallTxNotBefore`
were left out of the login reply for some reason, which was causing
issues in the GUI. This diff updates the login reply to include the
fields.
=> politeiawww: Fix login reply bug.

politeiawww/proposals.go
This change is the behavior that decrediton expects from the legacy vote
result route.
=> politeiawww: Fix legacy vote results bug.

politeiad/backendv2/tstorebe/plugins/ticketvote/activevotes.go, politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go
Closes #1381
This diff removes all panics from the active votes cache and replaces
them with graceful failures.
When a ballot is cast the record is locked by the tstore backend, but
this does not apply to the active votes cache which is lazily updated on
read requests. This can lead to a vote being removed from the active
votes cache while another thread is still validating a ballot, causing the
panic code paths to be hit.
This diff is pretty ugly. These concurrency issues will be resolved and
cleaned up for good once a plugin command and all cache updates are
executed using a single kv store transaction.
=> ticketvote: Fix active votes cache bug.

politeiawww/cmd/pictl/cmdlegacytest.go, politeiawww/proposals.go
Multiple legacy routes were previously returning 500s because the legacy
API does not paginate properly in a lot of routes, but the politeiad v2
API expects the requests to be paginated, causing errors to occur.
This diff updates the function that is used to request proposals from
politeiad for the legacy routes to paginate the requests properly. It
also updates the `pictl legacytest` command that tests the legacy routes
to specifically test the pagination issue.
=> politeiawww: Fix legacy pagination bug.

politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go
This diff fixes a bug that was causing the best block in a vote summary
to not be accurate when the summary was being pulled from the cache.
=> ticketvote: Fix summary best block bug.

politeiad/backendv2/tstorebe/tstore/record.go, politeiad/backendv2/verify.go, politeiawww/client/comments.go, politeiawww/client/records.go, politeiawww/client/ticketvote.go, politeiawww/cmd/politeiaverify/ticketvote.go
This diff moves the timestamp verification code from the `tstore`
package to the `backendv2` package to reduce the number of
dependencies that clients must import in order to verify timestamps.
=> politeiad: Move timestamp verify functions.

politeiad/backendv2/tstorebe/tstore/blobclient.go
Not sure whether this is was a typo, it seems that `map` pre-allocation here is not optimal. This PR fixes that.
=> [tstore] optimize map allocation

politeiawww/cmsnotifications.go, politeiawww/email.go, politeiawww/templates.go
Closes #1349 
This PR adds more email reminders for users that have not submitted emails yet for the previously month do so.
Timely submission of invoices will be much more important once the payout from the treasury is fully automated, so further nagging is due.
=> [cms] Add more invoice email notifications

politeiawww/dcc.go
This diff adds a check to make sure there is not already a DCC with the same nominating user.
=> cms: Add check for outstanding DCCs

politeiawww/codestats.go
Previously errors were caught and then subsequent users were not being updated.  This logs errors and continues on to the rest of the users available.  And this should catch to when it should update versus create a new code stats entry.
=> [cms] Fix code stats user update

README.md, politeiad/README.md, politeiawww/README.md
Part of #1393.
This diff updates the politeia, politeiad, and politeiawww READMEs. It
adds full setup instructions for running Politeia.
The READMEs could still need additional documentation on the politeia
architecture, but they are now complete enough that new contributors can
use them to get a full politeia instance up and running.
=> multi: Update READMEs.

politeiawww/api/www/v1/v1.go, politeiawww/politeiawww.go
This pull request is made for [politeiagui issue: Explain how long it takes to update proposal credit balance](https://github.com/decred/politeiagui/issues/2070)
I see the description of field `MinConfirmationsRequired` in `politeiawww/config.Config`: 
```
MinConfirmationsRequired uint64   `long:"minconfirmations" description:"Minimum blocks confirmation for accepting paywall as paid. Only works in TestNet."`
```
But when I check the code of paywall. It seem be working on both Mainnet and Testnet
=> www: Add PaywallConfirmations to policy.

go.mod, politeiad/politeiad.go, politeiad/v1.go, politeiawww/comments/error.go, politeiawww/records/error.go, politeiawww/ticketvote/error.go, util/errors.go
This diff adds the `pkg/errors` module as a dependency and adds error
handling for `pkg/errors` errors. This change is needed because of the
stack trace limitations of the golang stdlib errors.
When politeiad or politeiawww encounters an unexpected error, the error
message and a stack trace are printed to stdout. Listed below is an
example stack trace for an error that occured while attempting to submit
a new record.
```
2021-06-09 16:44:10.281 [ERR] APIS: Stacktrace (NOT A REAL CRASH): goroutine 83 [running]:
runtime/debug.Stack
/usr/local/go/src/runtime/debug/stack.go:24
github.com/decred/politeia/politeiawww/records.respondWithError
/home/luke/go/src/github.com/decred/politeia/politeiawww/records/error.go:86
github.com/decred/politeia/politeiawww/records.(*Records).HandleNew
```
You'll …
=> multi: Add pkg/errors stack traces.

politeiawww/client/ticketvote.go, politeiawww/cmd/pictl/cmdvotetestsetup.go, politeiawww/cmd/politeiavoter/politeiavoter.go, politeiawww/cmd/politeiavoter/retry.go, politeiawww/cmd/politeiavoter/trickle.go
=> politeiavoter: Migrate to new APIs.

politeiawww/cmsdatabase/cockroachdb/cockroachdb.go
This fixes proposal billing showing all versions of line items in the response instead of just the most recent versioned one.
Closes #1424
=> cms: Fix line items by proposal token for versions

politeiawww/cmsaddresswatcher.go, util/paywall.go
Instead of only looking at transactions that have the legacy Treasury Subsidy address as a prevout, we know can just look at transaction type for the found transactions' vout.  If any are treasurygen then we can be assured that we're looking at a treasury spend and it should be considered to be a payout for cms invoice addresses.
=> [cms] Update addresswatcher for treasury spends

politeiawww/cmsdatabase/cockroachdb/cockroachdb.go, politeiawww/invoices.go
Closes GUI issue 2423
Previously all versions of any invoice was being returned by these requests.  Now only the most recent (max version) one will be.
=> cms: Fix invoices requests for different versions

politeiawww/cmd/politeiavoter/politeiavoter.go
If the server returned a 500 on an attempt to cast a ballot of votes,
politeiavoter was treating this as a terminal condition and exiting.
This diff updates politeiavoter to add these votes to the retry queue
instead.
=> politeiavoter: Retry votes on 500s.

politeiad/config.go
Config validation that is specific to tstore was being run when the
tstore backend was not being used.  This diff fixes that.
=> politeiad: Fix tstore config validation.

politeiad/backendv2/verify.go
When the timestamp verify functions were moved out of the tstore package
it silently broke the `politeiaverify` tool. `politeiaverify` now
returns the following error when attempting to verify timestamps.
`LogHasher(RFC6962_SHA256) is an unknown hasher`
Importing the `google/trillian/merkle/rfc6962` using a blank identifier
fixes this issue.
=> d/backendv2: Fix trillian rfc6962 import.

politeiad/backendv2/tstorebe/plugins/usermd/cmds.go
Closes #1443 
The API specifies that the tokens from the user records route should be
sorted newest to oldest. The implemenation was returning them oldest to
newest. This diff fixes this bug.
=> usermd: Fix user tokens sorting bug.

politeiawww/cmd/shared/users.go, politeiawww/user/mysql/mysql.go, politeiawww/user/mysql/mysql_test.go
This commit fixes a bug in the mysql implementation of the `user.Database` interface 
where user identities weren't synced to the db which caused the bug in the search user by
public key feature reported on #1456.
This part is done automatically by `gorm` in the `cockroachdb` implementation as the
`User` model has a list of `Identity` items and `gorm` syncs the identities to db each time
we save the `User` model on db.
This diff upserts the user identities to the `identties` table manually using a sql transaction 
after each user update - see `UserUpdate` func. 
Closes #1456.
=> mysql: Upsert user's identities on user update.

politeiawww/user/mysql/mysql.go, politeiawww/user/mysql/mysql_test.go
This diff migrates the user mysql database columns to follow the 
snake case naming convention - `this_is_a_example`.
Closes #1457.
=> mysql: Consistent table and columns naming convention.

politeiawww/comments/process.go
This commit sorts the comment votes list by timestamp prior
to returning them.
Closes #1454.
=> comments: Sort votes by timestamp.

politeiawww/comments/process.go
This diff adds the record state to the `CommentVote` struct returned
from `convertCommentVotes`.
Closes #1452.
=> Comment votes: Return record state.

politeiawww/convert.go, politeiawww/dcc.go
Previously there was intermingling of pubkeys and userIDs which was causing errors.  This now properly updates the cmsdatabase entries with the user ids of any support or opposition.
=> cms: Fix DCC support/oppose id update

politeiawww/email.go
This diff changes the password changed email title 
from `Password Changed - Security Verification` 
to `Password Changed - Security Notification`.
Closes #1465.
=> politeiawww: Change `password changed` email title.

politeiad/plugins/usermd/usermd.go, politeiawww/api/records/v1/v1.go
This diff fixes a typo in in the JSON of the `Reason` field of a record
status change. This changes the structure that is saved to disk, but the
status change reason is only required when censoring or abandoning
proposals and no proposals have been censored or abandoned yet since the
launch of the new politeia site. We can still fix this before it becomes
a permanent bug.
=> multi: Fix set status json typo.

politeiad/api/v2/v2.go, politeiad/backendv2/backendv2.go, politeiad/backendv2/tstorebe/plugins/comments/cmds.go, politeiad/backendv2/tstorebe/plugins/plugins.go, politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go, politeiad/backendv2/tstorebe/tstore/blobclient.go, politeiad/v2.go, politeiawww/api/comments/v1/v1.go, politeiawww/api/ticketvote/v1/v1.go, politeiawww/comments/error.go, politeiawww/ticketvote/error.go
This diff redefines the `plugins.ErrDuplicateBlob` error on the backend as `backend.ErrDuplicatePayload`, since we now key-off this error on the API layer. Now it handles gracefully this error that may arise when calling the `BlobSave` function with a duplicate payload. It also refactors `politeiawww/comments/error.go` to match the standard of other plugins when dealing with politeiad user errors.
Closes #1455
=> multi: Handle duplicate payload error gracefully upon saving blobs

politeiawww/cmd/politeiavoter/politeiavoter.go
This diff moves the dcrwallet password prompt to the begining of the
voting function so that the user does not have to wait for the expensive
O(n) wallet calls to complete in order to input their password. It also
adds in a dcrwallet call that verifies the password is correct.
This patch was submitted by marcopeereboom.
=> politeiavoter: Update prompt pass placement.

politeiawww/records/process.go
This diff adds a missing error return on `processDetails` function.
=> records: Add missing error return.

politeiad/api/v2/v2.go, politeiawww/api/comments/v1/v1.go, politeiawww/api/pi/v1/v1.go, politeiawww/api/records/v1/v1.go, politeiawww/api/ticketvote/v1/v1.go
This adds documentation for undocumented exported names in multiple
parts of the codebase:
- www: comments API. 
- www: records API.
- www: tikcetvote API.
- d: v2 API.
=> multi: Document exported names.

politeiad/backendv2/tstorebe/store/store.go
This diff fixes a memory leak that was caused by the key-value store
gzip reader not being closed out when decoding a blob.
This bug was originally intoduced in #951 and was carried over to 
politeiad in #1180.
=> store: Close deblob reader.

politeiawww/user/mysql/mysql.go
This diff fixes a bug in the MySQL user database implementation where
the `u_blob` column type defined as `BLOB` which wasn't enough in some
cases where the user had 300+ active identities and creating new
identity resulted in: `Error 1406: Data too long for column 'u_blob' at
row 1`.
This commit fixes the bug described above by changing the `u_blob`
column type to `LONGBLOB` which should be able to store up to:
4,294,967,295 bytes.
=> MySQL: fix u_blub user table column bug.

politeiawww/records/process.go
This commit fixes a bug in `SetStatusReply` where it included the
username of the user who set the record status instead on the record's
author username.
=> records: fix SetStatusReply wrong username bug.

politeiawww/config.go, politeiawww/config/config.go, politeiawww/middleware.go, politeiawww/middleware_test.go, politeiawww/politeiawww.go, politeiawww/www.go
This diff makes the following changes to politeiawww:
- Adds req body size limit middleware to the politeiawww router.
- Adds tests to verify the middleware behavior.
- Adds a client read limit to the politeiawww websocket implementation.
- Add politeiawww config options for both the req body size limt and the
websocket read limit.
=> politeiawww: Add server read limits.

politeiad/config.go, politeiad/middleware.go, politeiad/middleware_test.go, politeiad/politeiad.go
This diff makes the following changes to politeiad:
- Cleans up the existing middleware. Instead of registering middleware
on individual routes, the middleware is now registered on the router
itself.
- Adds new middleware for a maximum request body size.
- Adds tests to verify the request body size middleware.
- Adds a config options to make the maximum request body size
configurable.
=> politeiad: Cleanup middleware.

politeiad/config.go, politeiad/politeiad.go, politeiawww/config.go, politeiawww/config/config.go, politeiawww/politeiawww.go, politeiawww/www.go
This diff adds read and write timeouts to both the politeiawww and
politeiad servers. Config options are also added to allow these values
to be configurable at runtime.
=> multi: Add read/write constraints to servers.

politeiad/backendv2/backendv2.go, politeiad/backendv2/tstorebe/plugins/comments/comments.go, politeiad/backendv2/tstorebe/plugins/dcrdata/dcrdata.go, politeiad/backendv2/tstorebe/plugins/pi/pi.go, politeiad/backendv2/tstorebe/plugins/plugins.go, politeiad/backendv2/tstorebe/plugins/ticketvote/ticketvote.go, politeiad/backendv2/tstorebe/plugins/usermd/usermd.go, politeiad/backendv2/tstorebe/tstore/tstore.go, politeiad/backendv2/tstorebe/tstorebe.go, politeiad/config.go, politeiad/politeiad.go
This diff adds a `--fsck` flag to politeiad that, when provided,
performs synchronous filesystem checks on startup for all record and
plugin data. This includes verifying the coherency of cached data.
The fscks have not been implemented in this diff, but notes have been
added to the various fsck functions to help with the implementation.
=> politeiad: Setup fscks.

politeiawww/api/pi/v1/v1.go
This diff fixes a typo in the politeiawww pi API Summary struct where
the json key of the Status was defined as "string" instead of "status".
=> pi: Fix typo in `Summary.Status` field json key.

politeiad/backendv2/tstorebe/inventory.go, politeiad/backendv2/tstorebe/tstorebe.go
This diff adds a cache rebuild for the record inventory with the
filesystem check command `--fsck`.
Part of #1511
=> tstorebe: Add record inventory fsck.

politeiad/backendv2/tstorebe/plugins/pi/cmds.go, politeiad/backendv2/tstorebe/plugins/pi/hooks.go, politeiad/backendv2/tstorebe/plugins/pi/pi.go, politeiad/client/pi.go, politeiad/plugins/pi/pi.go, politeiawww/api/pi/v1/v1.go, politeiawww/client/pi.go, politeiawww/cmd/pictl/cmdhelp.go, politeiawww/cmd/pictl/cmdproposalbillingstatuschanges.go, politeiawww/cmd/pictl/pictl.go, politeiawww/cmd/pictl/proposal.go, politeiawww/pi.go, politeiawww/pi/pi.go, politeiawww/pi/process.go
Clients need to be able to retrieve the full billing status metadata so
that the admin username can be displayed and so that the admin signature
is available if the client wants it. In order to do this, API needs to
be added to the pi plugin for retrieving the full billing status change
metadata objects.  With that said, the current `StatusReason` in not
needed in the pi `Summary` and can be removed as this feature wasn't
deployed to production yet.
**Implementation:**
- Remove `StatusReason` from pi API `Summary`.
- Add new `/billingstatuschanges` route to the pi API.
- Add new pictl command `pictl proposalbillingstatuschanges "token"`
command which consumes the new pi API.
---
Closes #1524.
=> pi: Add API to retreive billing status changes.

politeiawww/config.go, politeiawww/events/log.go, politeiawww/legacy/cmsdatabase/cockroachdb/log.go, politeiawww/legacy/codetracker/github/database/cockroachdb/log.go, politeiawww/legacy/codetracker/github/log.go, politeiawww/legacy/comments/log.go, politeiawww/legacy/log.go, politeiawww/legacy/pi/log.go, politeiawww/legacy/testing.go, politeiawww/legacy/ticketvote/log.go, politeiawww/legacy/user/cockroachdb/log.go, politeiawww/legacy/user/localdb/log.go, politeiawww/legacy/user/mysql/log.go, politeiawww/log.go, politeiawww/logger/logger.go, politeiawww/mail/log.go, politeiawww/middleware.go, politeiawww/politeiawww.go, politeiawww/records/log.go, politeiawww/sessions/log.go, politeiawww/www.go
This diff moves the logging state into into a new `logger` package
instead of storing it in the global main scope. This allows external
packages, such as plugins, to setup their own loggers without having to
add any code to main. This will allow plugins to be completely self
contained.
=> politeiawww: Add logger package.

politeiawww/legacy/pi/pi.go
This diff removes a validation in the pi plugin which prevented
setting the `billingstatuschangesmax` as zero. We would like to allow that
as there may be cases where the sysadmin would want to disallow billing
status changes temporarily.
=> pi: Allow zero `billingstatuschangesmax`.

politeiawww/cmd/politeiaverify/politeiaverify.go, politeiawww/cmd/politeiaverify/ticketvote.go
This updates the politeiaverify filename regular expressions to be able
to match against short tokens. politeiagui switched to short token
filenames at some point, causing politeiaverify to not recognize the
filenames anymore.
=> politeiaverify: Allow short token filenames.

politeiad/plugins/ticketvote/ticketvote.go, politeiawww/api/ticketvote/v1/v1.go, politeiawww/cmd/pictl/cmdrfptest.go, politeiawww/cmd/pictl/cmdvotestart.go, politeiawww/cmd/pictl/cmdvotesummaries.go, politeiawww/cmd/pictl/cmdvotetestsetup.go, politeiawww/cmd/pictl/print.go, politeiawww/cmd/pictl/ticketvote.go
This commit fixes a bug that was introduced by 63d933ce that caused the
percent signs in the vote summary printing to be printed incorrectly.
`printf(voteSummaryString())`
The above code is same thing as:
`fmt.Printf("%\n") // Prints "%!(MISSING)"`
These should be:
`printf("%v\n", voteSummaryString())`
It also cleans up the `voteSummaryString()` function and standardizes
the vote parameters (duration, quorum, passing) used in various vote
commands.
=> pictl: Fix print bug and standardize vote params.

politeiawww/cmd/pictl/cmdlegacytest.go, politeiawww/cmd/pictl/cmdrfptest.go, politeiawww/cmd/pictl/cmdvotetestsetup.go, politeiawww/cmd/pictl/testing.go
This diff uses the `cmdVoteStart` command directly when starting 
a normal or a runoff vote; It ditches the `voteRunoff` and uses the new
`runoff` bool param in `voteStart` to start a runoff vote.
=> pictl: use cmdVoteStart in test commands.

politeiad/backendv2/tstorebe/plugins/pi/cmds.go
Closes #1574.
This commit prevents billing status changes on RFP proposals. RFP
proposals do not request funding or bill against the treasury, so they
do not have a billing status. This does not include RFP submissions,
which do request funds and bill against the treasury.
=> pi: Fix RFP billing status bug.

politeiad/backendv2/tstorebe/plugins/pi/cmds.go, politeiad/backendv2/tstorebe/plugins/pi/cmds_test.go, politeiad/plugins/pi/pi.go
Closes #1577
This commit adds an 'approved' proposal status to the pi plugin.
Previously, the proposal status was considered to be 'active', meaning
the proposal is active and allowed to be billed against, once the
proposal vote was approved. This is fine for standard proposals. RFP
proposals, however, do not request funds and do not bill against the
treasury. The 'active' status does not apply to them. Once an RFP vote
is approved, the RFP proposal status is 'approved'. This does not apply
to RFP submissions.
=> pi: Add approved proposal status.

politeiad/backendv2/tstorebe/plugins/ticketvote/hooks.go
Closes #1576
This commit skips the vote metadata validation if the record is being
censored or abandoned. It does not matter if fields have become outdated
if the record is not being made public.
=> ticketvote: Fix status change validation bug.

politeiawww/cmd/politeiavoter/config.go, politeiawww/cmd/politeiavoter/help.go, politeiawww/cmd/politeiavoter/politeiavoter.go
This diff introduces the following improvements for the `politeiavoter`
help output to match the `dcrctl` behavior:
- `politeiavoter -h` prints application options.
- `politeiavoter -l` prints application commands - `long: listcommands`.
- `politeiavoter help <command>` prints a detailed help message for the
command.
- List available commands if no command was specified.
- List available commands if unknown command was specified.
- Verify the provided command before trying to connect to wallet.
- Try to connect to the wallet only if the command requires a connected
wallet.
---
Closes #1567.
=> politeiavoter: improve help output

politeiawww/cmd/politeiavoter/config.go, politeiawww/cmd/politeiavoter/sampleconfig/sampleconfig.go
This commit fixes a few bugs with the politeiavoter config.
- The correct defaults are added for the `walletgrpccert`, `clientcert`,
`clientkey` settings. The defaults are now printed as part of the help
message.
Before
```
--walletgrpccert=   Wallet GRPC certificate
--clientcert=       Path to TLS certificate for client authentication (default: client.pem)
--clientkey=        Path to TLS client authentication key (default: client-key.pem)
```
After
```
--walletgrpccert=   Wallet GRPC certificate (default: /home/luke/.dcrwallet/rpc.cert)
--clientcert=       Path to TLS certificate for client authentication (default: /home/luke/.politeiavoter/client.pem)
--clientkey=        Path to TLS client authentication key (default: /home/luke/.politeiavoter/client-key.pem)
```
- The default …
=> politeiavoter: Fix config bugs.

politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go, politeiad/plugins/ticketvote/ticketvote.go, politeiawww/api/ticketvote/v1/v1.go, politeiawww/cmd/pictl/cmdcastballot.go, politeiawww/cmd/politeiavoter/trickle.go, politeiawww/legacy/proposals.go, politeiawww/legacy/ticketvote/process.go
This commit changes the `ErrorCode` field in the `CastVoteReply` structs
to a pointer, in order to  fix a bug where default error code value
`ErrorCodeInvalid` was returned on success.
After this, in case of success the error code pointer will be nil.
--- 
Closes #1557.
=> ticketvote: Cast vote error format.

politeiawww/cmd/pictl/cmdseedproposals.go, politeiawww/cmd/pictl/proposal.go
This commit adds a --proposalstatus option to the `pictl seedproposals`
command. If provided, all proposals submitted by the command will be set
to the specified proposal status. This makes it easier to fine tune your
testing environment, which is desirable when needing to test specific
features or bug fixes.
It also makes two additional changes to the `seedproposals` command:
- Updates the comment and comment like defaults to be more reasonable.
- Switches the hard coded proposal statuses out for the newly added pi
plugin proposal statuses.
=> pictl: Add proposal status flag to seedproposals.

politeiawww/legacy/user/mysql/mysql.go, politeiawww/legacy/user/mysql/mysql_test.go, politeiawww/sessions/mysql/log.go, politeiawww/sessions/mysql/mysql.go, politeiawww/sessions/mysql/mysql_test.go
This diff adds a MySQL implementation for the sessions.DB interface.
---
Closes #1558.
=> sessions: Implement mysql db.

politeiad/backendv2/tstorebe/plugins/usermd/cache.go, politeiad/backendv2/tstorebe/plugins/usermd/usermd.go, politeiad/plugins/usermd/usermd.go
This diff adds a `fsck` command to the `usermd` plugin using the
following process:
1. For each record, get the user metadata file from the db.
2. Get the user cache for the record's author.
3. Verify that the record is listed in the user cache under the
correct category. The tokens listed in the user cache are
ordered by the timestamp of their most recent status change
from newest to oldest. If the record is not found in the user
cache, add it.
---
Closes #1511.
=> usermd: Add cache fsck.

politeiawww/cmd/pictl/cmdcommentvote.go, politeiawww/cmd/pictl/cmdproposaledit.go, politeiawww/cmd/pictl/cmdproposalnew.go, politeiawww/cmd/pictl/cmdproposalsetbillingstatus.go, politeiawww/cmd/pictl/cmdrfptest.go, politeiawww/cmd/pictl/cmdseedproposals.go, politeiawww/cmd/pictl/cmdvoteauthorize.go, politeiawww/cmd/pictl/comment.go, politeiawww/cmd/pictl/pictl.go, politeiawww/cmd/pictl/proposal.go, politeiawww/cmd/pictl/ticketvote.go, politeiawww/cmd/pictl/time.go, politeiawww/cmd/shared/config.go
This commit adds a --timer flag to pictl that prints command execution
time statistics when used. This can be helpful when performance testing.
It also cleans up the functions related to converting between unix
timestamps and human readable strings.
```
---Timer Stats---
Start  : 23 Nov 2021 11:24:06am
Stop   : 23 Nov 2021 11:24:07am
Elapsed: 971.65346ms
```
=> pictl: Add timer flag.

politeiawww/cmd/politeiavoter/politeiavoter.go
This commit updates the summary printing to consider already voted
errors as being successfully cast votes.
Already voted errors are not considered to be failures because they
occur when a network error or dropped client connection causes
politeiavoter to incorrectly think that the first attempt to cast the
vote failed. politeiavoter will attempt to retry the vote that it has
already successfully cast, resulting in the already voted error.
Printing these errors as failures is misleading to the user, who will
likely consider a failure as meaning the vote was not successfully cast,
which is incorrect in this case.
=> politeiavoter: Improve summary printing.

politeiawww/cmd/politeiavoter/trickle.go
This commit fixes a bug that was causing politeiavoter to continually
retry casting a vote when a duplicate vote error is returned.
Duplicate vote errors can occur when the first attempt results in a
network error where the vote is actually cast, but politeiavoter reports
it as failed. Example, the client connection drops after the vote has
already been submitted to the backend.  politeiavoter will attempt to
re-submit these votes and duplicate vote errors will be returned.
Previously, a duplicate vote error was considered a success case and the
vote was no longer attempted to be re-cast.
bc7da5b1 introduced a change that prevented the success case code path
from being reached on duplicate vote errors. This resulted in
politeiavoter continually retrying these votes when it should have …
=> politeiavoter: Fix duplicate vote bug.

politeiad/batch.go, politeiad/batch_test.go, politeiad/v2.go
Part of #1582.
This commit updates the politeiad batch read route to execute the read
commands concurrently instead of serially in order to improve
performance.
A batch of read commands is executed using a sync WaitGroup counter to
track the completion status of the commands and a shared memory cache to
aggregate the replies. Each batch uses its own unique memory cache.
This performance optimization cut the execution time of a 5 command batch
by ~50%.
=> politeiad: Execute batch reads concurrently.

politeiad/backendv2/tstorebe/plugins/pi/statusescache.go
This commit makes two minor tweaks to the proposal status cache:
1. Only overwrite existing entries if the proposal status has changed.
The logging was too noisy without this.
2. Add the proposal status to the debug logging along with the token.
Example log statements:
```
2021-12-03 15:23:36.390 [DBG] PLUG: proposalStatuses: updated entry 2f459c359620f942 from unvetted to under-review
2021-12-03 15:30:40.254 [DBG] PLUG: proposalStatuses: added entry 05e06fe789cebf7e with status active
2021-12-03 15:31:40.254 [DBG] PLUG: proposalStatuses: removed entry acafd57e67a0e519
```
=> pi: Update proposal status cache logging.

politeiawww/cmd/politeiavoter/config.go, politeiawww/cmd/politeiavoter/politeiavoter.go, politeiawww/cmd/politeiavoter/politeiavoter_test.go, politeiawww/cmd/politeiavoter/trickle.go, politeiawww/cmd/politeiavoter/trickle_test.go
This commit improves the --hoursprior UX by updating politeiavoter to
the following behavior.
By default, the trickler will trickle in votes for the full duration of
the vote minus 12h.
The --voteduration and the --hoursprior settings are not allowed to be
used at the same time. An error is returned if they are attempted to be
used together.
If a --voteduration is specified, the votes are trickled in over the
specified duration.
If a --hoursprior is specified, the votes are trickled in over the full
duration of the vote minus the specified hours prior.
If the calculated vote duration is less than 24h, the user MUST
manually set the duration using the --voteduration flag.
**Example 1**
A vote has 6 days remaining. The user attempts to trickle in their votes
over a 3h period using …
=> politeiavoter: Improve hoursprior UX.

politeiad/backendv2/tstorebe/store/mysql/encrypt_test.go, politeiad/backendv2/tstorebe/store/mysql/mysql.go, politeiad/backendv2/tstorebe/store/mysql/mysql_test.go, politeiad/v2.go, unittest/unittest.go
Closes #1608 
This commit updates the mysql package to batch SELECT queries if the
number of records being requested exceedes the MySQL limit for the
maximum number placeholders that can be included in a prepared
statement (65,535 placeholders).
As a side note, manually testing this commit required loading a tlog
tree with >65,535 leaves. This was surprisingly difficult to do and
highlights how we're using tlog in a way that it's not really built for.
We will need to write our own append-only log implementation at some
point in order to remove the performance bottlenecks that tlog has.
Log statements from the manual testing are shown below.
```
2021-12-20 09:04:55.964 [DBG] STOR: Get 83698 blobs using 2 prepared statements
2021-12-20 09:04:55.965 [DBG] STOR: Executing select statement 1/2 …
```
=> mysql: Batch select queries when required.

politeiawww/api/comments/v1/v1.go, politeiawww/legacy/comments/comments.go
This commit adds the `allowextradata` plugin setting value to the
comments API policy route as it might be useful for clients.
---
Closes #1600.
=> comments: Add `allowextradata` to the policy reply.

politeiad/backendv2/tstorebe/plugins/comments/cmds.go, politeiad/backendv2/tstorebe/plugins/comments/cmds_test.go, politeiad/backendv2/tstorebe/plugins/comments/comments.go, politeiad/plugins/comments/comments.go, politeiawww/api/comments/v1/v1.go, politeiawww/cmd/pictl/cmdcommentvotes.go, politeiawww/cmd/pictl/comment.go, politeiawww/legacy/comments/comments.go, politeiawww/legacy/comments/log.go, politeiawww/legacy/comments/process.go, politeiawww/legacy/pi/log.go, politeiawww/legacy/ticketvote/log.go, politeiawww/records/log.go
**Background:**
The comment votes endpoint currently only allows you to retrieve comment
votes for a specific user ID. This initial implementation was
restrictive because that was all that politeiagui needs. Opening up the
endpoint to allow a client to retrieve all comment votes made on a
proposal, without needing to provide a user ID, has been requested in
order to help analyze the proposal process. Comment votes are already
public, so there is no reason to not allow this.
**Implementation:**
- Make the user ID field optional.
- Return paginated comment votes. 
- Add A page number field to the command payload, which defaults to 1 if
not provided.
- Add new `votesPageSize` comments plugin setting to use it in both of
`politeiawww` & `politeiad`
- Add the new `votesPageSize` plugin setting …
=> comments: Allow retrieving all comment votes.

politeiad/backendv2/tstorebe/plugins/comments/comments.go, politeiad/backendv2/tstorebe/plugins/pi/pi.go, politeiad/backendv2/tstorebe/plugins/ticketvote/ticketvote.go, politeiad/plugins/comments/comments.go, politeiad/plugins/pi/pi.go, politeiad/plugins/ticketvote/ticketvote.go, politeiawww/api/comments/v1/v1.go, politeiawww/api/pi/v1/v1.go, politeiawww/api/ticketvote/v1/v1.go, politeiawww/cmd/politeiavoter/politeiavoter.go, politeiawww/legacy/comments/comments.go, politeiawww/legacy/comments/process.go, politeiawww/legacy/pi/pi.go, politeiawww/legacy/pi/process.go, politeiawww/legacy/ticketvote/process.go, politeiawww/legacy/ticketvote/ticketvote.go
Until this commit we have defined page sizes as global consts in our
plugins, this might result in some duplicated code if the page size is
needed in both `politeiawww` & `politeiad`.
This resolves the issue mentioned above by defining the plugins page
sizes as plugin setting, that way we have it available in both places
and easily configurable by sys admin without any code changes.
---
Closes #1603.
=> multi: Add routes page sizes as plugin settings.

politeiad/backendv2/tstorebe/tstore/record.go
This diff ensures that the ordering of the records entries returned from the
backend is consistent.
---
Closes #1595
=> politeiad: Consistent record entries ordering.

politeiad/backendv2/tstorebe/plugins/comments/cmds.go, politeiad/backendv2/tstorebe/plugins/comments/cmds_test.go, politeiad/backendv2/tstorebe/plugins/comments/comments.go, politeiad/backendv2/tstorebe/plugins/comments/testing.go, politeiad/client/comments.go, politeiad/plugins/comments/comments.go, politeiawww/api/comments/v1/v1.go, politeiawww/client/comments.go, politeiawww/cmd/pictl/cmdcommentedit.go, politeiawww/cmd/pictl/cmdhelp.go, politeiawww/cmd/pictl/pictl.go, politeiawww/legacy/comments/comments.go, politeiawww/legacy/comments/pi.go, politeiawww/legacy/comments/process.go, politeiawww/legacy/routes.go
This commit adds temporary comment edits feature.
**Implementation:**
- Add two new settings to the comments plugin:
- `allowedits` - global flag to enable comments edits.
- `editperiodtime` - defines the maximum period of time in seconds
where comments are still editable.
- Add logic to `politeiad` to ensure edits are allowed only during the
time interval set by the new `editperiodtime` setting.
- Add the new settings to the comments API policy route reply.
- Add an `/edit` route to the comment API.
- Add a `pictl commentedit` command.
---
Closes #1597.
=> multi: Add temporary comment edits.

politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go, politeiad/backendv2/tstorebe/plugins/ticketvote/inventory.go, politeiad/plugins/ticketvote/ticketvote.go
This diff ditches the ticketvote plugin page sizes which used to be defined as
constants. It uses the new page sizes which are defined as plugin settings.
This is a leftover from #1604.
=> politeiad: Cleanup deprecated page sizes

politeiawww/cmd/pictl/cmdcomments.go, politeiawww/cmd/pictl/cmdcommenttimestamps.go
This diff fixes a bug in `pictl commenttimestamps` where no timestamps
were fetched if the no comment IDs were provided, this is not the
expected behavior as it says in the `commenttimestamps` command help
message:
> If comment IDs are not provided then the timestamps for all comments will be
returned.
In addition, this commit adds pagination to the `commenttimestamps`
command to allow fetching all comment timestamps page by page when
a proposal has more than one page of comments. This also allows users to
request the timestamps of more than one page using the `commentIDs`
command argument.
--- 
Closes #1616.
=> pictl: `commenttimestamps` improvements.

politeiad/backendv2/tstorebe/tstore/tstoreclient.go
This diff fixes a bug in `tstoreClient`'s `CacheGet` function. Before
this it returned a map with the keys prefixed with the plugin ID of the
calling plugin, this commit fixes that issue and returns a map with
the original keys passed to the `CacheGet` function.
=> tstore: unprefix returned keys from `CacheGet`.

politeiad/backendv2/tstorebe/plugins/comments/timestamp.go, politeiad/backendv2/tstorebe/plugins/comments/timestamp_test.go, politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go, politeiad/backendv2/tstorebe/plugins/ticketvote/timestamp.go, politeiad/backendv2/tstorebe/plugins/ticketvote/timestamp_test.go
This diff improves the performance of retrieving cast vote, vote auth
and vote details timestamps from ticketvote plugin. It uses the
key-value store to cache final timestamps which have been timestamped on
the DCR chain as the performance of evaluating it on runtime is
proportional to the tree size which makes it unacceptably slow in prod
where the trees has ~30k leaves.
**Benchmark:** 
I have tested the performance improvements of this commit locally with a
proposal which has a tlog tree with ~10k leaves(comments) with 5 ticket
votes, and had x5 faster response times.
before:
```
$ pictl votetimestamps 328d27b 1 --timer
---Timer Stats---
Start  : 27 Jan 2022 5:16:07pm
Stop   : 27 Jan 2022 5:16:07pm
Elapsed: 367.31476ms
```
after:
```
$ pictl votetimestamps 328d27b 1 --timer
---Timer …
```
=> ticketvote: Cache final timestamps.

politeiad/backendv2/tstorebe/plugins/pi/hooks.go, politeiad/plugins/pi/pi.go
This diff adds a new `LegacyToken` field to the `ProposalMetadata` struct. It
will be populated only for legacy gitbe proposals which will be imported
to the backend in the next step.
This commit also adds a validation to the `pi` plugin to ensure that
the new `LegacyToken` field in not set during the normal proposal
submissions.
=> pi: Add `LegacyToken` to `ProposalMetadata`.

politeiad/plugins/pi/pi.go, politeiawww/api/pi/v1/v1.go
This fixes two issues with commit 38b63bd.
1. LegacyToken should have the omitempty JSON tag since it will only be
set for certain proposals and the field should not be included in the
encoded JSON that is saved to disk if it is empty.
2. LegacyToken was not added to the politeiawww pi API.
=> pi: Fix LegacyToken errors.

politeiawww/legacy/user/mysql/mysql.go
This fixes some incorrectly named columns in a sql insert statement. 
The statement was part of a function that is only used during database
migrations, so it does not impact normal operation.
This bug was introduced by 5b5c5ed71.
=> mysql: Fix column naming bug.

politeiad/backendv2/tstorebe/tstore/plugin.go, politeiad/backendv2/tstorebe/tstore/tstoreclient.go
The adds an exported initialization function for the tstore client that
is used by plugins.
This is required for #1632.
=> tstore: Add tstore client init function.

politeiawww/legacy/user/mysql/mysql.go
This fixes a bug in the InsertUser function of the mysql user database
implementation.
When a new user record is inserted into the database, both the users
table and the identities table must be updated. The InsertUser function
was not updating the identities table, which was causing user by public
key lookups to fail.
The InsertUser function is only used during database migrations. This
bug does not impact regular politeia use.
This bug was introduce by 0b1982a.
=> mysql: Fix InsertUser identity bug.

politeiad/backendv2/tstorebe/plugins/pi/pi.go
The min start date plugin setting was not being recognized as a plugin
setting.
This bug was introduced by 8c95e6412.
=> pi: Fix min start date setting bug.

politeiad/backendv2/tstorebe/plugins/pi/hooks.go
This fixes a bug with the start and end date error messages. The error
messages were referencing the default setting values instead of the
actual setting values.
This bug was introduced by 8c95e64.
=> pi: Fix plugin setting error messages.

politeiad/backendv2/tstorebe/plugins/comments/cmds.go, politeiad/backendv2/tstorebe/plugins/comments/comments.go, politeiad/backendv2/tstorebe/plugins/comments/fsck.go, politeiad/backendv2/tstorebe/plugins/comments/recordindex.go, politeiad/backendv2/tstorebe/plugins/plugins.go
This rewrites the comments plugin fsck function.
The bug investigation was initially kicked off due to a panic from
a nil pointer reference (a map entry was not being initialized
correctly), but I ended up finding multiple bugs when I started
looking through the code, so I rewrote the full fsck function to
ensure correctness.
These bugs were introduced by 8865f31.
=> comments: Fix fsck bugs.

politeiad/backendv2/tstorebe/tstore/testing.go, politeiad/backendv2/tstorebe/tstore/tstore.go, politeiad/backendv2/tstorebe/tstorebe.go, politeiad/config.go, politeiad/politeiad.go
This commit removes the ability to use leveldb as the tstore key-value
store.
tstore already requires a MySQL instance to be running since trillian
uses MySQL. It doesn't make a whole lot of sense to have a config option
to use leveldb as the tstore key-value store since MySQL is already a
requirement. Removing this option simplifies the politeiad setup and
makes the code easier to maintain. MySQL is now used by default.
If we move the trillian functionality into politeia and remove the
trillian dependency at some point in the future, then it may make sense
to add a leveldb key-value store option back in.
=> politeiad: Remove leveldb tstore config option.

politeiad/backendv2/tstorebe/store/localdb/localdb.go, politeiad/backendv2/tstorebe/store/mysql/mysql.go, politeiad/backendv2/tstorebe/store/store.go
This commit updates the tstore backend key-value store to allow for
overwrites when using the Put() method. New entries are inserted.
Existing entries are updated.
After reviewing the tstore architecture, I realized that the duplicate
entry error that was added in 950620c was the wrong way to handle
duplicate key errors.
tstore saves data using a 2-step process. Step 1, save the data to the
key-value store. Step 2, append the hash of the data onto the trillian
tree. If step 2 fails, the key-value store entries are not unwound, they
are simply left in the key-value store. It was originally setup like
this to keep the required database primitives as simple as possible to
allow for flexibility in the database choice. The thought was that, at
some point in the future, it might be possible to …
=> tstorebe/store: Allow put overwrites.

politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go, politeiad/plugins/ticketvote/ticketvote.go
This commit adds the timestamp of the vote status change to the vote
summary structure.
The function that builds the vote summary contains the logic for
determining the vote status of a record. Including the timestamp of the
vote status change in the vote summary ensures that the logic for
determing the vote status and it's associated timestamp remains in one
place.
This addition also allows the vote inventory to be rebuilt using just
the vote summaries, without having to pull any additional data.
=> ticketvote: Add the timestamp to the vote summary.

politeiad/backendv2/tstorebe/plugins/ticketvote/cmds.go, politeiad/backendv2/tstorebe/plugins/ticketvote/fsck.go, politeiad/backendv2/tstorebe/plugins/ticketvote/summaries.go, politeiad/backendv2/tstorebe/plugins/ticketvote/ticketvote.go
This commit implements the ticketvote plugin Fsck function. This
function rebuilds all of the ticketvote plugin caches.
=> ticketvote: Implement fsck.

politeiad/cmd/legacypoliteia/cmd_import.go
This commit adds some additional error handling for when trillian
unexpectedly fails, allowing the import command to continue without also
failing. This edge case was encountered during testing.
=> legacypoliteia: Handle trillian edge case failure.

politeiad/backendv2/tstorebe/tstore/tstoreclient.go
This commit improves the error message that is returned when the
expected number of blobs are not found in the key-value store.
Previously, the keys that were not found were being included in the
error message. This made the error message illegible when a large number
of keys were being requested, like when all of a proposal's cast votes
are being requested.
=> tstore: Improve blobs not found error.

politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
This commit updates the politeiawww_dbutil command to only read a single
user into memory at a time. It was previously reading all users into
memory and then performing the migration. It also adds in some
additional validation to ensure that an incorrect paywall address index
is not being migrated over.
=> dbutil: Improve migrate cmd.

politeiad/backend/gitbe/cms.go, politeiad/backend/gitbe/decred.go, politeiad/backendv2/tstorebe/plugins/ticketvote/fsck.go, politeiad/backendv2/tstorebe/plugins/usermd/usermd.go, politeiad/backendv2/tstorebe/tstore/record.go, politeiad/backendv2/tstorebe/tstore/recordindex.go, politeiad/backendv2/tstorebe/tstorebe.go, politeiad/cmd/legacypoliteia/cmd_import.go, politeiad/cmd/legacypoliteia/gitbe/mdstreams.go, politeiad/config.go, politeiad/plugins/comments/comments.go, politeiawww/api/www/v1/v1.go, politeiawww/api/www/v2/v2.go, politeiawww/cmd/cmswww/testrun.go, politeiawww/cmd/pictl/ticketvote.go, politeiawww/cmd/politeiavoter/config.go, politeiawww/cmd/shared/config.go, politeiawww/config/config.go, politeiawww/user/user.go
This commit updates the repo with comment formatting required by gofmt
for go 1.19.
=> multi: Go 1.19 doc comment formatting.

politeiad/config.go, politeiad/politeiad.go, politeiawww/cmd/politeiavoter/config.go, politeiawww/cmd/shared/config.go, politeiawww/config/config.go, politeiawww/handlers.go, politeiawww/legacy/www.go, politeiawww/legacy/www_test.go, politeiawww/politeiawww.go, util/version/version.go, util/version/version_buildinfo.go, util/version/version_nobuildinfo.go
This commit adds the version changes from decred/dcrctl#44. 
The original commit message is shown below:
This reworks the way versions are handled internally to reverse the
semantics such that the individual semver components (major, minor,
patch, prerelease, and buildmetadata) are parsed from a full string and
exported at init time.
Also, since the version is now parsed and verified to be accurate, it
updates the pre-release parsing to properly support dots as required by
the spec.
Finally, starting with Go version 1.18, it adds the git commit hash to
the version string as buildmetadata when no buildmetadata is otherwise
specified.
This provides a few main benefits:
- Allows a single linker override to fully specify the version string
instead of having separate ones that can only …
=> version: Support single override and add git hash.

politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go
This commit fixes a bug where the dbutil command was suppose to be
checking for the mysql flag, but was not.
This bug was introduced by 0b1982a48.
=> dbutil: Fix mysql flag bug.

politeiad/backendv2/tstorebe/plugins/pi/hooks.go
This commit fixes a bug in a function that was used to determine the
most recent author update. The function was using the wrong timestamp to
determine the order of the author updates. It was using the timestamp
of the most recent comment edit when it should have been using the
timestamp of the comment creation.
This bug was introduced by b43eebdeb.
=> pi: Fix author update ordering bug.

.gitignore, politeiawww/legacy/piuser.go
This commit fixes a bug where politeiawww crashes when an error returned
for dcrdata while polling new users paywall address. This commit
swallows the error and returns a reply with hasPaid = false along with the
paywall address details.
=> politeiawww: handle dcrdata tx lookup errors

politeiawww/legacy/paywall.go
This avoids spamming the logs with dcrdata's `Unprocessable Entity` 
error.
=> piwww: avoid dcrdata's `Unprocessable Entity` err.

politeiawww/cmd/politeiavoter/politeiavoter.go
main() does not have a catch-all log for errors returned by _main(), so it is the responsibility of _main() to print or log these for every error return.
=> politeiavoter: Log errors in two unlogged error paths

go.mod, go.sum
This fixes binaries on OpenBSD which were failing to lazily link to syscall(2).
=> Bump golang.org/x/sys to latest
